### ISSUE TITLE
שליטה בסדר של רשימת הערוצים

### ISSUE THREAD

**Issue by m1tm** [Fishenzon/repo#10]
הי.
האם יש אפשרות לשליטה בסדר של הערוצים?
תודה

**Comment by Fishenzon** [comment]
@m1tm 
תראה את גירסה 1.4.2
נוספה האופציה לסדר את הערוצים דרך ההגדרות.
מספר נמוך יותר יופיע גבוה יותר ברשימה.
בחירה ב-0 עבור ערוץ תסתיר אותו מהרשימה.

**Comment by m1tm** [comment]
תודה!

**Comment by Fishenzon** [comment]
@m1tm 
תהנה
