### ISSUE TITLE
Can you add Channel9 (Rus) and i24 News (Eng)

### ISSUE THREAD

**Issue by rypz79** [Fishenzon/repo#100]
9tv.co.il (Israel Plus)
https://video.i24news.tv/page/home

Probably not because there isn't a free stream but I will ask anyway.

Thank You

**Comment by alexrait** [comment]
There is a free stream. There is an Android app - IsraTV where you can watch it.
I hope to see it in Kodi too.

**Comment by rypz79** [comment]
> There is a free stream. There is an Android app - IsraTV where you can watch it.
> I hope to see it in Kodi too.

Nice. No i24 News though.

**Comment by Fishenzon** [comment]
There are no official free streams for those channels.
IsraTV maybe free, but it don't mean that 9tv stream is free too.
