### ISSUE TITLE
מה קרה לערוץ 13?... 

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#101]
הודעה "מצטערים" .... 
החליפו לינקים?...

**Comment by Fishenzon** [comment]
צהרים טובים.
לא קרה כלום ולא החליפו שום לינק.
כמו שהיה בשבוע שעבר וכמו שיהיה מן הסתם בשבוע הבא וכמו שזה הופיע באתר של ערוץ 13,
בזמן שידור התכנית על עפרה חזה, שזכויות השידור שלה נקנו מהוט, אין שידור של זה באינטרנט.

**Comment by rafi-d** [comment]
לא ידעתי על המגבלות האלו...

תודה
