### ISSUE TITLE
ערוצי טלוויזיה לא מכילים אינפורמציה

### ISSUE THREAD

**Issue by mosheivry** [Fishenzon/repo#103]
שלום,

התקנתי את עידן פלוס על גרסת קודי האחרונה 18.9. האפליקציה מותקנת על גרסא אחרונה של אנדרואיד במכשיר מיבוקס 4.
ערוצי הטלוויזיה לא מכילים פרטים של התוכניות המשודרות. גם לוח השידורים ריק.

מה אני מפספס פה?

אגב בווינדוס 10, ובמכשיר מיבוקס קודם לא היתה בעיה דומה.

**Comment by Fishenzon** [comment]
כנראה היתה לך תקלה מקומית זמנית
זה אמור להתעדכן אוטומטית פעם ביום
אתה יכול להיכנס להגדרות של ההרחבה וללחוץ על הורדת מדריך שידורים ידנית
