### ISSUE TITLE
ערוץ 5

### ISSUE THREAD

**Issue by saronensa** [Fishenzon/repo#104]
שלום, 
ערוץ 5 לא עובד , שאר הערוצים עובדים מצויין
האם יש סיכוי שיחזור לעבוד?
תודה

**Comment by Fishenzon** [comment]
הלינק שהיה באתר הפסיק לעבוד.
אני משאיר את עדיין בהרחבה, כי כבר קרו מקרים שהלינק פתאום חזר לעבוד.
אם אראה שהוא לא חוזר אסיר את הערוץ לחלוטין

**Comment by saronensa** [comment]
תודה רבה!


בתאריך יום ד׳, 24 בפבר׳ 2021, 23:21, מאת fishenzon ‏<
notifications@github.com>:
