### ISSUE TITLE
הוספת ערוצי רדיו

### ISSUE THREAD

**Issue by tzagim** [Fishenzon/repo#105]
היי , אודה לך מאד אם תוכל להוסיף את ערוצי הרדיו הבאים
קול חי
Site: https://www.93fm.co.il
Logo: https://www.93fm.co.il/wp-content/uploads/2016/08/%D7%9C%D7%95%D7%92%D7%95-160x100c.png
URL: https://media2.93fm.co.il/live-new
לוח שידורים: https://www.93fm.co.il/schedule/?player_id=263593

קול חי מיוזיק
Site: https://kcm.fm
Logo: https://kcm.fm/static/images/logo.svg
URL: https://media2.93fm.co.il/livemusic
לוח שידורים: https://kcm.fm/Schedule

קול ברמה
Site: https://kol-barama.co.il
Logo: https://kol-barama.co.il/wp-content/uploads/2019/03/logo.png
URL: https://icy.streamgates.net/Radio_CDN/Kol_Barama/icecast.audio
לוח שידורים נמצא באתר לא הצלחתי לזהות את הכתובת שלו
יש להם גם שידורים תחת השם שואו לייב (לא ברור לי מתי זה משודר)
שואו לייב: https://a1.streamgates.net/kolbarama/video/chunks.m3u8
או 
https://cdna.streamgates.net/kolbarama/video/playlist.m3u8

קול פליי
Site: https://kol-play.co.il
Logo: https://kol-play.co.il/wp-content/themes/kolplay/images/logo.png
Url: https://radio.streamgates.net/stream/kbmusic
לוח שידורים יש באתר לא הצלחתי לזהות את הכתובת שלו

ואם יש לך מצב רוח אז גם את 
גלי ישראל
Site: http://www.gly.co.il
Logo: http://www.gly.co.il/wp-content/uploads/2017/01/logo1-copy.png
URL: http://gly-audioswitch1.ecast.co.il/live
לוח שידורים: http://www.gly.co.il/%d7%9c%d7%95%d7%97-%d7%a9%d7%99%d7%93%d7%95%d7%a8%d7%99%d7%9d/ (תמונה, לא נראה שיש מה לעשות עם זה)

תודה מראש
ותודה רבה על ההרחבה הנפלאה

**Comment by Fishenzon** [comment]
ערב טוב.
הוספתי את התחנות, למרות שהלינק של גלי ישראל מידי פעם לא עובד באתר
הוספתי מדריכים לתחנות הראשיות

**Comment by tzagim** [comment]
תודה רבה!!!

רק תיקון קטן, על גלי ישראל נכתב בטעות קול פליי

**Comment by Fishenzon** [comment]
שבוע טוב.
תודה.
תוקן בגירסה 2.9.5

**Comment by tzagim** [comment]
תודה רבה
