### ISSUE TITLE
צפייה בערוצי עידן פלוס באפל טיוי

### ISSUE THREAD

**Issue by albilia** [Fishenzon/repo#108]
שלום, 
קיימים ברשותי מכשירי אפל טיוי בבית ללא קודי, השימוש מתבצע דרך אפליקציית iptv בשם iplaytv שאליה אני מוסיף פלייליסטים כרשימות  M3u8.
רציתי לדעת האם האפליקציה הזו נתמכת על ידך באיזשהו אופן, כמו למשל רשימת M3u8 של ערוצי עידן פלוס שאותה אוכל להזין באפליקציית iplaytv.

תודה מראש וחג שמח : )

**Comment by Fishenzon** [comment]
חג שמח
הרשימה שלי מותאמת לקודי, היא לא תעבוד כמו שצריך באפליקציות אחרות

**Comment by albilia** [comment]
אני מבין. 
תודה רבה  :  )

**Comment by rafi-d** [comment]
אין סיבה שהרשימה שהתוסף מנפיק לקודי - לא תעבוד (לאחר עריכה...)
ויש גם את הרשימה שלי - כאן: 
https://pastebin.com/raw/24LkKJK1
