### ISSUE TITLE
ספריית תכנים נעלמה

### ISSUE THREAD

**Issue by liadraz** [Fishenzon/repo#109]
שלום רב,

ספריית תכנים נעלמה מהקודי אתמול.
אני נמצא בארה"ב

רציתי לשאול אם קיימת בעיה כלשהיא? אם כתובות שונו לאחרונה?

תודה רבה,

**Comment by rafi-d** [comment]
אולי תבהיר - איזו "ספרית תכנים" בדיוק?

**Comment by ReuvenMash** [comment]
יכול להיות שקודי התעדכן לך לגרסה 19?

**Comment by rafi-d** [comment]
אם נמשיך לנחש יכול גם להיות שכל 
VOD ה
של 11 ו 13 שחסום לנגישות מחו"ל - זו הסיבה

**Comment by liadraz** [comment]
היי,
תודה רבה שחזרתם אליי.

מתנצל הייתי צריך לתת יותר פרטים מלכתחילה-
אני מריץ KODI גירסא 18.9 על מערכת הפעלה LibreELEC גירסא 9.2.6 על רספברי פיי.

אני כרגע נמצא בארה"ב. התקנתי על הקודי רק את הריפו של פישנזון. לא נעשו עדכוני גירסא גדולים על המערכת הפעלה ועל הקודי (הגירסאות הנוכחיות כתובות למעלה).

לפני שלושה ימים, התוכן מספריית ה VOD של שלושת הערוצים כאן, 12 ו-13 נעלמו. *עד לפני כן התוכן היה זמין ורץ בלי שום בעיה.
התוכן שנמצא תחת: **ADD ONS --> עידן + --> VOD** --> כאן \ מאקו \ רשת --> כל התוכניות --> וכו...

אנחנו עדיין מצליחים לראות ערוצים בטלוויזיה חייה דרך העידן פלוס מפישנזון.

רציתי לשאול אם נעשה איזה שהוא שינוי בריפו \ קישורים או אולי הבעיה בכלל היא חסימה של ספק האינטרנט המקומי? 
בהתחשב שוב שהכל עבד עד לפני כמה ימים.

תודה רבה,
וחג שמח :)

**Comment by Fishenzon** [comment]
חג שמח
מבחינת ההרחבה לא שונו כתובות, בטח לא של כל המקורות בבת אחת.

**Comment by rafi-d** [comment]
> 
> 
> אם נמשיך לנחש יכול גם להיות שכל
> VOD ה
> של 11 ו 13 שפשוט חסום באתרים לנגישות מחו"ל - זו הסיבה

**Comment by nexphere** [comment]
זה קורה גם בארץ

רק ערוץ 12 עולה

השאר לא עובד

האם יכול להיות קשור
ל iptv client
or to the youtube add on ??
