### ISSUE TITLE
[BUG] Failed to parse zip file - Version 1.5.0

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#11]
ERROR: Failed to parse '...….. plugin.video.idanplus-1.5.0.zip/plugin.video.idanplus/addon.xml'

Current installed version is 1.4.9

Kodi 17.6, Win 10 (64bit)

**Comment by Fishenzon** [comment]
Hi, Try again.

**Comment by burekas7** [comment]
Working :)
Thanks for your great job!
