### ISSUE TITLE
כאן חינוכית גיבוי

### ISSUE THREAD

**Issue by israelchoen** [Fishenzon/repo#113]
שלום,
אם אפשר להוסיף בעידכון הבא את כאן חינוכית (גיבוי) עם הלינק הזה
https://kanlivep2event-i.akamaihd.net/hls/live/747600/747600/master.m3u8
בגלל שהדיילימושן חסום אצלי
#97 

כמו כן ערוץ הקניות לא עובד, וזה הלינק המעודכן
https://shoppingil-rewriter.vidnt.com/CHANNEL21-OTT/CHANNEL21-OTT-P1_live.m3u8

תודה

**Comment by Fishenzon** [comment]
בוקר טוב
מוזמן לבדוק את גירסה 2.9.6

**Comment by israelchoen** [comment]
תודה רבה
