### ISSUE TITLE
ערוץ 20 (ערוץ המורשת ) לא עובד בבקשה תתקנו 

### ISSUE THREAD

**Issue by latinosgold** [Fishenzon/repo#115]
היי כבר יומיים שערוץ 20 בעידן פלוס לא עובד בבקשה תתקנו תודה ויום טוב

**Comment by Fishenzon** [comment]
צהרים טובים
המקור לא תקין באתר, רק חלק מאיכויות השידור זמינות.
אתה יכול להיכנס להרחבה, ללחוץ לחיצה ארוכה או קליק ימני על הערוץ, בתפריט תלחץ על בחירת איכות ניגון
תבחר באיכות 404 שעובדת גם באתר וגם בהרחבה בהתאם

**Comment by latinosgold** [comment]
תודה רבה עובד מצויין אמא שלי כל כך מרוצה סופר מעריך את זה למדתי משהו חדש

**Comment by Fishenzon** [comment]
בכיף

**Comment by latinosgold** [comment]
היי יש כרגע בעיה בהרחבה של עידן פלוס בפתאומיות אין vod של ערוץ 13 ואין vod של ערוץ 14 שבעבר היה ערוץ 20 האם תוכל לבדוק את זה ולהוציא עידכון חדש זה בשביל אמא שלי לא ניתן לראות חדשות של ערוץ 13 רק הvod של ערוץ 12 עובד מעדכן אותך ומעריך מאוד את עזרתך בנושא :)  

נשלח מה-iPhone שלי

**Comment by rafi-d** [comment]
נראה לי שתוקן כעת בגרסה  3.1.2 ועובד. תגיד לאמא שלך לעדכן גרסה....

**Comment by latinosgold** [comment]
תודה רבה אח יקר מאוד מעריך את זה הכל עובד מצויין אמא שלי מברכת אותך אין עליך שתבורך :) 

נשלח מה-iPhone שלי
