### ISSUE TITLE
היי יש לי שאלה לגבי הvod  של ערוץ 13 בעידן פלוס 

### ISSUE THREAD

**Issue by latinosgold** [Fishenzon/repo#116]
היי יש לי שאלה לגבי הvod של ערוץ 13 כבר שבוע וקצת שאין תוכן בחדשות 13 בהרחבה של עידן פלוס הוא רושם שאין תוכניות מלאות האם זה תקלה בהרחבה ומה ניתן לעשות שזה כן יעבוד  בשביל שיחזור התוכניות המלאות תודה מעריך את זה

**Comment by Fishenzon** [comment]
צהרים טובים.
נסה את גירסה 3.0.0

**Comment by latinosgold** [comment]
תודה רבה זה הסתדר מעריך את זה 

נשלח מה-iPhone שלי

**Comment by Fishenzon** [comment]
בכיף

**Comment by latinosgold** [comment]
היי אחי יש בעיה בvod של ערוץ 13 בהרחבה שלך כלום לא עובד אשמח שתבדוק ותעדכן זה חשוב מאוד לאמא שלי בעיקר החדשות מעריך אותך מאוד ושוב תודה רבה על הכל ! המשך יום מצויין 

נשלח מה-iPhone שלי

**Comment by rafi-d** [comment]
אם מותר להמליץ על ה"מתחרים": תנסו את IsraTV ...

**Comment by latinosgold** [comment]
בדקתי גם באפליקציה isratv גרסא 3.54 שהיא האחרונה יש error תוכל לבדוק זאת ולהעדכן אותי שוב מעריך אותך מאוד 👍😎

נשלח מה-iPhone שלי

**Comment by rafi-d** [comment]
לא כאן המקום לזה. תוכל לפתוח שאלב [בפורום ](https://www.tapuz.co.il/forums/%d7%a8%d7%a9%d7%aa%d7%95%d7%aa-%d7%a4%d7%a1-%d7%a8%d7%97%d7%91-%d7%95-ip-tv.629/)שלי...

**Comment by latinosgold** [comment]
תודה אחי אני אבדוק זאת אבל אתה חושב שבהרחבה שבפודל תוכל לסדר את זה שיעבוד גם שם מעריך אותך מאוד 
תעדכן אותי שוב תודה רבה :) 

נשלח מה-iPhone שלי
