### ISSUE TITLE
VOD של 013  לא עובדים

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#117]
תוכל בבקשה לבדוק מה הסיבה ? 
לאחר השהיה פשוט "מתייאש"
באתר אין בעיה

זה הלינק של משחקי השף - פרק 40 למשל.
https://cfvod.kaltura.com/scf/enc/hls/p/2748741/sp/274874100/serveFlavor/entryId/1_8a04qz8w/v/1/ev/6/flavorId/1_jy33kyaq/name/a.mp4/seg-23-v1-a1.ts?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZnZvZC5rYWx0dXJhLmNvbS9zY2YvZW5jL2hscy9wLzI3NDg3NDEvc3AvMjc0ODc0MTAwL3NlcnZlRmxhdm9yL2VudHJ5SWQvMV84YTA0cXo4dy92LzEvZXYvNi9mbGF2b3JJZC8xX2p5MzNreWFxL25hbWUvYS5tcDQvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYyOTM4OTI0Nn19fV19&Signature=gfEAzoX3uN70NXwEE1Syb9~wnOq4daktvhWCl6eOG6trWWd46uDPGgeixE-dXsHW371Y3XppDmlnDNHvXlsPmSBWdAPocq8YmKolR9QhU4h9cx8ffTlt0ZZj2EO2G3jo1GqTCDVaoYVP8Yx~0giABr7bKqFFqxTwdftkwHJrrq3rKvhBSV~Hpz0WDKwsLmMwH4MptqUCR3QuTTfAAkKZ1Y2UmwaF3nAsS~PrrTuVICVcF9xnFB6U0tiuBeyweTkn6tnTFu-h8~-qLMmzae5JQr~WYtAy1nNXtu-5Sh3~3C3bAlaslN5tgFF4G8jVgeDusb296MduCznW-b2Rb0HAIA__&Key-Pair-Id=APKAJT6QIWSKVYK3V34A

**Comment by rafi-d** [comment]
רואים את הבעיה גם אצלך? או זה רק משהו אצלי?

**Comment by Fishenzon** [comment]
ערב טוב.
מה זה לאחר השהיה?
אצלי זה מנגן את הפרק

**Comment by rafi-d** [comment]
סליחה, לא השלמתי מספיק פרטים:
בחלונות - [קודי 18.9] אכן, מתחיל לנגן את הפרק ויחסית די מהר
באנדרואיד - [גירסה 19.1] אחרי המתנה של כ30 שניות - מציג את ההסימן 
PLAY
 ואחרי עוד כ10 שניות מתחיל לנגן.

*באנדרואיד [גירסה 18.9*] שהיא הגירסה הפעילה אצלי - גם כאן אחרי המתנה של כ30 שניות מציג את הסימן 
PLAY
 אך אחרי עוד כ10 שניות - פשוט הכל נעלם ומספיק. לא מנגן כלל.

:(

אז בשורה התחתונה - הבעיה היא באנדרואיד תחת גירסה 18.9
אולי נדרש להאריך את קבועי הזמן להמתנה?

אם המיידע לא מספיק, אוכל להתאמץ עוד קצת ולראות מה קורה ב
LOG 
שם

תודה

**Comment by Fishenzon** [comment]
נראה שזאת בעיה כללית בקודי 18 על חלק מגירסאות אנדרואיד

**Comment by rafi-d** [comment]
סוגר לבינתיים.  נחליף נתב ואם לא, נתקדם ל19
