### ISSUE TITLE
תוספת ל כאן  11 VOD מתכני ה YOUTUBE 

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#118]
ניסיתי למצוא את הדוקו האחרון על קרוון מהשבוע ולא מצאתי. 
מסתבר שהם מפרסמים אותו ב YOUTUBE כאן_דוקו#
https://www.youtube.com/hashtag/%D7%9B%D7%90%D7%9F_%D7%93%D7%95%D7%A7%D7%95
ובכלל יש קטגוריות שמתפרסמות רק ב בערוצי הYOUTUBE כאן:
https://www.youtube.com/c/%D7%9B%D7%90%D7%9F%D7%90%D7%A8%D7%9B%D7%99%D7%95%D7%9F%D7%94%D7%A9%D7%99%D7%93%D7%95%D7%A8%D7%94%D7%A6%D7%99%D7%91%D7%95%D7%A8%D7%99/channels
כמו - "כאן כלכלי" 
( או גם כאן - https://www.youtube.com/c/KAN11/channels )

יש מצב להכניס את הערוצים שלהם ביוטיוב גם לתוסף?

**Comment by rafi-d** [comment]
מצויין, גם הכנסת הלינקים הישירים לערוצי יוטיוב - תעזור לנווט בקלות

**Comment by Fishenzon** [comment]
בסוף ירדתי מזה. 
ההרחבה מתסמכת על מה שמופיע באתר.
