### ISSUE TITLE
שאלה| script של mako 

### ISSUE THREAD

**Issue by hrb9** [Fishenzon/repo#122]
שלום לכל המפתחים, 
קודם כל כל תודה רבה ! 
דבר שני רציתי לברר האם תוכלו להדריך אותי, בקצרה, איך ליצור באמצעות סקריפט דומה ל   סקריפט פייטון שאתם עשיתם, לינק ל
keshet 12 in FHD 
אני רוצה להכניס לינק זה לרשימת 
m3u 
שברשותי ב-
plex 
(באמצעות xteve) 
אודה לעזרתכם !!! 
תודה רבה !!!!

**Comment by Fishenzon** [comment]
שבוע טוב.
אתה יכול להסתכל בסקריפט בהרחבה וללמוד ממנו.
