### ISSUE TITLE
ICONs בEPG ל רשת - לא מזוהים ברובם

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#124]
רואים Xים אדומים  בEPG של רשת . בערוצי 11 ו 12 - הם בסדר.

**Comment by Fishenzon** [comment]
אני לא רואה שום בעיה במדריך ואני לא מבין איזה icon יש במדריך שידורים שהוא טקסט.

**Comment by rafi-d** [comment]
צודק, טעות שלי, התבלבלתי עם תוכנה אחרת... אבך אם כבר התבלבלתי, הנה צילום מסך. אולי זה יתן לך רעיונות גם לתוסף... :)

![Screenshot_20220309-074948](https://user-images.githubusercontent.com/2458280/157381061-68200cda-1c8c-4d5f-9792-6388d364d9cb.png)

![Screenshot_20220309-075011](https://user-images.githubusercontent.com/2458280/157381100-426add8b-7679-4aeb-883c-9869bed5c5a6.png)
