### ISSUE TITLE
VOD של ערוץ 13 לא מוצג

### ISSUE THREAD

**Issue by noamel** [Fishenzon/repo#127]
ביומיים האחרונים תכני VOD של ערוץ 13 לא מוצגים.
זה נראה כמו שינויים באתר (אפשר לראות גם שינויים מסיביים באתר גם מבחינת התצוגה).

**Comment by Fishenzon** [comment]
נסה את גירסה 3.1.6

**Comment by tzagim** [comment]
עובד אצלי, תודה

**Comment by noamel** [comment]
עובד גם אצלי, תודה!
