### ISSUE TITLE
VOD של תכנים חדשים בקשת (12) נתקלים בשגיאה

### ISSUE THREAD

**Issue by tzagim** [Fishenzon/repo#128]
לא ניתן לנגן תכנים חדשים בקשת 12 כאלו שהועלו החל מ-28 לחודש

**Comment by noamel** [comment]
קרה גם אצלי, אבל עכשיו נראה שכל התכנים עובדים (ככל הנראה לאחר עדכון לגרסה 3.1.6).

**Comment by Fishenzon** [comment]
תבדוק אם זה הסתדר בגירסה 3.1.7

**Comment by tzagim** [comment]
חזר לפעול, תודה
