### ISSUE TITLE
שידורים ישירים: בעיית קפיצות, סנכרון ושמע

### ISSUE THREAD

**Issue by Kodilib** [Fishenzon/repo#13]
שלום לך,

קודם כל אני חייב להודות לך על ההרחבה הנהדרת והיוצאת מן הכלל, והתחזוקה השוטפת בה! יישר כוח!

אני רוצה לשתף בבעיה שנתקלתי בה לאחרונה:
אני משתמש במערכת ההפעלה ליברה-אלק שמותקנת על גבי סטרימר ואני נתקל בבעיות שונות בשידור החי של 'קשת' כמו קפיצות בשידור ובעיית סנכרון שמע. יש לציין שבעיה זו מופיעה בשידור החי של קשת בלבד ואינה הופיעה בעבר.
הערה: ההרחבה נבדקה במערכת אנדרואיד באותו הסטרימר ובווינדוס במחשב והכל עובד כשורה.

כולי תקווה שתוכל לטפל בבעיה.

אשמח לשתף ולתת פרטים נוספים באם יש צורך.

תודה רבה!

**Comment by Fishenzon** [comment]
@Kodilib 
תודה.
הלינקים נלקחים מהאתר, אין לי הרבה משחק עם זה.
אתה יכול לנסות לבחור לנגן באיכות 720 למשל,ולבדוק אם זה מנגן לך טוב יותר.
תבדוק גם שהאינטרנט שלך יציב

**Comment by Kodilib** [comment]
תודה רבה על התשובה!
ניסיתי לבצע את מה שכתבת, אך הבעיה עדיין קיימת- אולי הדבר קשור בסופו של דבר ספציפית למערכת ההפעלה. בכל אופן, אני כולי תקווה שהבעיה תפתר בעדכון גרסה הבא.

למרות הכל, אני חושב שזו הרחבה נפלאה, שמתוחזקת באופן שוטף ולאורך זמן. תודה לך על ההשקעה!
