### ISSUE TITLE
ושוב רשת 13

### ISSUE THREAD

**Issue by tzagim** [Fishenzon/repo#130]
הם החזירו איכשהו את ה-VOD בכתובת https://13tv.co.il/vod ויש שם גם פרקים אחרונים, יש משהו לעשות עם זה?

**Comment by Fishenzon** [comment]
יכול להיות שההרחבה לא מעודכנת אצלך.
ה-VOD קיים בהרחבה גם אחרי השינויים (לרעה) שעשו באתר.
הפרקים האחרונים לא רלוונטים כי יש שם רק 4 פרקים ברשימה

**Comment by tzagim** [comment]
> יכול להיות שההרחבה לא מעודכנת אצלך. ה-VOD קיים בהרחבה גם אחרי השינויים (לרעה) שעשו באתר. הפרקים האחרונים לא רלוונטים כי יש שם רק 4 פרקים ברשימה

אכן הם עשו שינוי לרעה, אבל ברשימה העכשוויות לא מופיעות כל התוכניות, לדוגמה "שף מתחלף" לא מופיע כלל, ואבודים מופיע בצורה חלקית, זה דברים שאני זוכר בשלוף

**Comment by Fishenzon** [comment]
בוקר טוב.
נסה את גירסה 3.2.1

**Comment by tzagim** [comment]
עובד מעולה, תודה
