### ISSUE TITLE
Lost compatibility with kodi v18.9

### ISSUE THREAD

**Issue by menachg** [Fishenzon/repo#131]
Used to work with kodi 18.9 but yesterday's update broke compatibility due to dependency to urllib3

**Comment by rafi-d** [comment]
:(

**Comment by Fishenzon** [comment]
צהרים טובים.
התקנתי הרגע על קודי 18.9 בלי שום בעיה.

**Comment by menachg** [comment]
צודק, ניסיתי עם התקנה נקיה ועבד.
