### ISSUE TITLE
Kan - no playable items

### ISSUE THREAD

**Issue by ShlomiD83** [Fishenzon/repo#132]
Kan 11 updated their site and there are no playble items in Idan Plus.

Can you please fix it? :)

**Comment by yarongon** [comment]
Also, the live stream sof Kan 11 and Kan Reshet Bet do not work :(
The log shows HTTP 403.
The backup channel of Kan 11 does work. So it seems something was changed but I don't know what.

**Comment by Fishenzon** [comment]
היתה בעיה כמה ימים.
כבר יותר מחודש שאין את הבעיה הזאת.
