### ISSUE TITLE
 קשת - הצעה ללינק/ערוץ חדש ב FHD (1080P)

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#133]
מצאתי את האתר הזה, ונראה שיש בו לינק טוב מאוד לקשת (1080P, ללא כתוביות):
https://random-stuffs.netlify.app/tv
תוכל להוסיף אותו למבחר הערוצים?

**Comment by Fishenzon** [comment]
תודה.
הלינק נלקח מאותו המקום, גם בהרחבה הוא משדר 1080P

**Comment by tzagim** [comment]
> אכן, טעות שלי. הכוונה הייתה ל1080P ברשת - 13 אבל לא נראה לי ששם המקום למצוא את זה... אולי יש מקור אחר ל1080P ב 13?

ככל ואני מבין, ההרחבה משתמשת בקישורים רשמיים ולא פיראטיים, רשת 13 לא מאפשרת צפייה חוקית באיכות 1080p, ולכן התשובה לשאלתך היא לא.

**Comment by Fishenzon** [comment]
בוקר טוב.
כמו שנכתב בהודעה מעלי, אני לא אוסיף להרחבה לינקים מאתרים פיראטיים.
הלינקים בהרחבה מגיעים מהאתרים הרשמיים של הערוצים.
