### ISSUE TITLE
ערוץ נוסף לספרט? 

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#135]
מה דעתך על הוספת ערוץ (ערוצים) נוספים לספורט?
דוגמא לערוץ 5ספורט  - https://poscitech.click/en/ch144.php 

האיכות בכלל לא רעה, נדמה לי 1080P...

**Comment by Fishenzon** [comment]
אם ערוץ הספורט ישדר באתר הרשמי שלו, אכניס את זה להרחבה.

**Comment by daniandco1** [comment]
הבעיה העיקרית עם השידורים האלה זה שהלינקים מתחלפים. הייתי שמח לבנות משהו, אם יש לינקים שלא משתנים הרבה @rafi-d

**Comment by rafi-d** [comment]
> הבעיה העיקרית עם השידורים האלה זה שהלינקים מתחלפים. הייתי שמח לבנות משהו, אם יש לינקים שלא משתנים הרבה @rafi-d

כללית נכון, אבל אם אתה בונה אפליקציה (?) חכם/נכון, תוכל לערוך אותה כך שניתן יהיה בקלות לעדכן לינקים.

לדעתי, הלינק שנתתי כאן, יציב כבר חודשים, ושני אתרים אחרים (לפחות) משתמשים בו. תמיד אפשר גם להשתמש בלינקים שלהם שם יש רידירקט אליו (כעת... קיימים בדומה גם למבחר ערוצים אחרים, אוכל לשלוח  בפרטי אם תחליט לנסות).

אישית אני מעדיף באנדרואיד אפליקציה  ולא את קודי, או גם וגם ...
