### ISSUE TITLE
שני ערוצי 12 (קשת) לא פועלים

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#137]
אולי שינוי באתר את שיטת הצפיה? ...  אפשר לנסות להשמיש?

אגב, גם ערוץ כאן11 בגיבוי של דיילימושן לא פועל

תודה!

**Comment by Fishenzon** [comment]
תודה רבה.
תבדוק את גירסה 3.2.9

**Comment by Fishenzon** [comment]
כאן 11 הורידו את DM כשהתחיל המונדיאל. אולי יחזירו אותו בהמשך?

**Comment by rafi-d** [comment]
תקין כעת, תודה!

מה הם עוללו הפעם?  כי הערןץ הפסיק לפעול גם באפליקציה IsraTV הוותיקה...

**Comment by rafi-d** [comment]
12 חזר לעצמו גם בIsraTV

כנראה יש מי שדואג...
