### ISSUE TITLE
vod keshet12

### ISSUE THREAD

**Issue by omerzs** [Fishenzon/repo#139]
אין תוכן בוייאודיי של החדשות בקשת12 ניסיתי לעדכן ל3.2.9 

עדיין לא עובד

**Comment by rafi-d** [comment]
לא רואה בעיה, לפחות לא ב"משחקי השף"

**Comment by Fishenzon** [comment]
שינו משהו באתר, אתה יכול לבדוק את גירסה 3.3.0
@omerzs

**Comment by omerzs** [comment]
3.3.0 עובד תודה אחי!!
