### ISSUE TITLE
SetArt & Remove reshet sort button from listing

### ISSUE THREAD

**Issue by cartmandos** [Fishenzon/repo#14]
(a) Was wondering if u're willing to incorporate some minor changes to set art (namely, fanart/thumb) for the channels, so that when using the addon's listing via skin widgets (for ex.) it will get that artwork to show in home screen, etc or other viewtypes.
[IN METHOD addDir, common.py]
`listitem.setArt({'thumb': iconimage, 'fanart': iconimage})`

(b) Reshet's listing inc. the ''sort by'' item. But this is also featured in the addon's setting. Again, when getting listing to show on widgets it's kinda annoying to see... 
(mako on the other hand, has it on main dir but reshet vod IS the main dir, thus the difference).
[del THIS LINE, reshet py]
`common.addDir(name, "toggleSortingMethod", 5, iconimage, 
{"Title": name, "Plot": "{0}[CR]{1}[CR]{2} / {3}".format(name,common.GetLocaleString(30004),common.GetLocaleString(30002),											common.GetLocaleString(30003))}, module=module, isFolder=False)`

(c) The addon has A LOT of label formatting ([COLOR], [B], etc...)
IMHO, this should be taken care of at the skin level not the addon.
Most importantly, [B] or simillar labels that are often used in skins and can get double label formatting (addon & skin xml), which in turn will be viewed to user as "sometext[/b]".

Just my thoughts, and things i've changed personally. If u see fit, i hope u'll integrate some of it in the next updates to come.

AND, THANKS FOR THE HARD WORK. THIS ADDON IS A LIFE($$$) SAVER ;]

**Comment by Fishenzon** [comment]
@cartmandos 
Thanks.
Please check ver 1.6.7

**Comment by cartmandos** [comment]
Perfect. Only noticed [TIMES] on channel listing lacks spacing.

**Comment by Fishenzon** [comment]
@cartmandos 
Hi.
Please check ver 1.6.8

**Comment by cartmandos** [comment]
hi, sorry for the late response. So far it's great 👍
