### ISSUE TITLE
VOD קשת - עוד בעיה... 

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#140]
יש בעיה נוספת כעת, שנעלמות קטגוריות (TABS) שלמות.  למשל - 

תחת הזמר המסכה :
https://www.mako.co.il/tv-the_masked_singer?partner=BreadCrumbs

היתה מקודם עוד מחיצה: "פרקים  מלאים " 
https://www.mako.co.il/mako-vod-keshet/the_singer_in_a_mask-s3?partner=SecondNav

כעת, המחיצה נעלמה, ופשוט אי אפשר לראות פרקים קודמים... 

לא בדקתי אם זה רק כאן, או גם בתוכניות אחרות.

תודה!

-רפי

**Comment by rafi-d** [comment]
![image](https://user-images.githubusercontent.com/2458280/212255802-80d194b9-fc1f-4840-b868-51682844f465.png)

נראה ששתי הTABs שם - "פרקי"ם ו"מיוחדים" מעורבבות כעת...

**Comment by Fishenzon** [comment]
עשהו שינוי באתר, צריך לבדוק אם צריך שינוי מקיף או רק התאמות.

**Comment by Fishenzon** [comment]
הוספתי הפרדה בגירסה 3.3.1
עדכנתי את ההרחבה לשינויים באתר, היו מקומות שנוספו עוד פרקים, למשל בחדשות המהדורה המרכזית.
מצד שני עכשיו חוץ משם התכנית, לא מופיע תיאור מפורט יותר. זה קיים רק בדף הספציפי של אותו פרק ולא ברשימת הפרקים.

**Comment by rafi-d** [comment]
תודה, אעדכן בערב...
