### ISSUE TITLE
כיצד ניתן להוריד את איכות השידור כדי למנוע באפרינג?

### ISSUE THREAD

**Issue by aviranco** [Fishenzon/repo#141]
יש מדי פעם Buffering, ככל הנראה בעקבות מהירות האינטרנט עבור האיכות הגבוהה ביותר. ראיתי שניתן בהגדרות לתת ערך של איכות השידור עבור כל ערוץ, אך מה הערכים התקינים האפשריים? צריך לעשות משהו על מנת שהשינויים יכנסו לתוקף? מה הערך של איכות השידור הכי נמוכה? ניסיתי לשים 280 ו-280p אך לא הייתה השפעה על האיכות.

תודה

**Comment by rafi-d** [comment]
לחיצה ארוכה על הערוץ -> מוצג תפריט -> ואז בחר  "קביעת איכות שידור"  . תוכל לכוון את האיכות (רזולוציה) של הניגון לפי הרשימה שמוצגת בזמן אמת. זה גם עובד... :)

**Comment by Fishenzon** [comment]
כמו שרפי כתב, אפשר לקבוע את האיכות וזה נשמר בהגדרות. (אתה יכול גם לכתוב ידנית בהגדרות מספר גדול או שווה לאיכות שאתה בוחר. כל המספר קטן מהמספר של האיכות הבאה, תיבחר האיכות הזאת גם לפעמים הבאות).
אצלי כן רואים בהגדרות את האיכות שנבחרה

**Comment by rafi-d** [comment]
אצלי לא. בודק בקודי 19.5 , חלונות, כאן 11 הערוץ הראשון מתוך ה4 שיש (בהגדרות יש רק אחד) ...  אולי יש בלבלול איזה ערוץ קשור לאיזו הגדרה...

**Comment by Fishenzon** [comment]
כנראה שאתה לא בודק בלשונית הנכונה.
בלשונית של כאן אפשר לקבוע את האיכות המירבית של ה-VOD.
האיכויות של הערוצים נמצאים בלשונית טלויזיה מתחת לקביעת מיקום הערוצים.

**Comment by rafi-d** [comment]
צודק.. איך אפשר לדעת שיש למטה משהו... :)    אולי סידור משולב של מיקום + איכות לכל ערוץ היה בהיר יותר... 
אגב, הUI ממש לא ברור גם בעת קביעת האיכות - לאחר שבחרת מרשימה,  מוצג דיאלוג עם בחירה נוספץ "AUTO" . ממש לא ברור, ומיותר, אם כבר אז צ"ל "DONE" עם המספר הנבחר, או בכלל להכניס את כל הרשימה אליו...
