### ISSUE TITLE
ערוץ הידברות לא עובד

### ISSUE THREAD

**Issue by yannn12** [Fishenzon/repo#143]
היי, ערוץ הידברות לא עובד
נראה שהקישור בקוד לא עובד יותר https://go.shidur.net/player/testlive.php
יש מצב להחזיר את זה ל קישור של האתר? https://www.hidabroot.org/live

זה הערוץ הכי שימושי בהרחבה :)

תודה רבה

**Comment by Fishenzon** [comment]
תודה.
סידרתי בגירסה 3.3.3
