### ISSUE TITLE
תקלה ב-vod

### ISSUE THREAD

**Issue by dstu69** [Fishenzon/repo#145]
שלום,
תכני ה-VOD נתקעים בדיוק אחרי 2 דקות. גם אם מחדשים צפיה מאמצע פרק, זה נתקע שוב אחרי 2 דקות.
זה לא מוגבל לערוץ ספציפי וכנראה שזה התחיל עם העדכון האחרון.
תודה

**Comment by dstu69** [comment]
לאחר בדיקה נוספת, זה קורה גם בשידור חי

**Comment by rafi-d** [comment]
איזה מערכת הפעלה/גרסה? צופה באנדרואיד, גרסה 19.5, תוסף 3.3.3
ולא רואה תופעה כזאת.

**Comment by dstu69** [comment]
קודי 20.0.0 על Android TV, תוסף 3.3.3
בדקתי תכנים שלא מעידן פלוס והם עובדים בסדר

**Comment by rafi-d** [comment]
אם אתה אומר שזה קשור לגרסה האחרונה (וכנראה רק לקודי 20) - מציע שתבטל עדכון אוטומטי לתוסף, ותנסה גרסה קודמת שיש כאן:

https://github.com/Fishenzon/repo/tree/master/zips/plugin.video.idanplus

**Comment by Fishenzon** [comment]
צפיתי בקודי 20 על אנדרואיד טיוי בשני מכשירים ולא נתקלתי בתקלה הזאת

**Comment by dstu69** [comment]
זה קורה אצלי בתכנים של כאן 11 בחיבור VPN (כי הם חסומים מחו"ל). אולי זה קשור. אגב, ביישומון של כאן BOX, זה עובד בצורה תקינה, למרות ה-VPN
