### ISSUE TITLE
keshet VOD

### ISSUE THREAD

**Issue by GitHubIL** [Fishenzon/repo#146]
שלום,
לאחרונה הVOD של keshet לא עובד.
הבעיה קיימת רק בקודי 18.9.
בקודי 19 עובד רגיל.
ייתכן שזה קשור לpython 3.

תודה רבה

**Comment by omerzs** [comment]
Thanks @GitHubIL  I can confirm had same issue upgrading kodi resolved the issue.

**Comment by Fishenzon** [comment]
תוקן בגירסה 3.3.4

**Comment by GitHubIL** [comment]
תודה
