### ISSUE TITLE
סידור של תכניות VOD

### ISSUE THREAD

**Issue by rick-ronen** [Fishenzon/repo#147]
אחרי העדכונים האחרונים, סדר הפרקים המוצג ב VOD הוא מהראשון לאחרון, כך יוצא לדוגמא ארץ נהדרת צריך לגלול עד סוף המסך (או חץ אחד מעלה) על מנת להגיע לעונה האחרונה (ספריה) ומשם לגלול שוב לפרק האחרון ששודר. 
לפי דעתי זה צריך להיות הפוך בסדרות שמשודרות בימים אלו.

**Comment by rafi-d** [comment]
מצטרף לבקשה. למעשה זה באג, כי יש אפשרות בחירה בתפריט משמאל - ascending - descending :DATE שלא עובד...

**Comment by Fishenzon** [comment]
אסדר בגירסה הבאה את סדר העונות בסדר יורד.
מבחינת הפרקים, יש עונות שמסודרות בסדר יורד ויש כאלה שמסודרות בסר עולה, אפשר לראות את זה בארץ נהדרת לדוגמה.
אין לי הרבה מה לעשות, האתר לא מספק את הנתון הזה. לפעמים זה מופיע בתוך חלק משם התכנית או התאור, אבל זה לא מגיע בתור נתון ברור של תאריך.
בעבר זה כן היה קיים אבל שינו את הדרך שהאתר מביא את התכנים אליו.

**Comment by rafi-d** [comment]
אם כך, זו  עוד סיבה טובה לתת יכולת שליטה ידנית על הסדר מהתפריט השמאלי בקודי ...
