### ISSUE TITLE
אין תוכן במספר תוכניות ב VOD

### ISSUE THREAD

**Issue by pashosh** [Fishenzon/repo#148]
למשל כשמגיעים לתפריט של ארץ נהדרת ונכנסים פנימה, אין שם תוכן. ריק.
אותו הדבר קורה גם בתוכנית המטה המרכזי (ערוץ 13).
בדקתי את זה על המחשב (לינוקס) וגם בסטרימר אנדרואיד כלשהו.
התופעה קיימת בשני המקומות.
יכול להיות שזה קורה בעוד תוכניות אבל כמובן שאין לי מושג כי לא עברתי על כולן.
כמו כן, אני יודע שזה לא קורה בכל התוכניות כי למשל יש תוכן בתפריט של התוכנית פגוש את העיתונות.

**Comment by rafi-d** [comment]
לא רואה בעיה כזו בארץ נהדרת (אנדרואיד), תוודא שאתה בגרסה 3.3.4...

**Comment by rafi-d** [comment]
עם איזו גירסה של קודי?

**Comment by Fishenzon** [comment]
נא לוודא גירסת רפו 1.0.2 וגירסת הרחבה 3.3.4

**Comment by pashosh** [comment]
אוקיי אחרי קריאת התגובות אני יכול לאשר שאכן גם אצלי יש ארץ נהדרת והמטה המרכזי.
בכל אופן לדעתי יש בעיה ואני חושב שתוכלו לשחזר אותה אצלכם (כך אני פעלתי עד עכשיו ולכן חשבתי שאין את התוכניות).
הבעיה היא בחיפוש של התוכנית ואז בהוספה למועדפים של עידן +.
אם תחפשו _ארץ_ אתם תגיעו בין השאר לתוצאה של _ארץ נהדרת_ ואם תכנסו פנימה אתם תראו  (כך זה אצלי) שאין כלום בפנים.
אבל, אם אני הולך לVOD ואז לקשת 12 ושם לקומדיה ואז לארץ נהדרת, אכן רואים את כל העונות ואפשר לבחור תוכניות מכל עונה.
כלומר כשמגיעים ידנית לתוכנית הרצויה הכל עובד היטב, אבל כשאני מחפש, משהו שם משובש (לפחות אצלי).
מה שעשיתי כניראה לפני כן זה פשוט לחפש את התוכנית וכשמצאתי, הוספתי אותה למועדפים ומאז אני ניגש לתוכנית דרך המועדפים וכמובן לא רואה שום דבר בפנים.
עד לפני שלושה שבועות (בערך) המועדפים הללו היו בסדר, כלומר היה תוכן בפנים ואז משהו קרה ונעלם מהם התוכן.
כמו כן, אם אני מגיע לארץ נהדרת ידנית (וגם למטה המרכזי) ושם מוסיף אותה למועדפים של עידן +, זה עובד טוב, כלומר יש תוכן בפנים כשאני נכנס לתפריט הזה בתוך המועדפים.
ראוי גם לציין שאם אכן תחפשו _ארץ_ בין השאר תהיה גם תוצאה של _והארץ הייתה תוהו ובוהו_ ואם תכנסו אליה אז התוכן קיים.
ואפילו אפשר להוסיף אותו למועדפים והכל עובד היטב.
אז שורה תחתונה: מצאתי שתי תוכניות (ארץ נהדרת והמטה המרכזי) שאם אני מחפש אותן, כשאני נכנס לתוצאת החיפוש, אין תוכן בפנים.
אבל התוכן שלהן קיים כשמגיעים אליהם ידנית.


בסטרימר אני על קודי 19.5 ובמחשב אני על קודי 20.
בשני המקומות אני על הרפו האחרונה כלומר 1.0.2 וגרסה 3.3.4 של התוסף.

**Comment by rafi-d** [comment]
יש בעיה במועדפים ''ישנים'  כשהלינקים באתר משתנים.

https://github.com/Fishenzon/repo/issues/144

הפתרון נראה לי מסובך אבל אפשרי... (אולי שימוש בפונקציות במקום לינקים במועדפים)

**Comment by rafi-d** [comment]
נב: זה שהחיפוש לא תקין כעת זו בעיה נוספת...

**Comment by Fishenzon** [comment]
החיפוש עכשיו תקין בגירסה 3.3.5
יש עדיין בעיה עם רשת שעברו לסידור חדש באתר. חלק מהתכנים לא זמינים (עדיין?) בפורמט החדש.
