### ISSUE TITLE
vod ערוץ 13

### ISSUE THREAD

**Issue by dani111111111** [Fishenzon/repo#149]
אני מקבל רק פרומאים של תוכניות ועונות קודמות בלבד

**Comment by rafi-d** [comment]
עם איזו גרסת תוסף ?

**Comment by dani111111111** [comment]
20.4.0 repository

**Comment by dani111111111** [comment]
עידן פלוס 3.3.0

**Comment by rafi-d** [comment]
אז  קודם תעדכן, ורק אחכ תתלונן... ;)

**Comment by dani111111111** [comment]
אגב הוא לא נתן לי לעדכן רק כשהסרתי והתקנתי שוב

**Comment by dani111111111** [comment]
כל הכבוד לכם עבודה מצויינת
