### ISSUE TITLE
תרומתי הצנועה

### ISSUE THREAD

**Issue by hugo46** [Fishenzon/repo#15]
היי,
ראשית עבודה נהדרת

יש לי אפשרות לתרום מעט ידע ואשמח לשתף את כולם

1. הלינק של ערוץ החדשות הוא פיד שמשדר את הלופ היומי שלהם ולא כולל את הפריצות לשידורים חיים של המהדורה ותכניות הלווין
הלינק שכולל את הלייבים הוא:
http://ch2live-i.akamaihd.net/hls/live/252343/hls1_44_1496/chunklist.m3u8

מדוע ערוץ וואלה! ניוז לא נמצא? הוא משדר מהדורה יומית (בשעה 14:00 ושני שידורים 
 (חוזרים מיד לאחר מכן
בדומה למתכונת של ערוץ וואינט שהוא כן נמצא
יש לי לינק של שידורי sd
https://31-168-228-117.vidnt.com/walla_ulpanRepeat/_definst_/smil:ulpan.smil/chunklist_w1972474775_b828000.m3u8

עוד עובד על למצוא hd אם הם בכלל משדרים

תודה והמשיכו בעבודה הטובה!

**Comment by rafi-d** [comment]
רק HD בבקשה...
 👍

**Comment by hugo46** [comment]
חברת החדשות זה HD
על וואלה נעבוד

**Comment by hugo46** [comment]
תודה לכם
אחרי בדיקה נוספת, וואלה לא משדרים ברזולוציה גבוהה יותר מזו שצירפתי

**Comment by Fishenzon** [comment]
תודה
הערוצים נוספו בגירסה 1.7.2
