### ISSUE TITLE
תיקון לערוץ 14

### ISSUE THREAD

**Issue by EagleLand** [Fishenzon/repo#152]
מצורף קובץ עם תיקון לניגון התכנים של ערוץ 14.
ערוץ 14 החליפו ספק תוכן ועברו ל-akamai לכן מצריך תיקון התוסף.
[plugin.video.idanplus.zip](https://github.com/Fishenzon/repo/files/10714590/plugin.video.idanplus.zip)

**Comment by Fishenzon** [comment]
תודה רבה. 
הוספתי את התיקון בגירסה 3.3.5

**Comment by EagleLand** [comment]
בבקשה לעדכן גם את `resources\language\resource.language.en_gb\strings.po ` מכיוון שהשם הפוך.

**Comment by Fishenzon** [comment]
עדכנתי
