### ISSUE TITLE
ההרחבה הפסיקה לעבוד עם ה-IPTV Simple Client

### ISSUE THREAD

**Issue by GamesToEnjoy** [Fishenzon/repo#153]
אני נוהג לצפות בערוצים ממסך הבית של קודי > TV (מה שנקרא בהרחבה טלווזיה חיה).
לפני מספר ימים זה הפסיק לעבוד, ושאני לוחץ על TV לא רואים אף ערוץ.
לחצתי תחת הגדרות על הגדרת IPTV Simple Client לשימוש בקבצי עידן פלוס, וזה לא עוזר.
תחת ההגדרות שימוש בטלוויזיה חיה דולק וגם הרחבת IPTV Simple Client מותקנת.
נסיתי להתקין מחדש את ההרחבה ואף להתקין את הקודי מחדש וזה לא עזר.
מותקן אצלי קודי 20 אבל לא נראה לי שזה הבעיה כי זה עבד לי תקופה מסוימת גם על קודי 20.
אשמח מאוד לפתור את הבעיה הזאת כי הטלוויזיה החיה של קודי מאד נוחה לשימוש.
תודה מראש!

**Comment by pashosh** [comment]
גם אצלי זה קרה.
מה שפתר זאת לבסוף זה להסיר את ההגדרה של התוסף  IPTV Simple Client.
לא להסיר את התוסף, אלא את מה שהיה מוגדר שם.
כלומר תכנס אל התוסף ולך להגדרות בתוכו ושם תהיה לך אופציה באחת השורות להסיר את ההגדרה.
תסיר ואז תבדוק אם כשאתה מגיע לתפריט TV אתה רואה את הערוצים החיים.
אם לא, אז תגדיר את עידן+ שייצר לך את הערוצים:
https://imgur.com/5kDwAQt
כלומר יצירת קבצים לטלוויזיה חיה ואז הגדרה IPTV Simple Client לשימוש בקבצי עידן+.

**Comment by GamesToEnjoy** [comment]
@pashosh תודה על העזרה!
בהגדרות של IPTV Simple Client יש לי את אותם השורות כמו שלך, אבל זה עדין לא עובד.
ניסיתי ללחוץ יצירת קבצים לטלוויזיה חיה ואז הגדרה IPTV Simple Client לשימוש בקבצי עידן+, וגם לא עזר.
אם אני נכנס להגדרות של IPTV Simple Client תחת Edit migrated Add-on config, ה-location הוא Remote path. אמור להיות שם Local path עם הקובץ של עידן פלוס שנוצר לוקלי, נכון? נראה לי שההרחבה של עידן פלוס לא מעדכנת אצלי את ההגדרות של IPTV Simple Client.
תוכל לשלוח לי בבקשה מה מופיע אצלך בהגדרות של IPTV Simple Client שאני אנסה לשנות ידנית?

**Comment by pashosh** [comment]
אכן אצלי זה local path:
![asd](https://user-images.githubusercontent.com/7255228/218888172-3bb610bc-b844-414d-92f4-19824df8e368.png)

**Comment by pashosh** [comment]
הדרך אל הקובץ m3u הוא ככה (אני על לינוקס אז אולי אצלך זה יהיה אחרת):
addon_data -->  plugin.video.idanplus --> idanplus.m3u

**Comment by GamesToEnjoy** [comment]
@pashosh תודה רבה!
אני צריך למצוא תחת איזה תיקייה באנדרואיד נמצא addon_data, אבל זה בהחלט הכיוון.

**Comment by pashosh** [comment]
אולי תלחץ על Defaults ואז תנסה מחדש ליצור קבצים לטלווזיה ואז הגדרת iptv simple לשימוש בקבצים האלו, בתוך ההגדרות של עידן+.

**Comment by gigarepo** [comment]
@pashosh הצלחתי בסוף ע"י זה שטענתי ידנית את הקובץ idanplus.m3u,  תודה על העזרה :)

בכל מקרה יש בעיה עם ההרחבה של עידן פלוס שהפסיקה לעדכן את ההגדרות של IPTV Simple Client, וזה משהו שעבד היטב כמה שנים.
מקווה שזה יתוקן.

**Comment by tzagim** [comment]
הבעיה אינה בהרחבת עידן פלוס אלא בתוכנת הצפייה IPTV Simple Client, גרסה 20.8.1 שברה את הקישורים.

הדרך הקלה ביותר היא פשוט לשנמך גרסה זה פותר מיידית את הבעיה.

למיטבי לכת, ניתן לקרוא [כאן](https://forum.kodi.tv/showthread.php?tid=371966) [וכאן](https://github.com/xbmc/xbmc/issues/22779) על הבעיה ורעיונות לפתרון.

**Comment by Fishenzon** [comment]
הוספתי תיקון שיעבוד גם על קודי 20.
נא לעדכן לגירסה 3.3.6

**Comment by GamesToEnjoy** [comment]
@Fishenzon Working :)
Thanks a lot for solving it!
