### ISSUE TITLE
Please add Timeshift support in the M3U file

### ISSUE THREAD

**Issue by Barina** [Fishenzon/repo#154]
I've tried to enable timeshift using "PVR IPTV Simple Client" and "Inputstream FFmpeg Direct" but I couldn't get it to work.
Anytime I tried watching (any) stream there's only the stop button available and no fast-forward\backward or pause buttons..

After googling it a bit, I found that the M3U file need to be edited so I manually added these few lines **before each entry**:
```
#KODIPROP:inputstream=inputstream.ffmpegdirect
#KODIPROP:inputstream.ffmpegdirect.stream_mode=timeshift
#KODIPROP:inputstream.ffmpegdirect.is_realtime_stream=true
#KODIPROP:mimetype=video/mp2t
```
Source: https://github.com/kodi-pvr/pvr.iptvsimple/blob/Matrix/README.md#timeshift
And from there, timeshift works great(ish..)! until I restart Kodi... seems like the M3U file gets reset on every launch.

Is there a way to add builtin, permanent timeshift support in the M3U file?

Needless to say? I'm using a fresh Kodi (for Debian) 19 install

**Comment by rafi-d** [comment]
So, W/A it, rename the file , and configure PVR IPTV Simple Client to use it instead...

**Comment by Barina** [comment]
Thanks
Aren't those M3U files can change sometimes? If they're fixed then this workaround is more than acceptable :)

**Comment by Fishenzon** [comment]
תודה רבה.
מכיוון שעם התגיות האלו, נתקלתי בתקיעות בשידור במחשב אחד לעומת מכשיר אחר שזה עבד בו טוב, הוספתי את זה בתור אופציה.
זה כבוי בתור ברירת מחדל, אם אתה רוצה להשתמש בזה, כנס להגדרות ללשונית של טלויזיה חיה וסמן timeshift. מהחילוצים הבאים זה יוסיף את התגיות.

**Comment by rafi-d** [comment]
זה עובד רק בחלונות, או גם באנדרואיד?

**Comment by Fishenzon** [comment]
זה עובד גם באנרואיד. אבל השארתי את זה כבוי כברירת מחדל.
יש לינקים כמו קשת שמגמגמים או נתקעים לגמרי בכל מיני מכשירים, לעומת לינקים כמו רשת שעבדו אצלי בסדר.
מי שזה עובד אצלו בסדר יצטרך לסמן בהגדרות אם הוא רוצה שזה יופעל.
עדיף שלא יופעל אוטומטית ויתקע למשתמשים שלא צריכים את זה את הצפיה.

**Comment by rafi-d** [comment]
OK, תודה.    יש מצב באנדרואיד לשמור את ההקלטות שוודאי עושים בTIMESHIFT בכונן רשת ולא מקומית על הקופסה?

**Comment by Fishenzon** [comment]
אני לא יודע. 
תנסה בהגדרות של iptvsimple ובהגדרות של inputStream adaptive
