### ISSUE TITLE
צריכה הספק גבוה גם אחרי עצירה צפיה.

### ISSUE THREAD

**Issue by Ikif** [Fishenzon/repo#155]
הי .
יש לי RPI3 עם LibreELEC ויש לי קירור אקטיבי שתלוי בטמפרטורה של המעבד.
בזמן הצפיה זה מגיע עד 55C ואז בעזרת מאוורר מתקרר עד 42C.
אחרי restart הטמפרטורה לא עולה יותר מ50C (המאוורר לא מופעל) , אבל אם אני עוצר צפיה ונשאר בתוך Add-on , אז זה ממשיך לצרוך הספק גבוה ומגיע ל55C מה שגורם להפעלת מאוורר.

ניתן לתקן זאת ?

**Comment by Fishenzon** [comment]
בוק רטוב.
אין לי מה לעשות מהצד שלי.

**Comment by rafi-d** [comment]
אולי לשים מאוורר חיצוני/שקט יותר?
