### ISSUE TITLE
בעיית ניגון ב VOD

### ISSUE THREAD

**Issue by ASD2356** [Fishenzon/repo#156]
יש בעיה ב VOD, שאם רוצים לראות תוכן כלשהו, מערוצי השידור, רשת 13 או כאן 11 או עכשיו 14, אז התוכן הזה לא מתנגן, איך לדעתכם אפשר לפתור את הבעיה הזו?

**Comment by rafi-d** [comment]
איך? אולי אם תתן עוד פרטים , על איזו מערכת הפעלה והגרסה של הנגן+קודי?... כי אצלי כן עובד ...

**Comment by ASD2356** [comment]
> איך? אולי אם תתן עוד פרטים , על איזו מערכת הפעלה והגרסה של הנגן+קודי?... כי אצלי כן עובד ...

זה דרך סמארטפון של חברת שיאומי דגם Readmi 9c, מערכת הפעלה של MIUI שהיא כמו מערכת הפעלה של אנדרואיד והגרסה של המערכת הפעלה הזו היא 12.0.22, וזה דרך קודי גרסה 20.0, וקודם באותו מכשיר סמארטפון באותו סוג וגרסה של מערכת הפעלה אז לא הייתה לי את הבעיה שלי.

**Comment by rafi-d** [comment]
קשה.... וגירסת התוסף? ניחוש שלי - קודי 20 הבעייתי ..

**Comment by ASD2356** [comment]
> קשה.... וגירסת התוסף? איזה סקין? ניחוש שלי - קודי 20 הבעייתי או הסקין שבחרת . ..

מה הכוונה פה לקשה? 
גרסת ההרחבה של עידן פלוס במקרה שלי הזה היא 3.3.7
מה הכוונה פה לסקין שבחרתי?

**Comment by Fishenzon** [comment]
שבוע טוב.
בדקתי אצלי בפלאפון עם אנדרואיד 13, קודי 20 וגירסת הרחבה 3.3.7 והכל עובד.
תנסה לשלוח לוג ונראה.
דבר נוסף, אתה נמצא בחו"ל?

**Comment by ASD2356** [comment]
אני עכשיו נמצא בישראל,
איך אפשר דרך קודי בלי תוספות להגיע ולשלוח לוג?
חשוב לי להוסיף פה שמתי שיש לי את התקלה הזאת אז אני לא מקבל אף הודעה של תקלה, ובמקום זה כתוב לי למטה בצד ימין הרבה זמן את המילה עסוק ואחר כך המילה הזאת נעלמת משם, מבלי שהשידור מתנגן שם.

**Comment by ASD2356** [comment]
זה יצא טוב הלוג הזה?
https://paste.kodi.tv/tetoruwuya

**Comment by ASD2356** [comment]
נראה לי שזה הלוג הנכון
https://paste.kodi.tv/tetoruwuya

**Comment by Fishenzon** [comment]
הגירסה אצלך היא 3.3.4 לעומת הגירסה הנוכחית 3.3.7
אם לא מתעדכנת לך ההרחבה יכול להיות שיש עוד דברים שלא עובדים אצלך כמו שצריך.
תנסה לעדכן את ההרחבה ואם היא לא מתעדכנת, תנסה להתקין מחדש את הרפו.

**Comment by rafi-d** [comment]
https://github.com/Fishenzon/repo/issues/157
