### ISSUE TITLE
גרסה 3.3.8 - תכני VOD כאן 11 ריקים

### ISSUE THREAD

**Issue by TwilightMercy** [Fishenzon/repo#157]
קודי 20.1
נכנס לכאן 11 vod - כל התכניות - ריק
קורה גם לעוד אנשים שבדקתי
אם צריך לוג, אשלח אין בעיה

![image](https://user-images.githubusercontent.com/29895680/230043902-8c8a7c72-1d42-4ebb-9a6d-556497fe94cd.png)

**Comment by tzagim** [comment]
אותה בעיה אצלי, גם ב-14

**Comment by rafi-d** [comment]
גם כאן (קודי 19.5)-
 Vod כאן 11 ריק
כאן ארכיון ריק
עכשיו 14מריק

**Comment by Fishenzon** [comment]
ערב טוב.
הייתי עסוק במהלך פסח.
מסתבר שהוסיפו הגנה של cloudflare, הוספתי משהו שאמור לטפל בזה, אבל זה לא עובד טוב בקודי כמו שזה עובד בפייטון מחוץ לקודי.
מבחינת ה-VOD זה עדיין מגמגם וצריך לפעמים לנסות להיכנס כמה פעמים עד שעולה התוכן.
מבחינת תחנות טלויזיה ורדיו שמתי לינקים ישירים מהאתר.
סידרתי גם את ה-VOD של ערוץ 14.

עדיף שיעבוד לפחות חלקית לפני יום הזיכרון.
