### ISSUE TITLE
סימון כ"הושמע"/"לא-הושמע" - מוחק את כל זמני הנגינה

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#16]
Setting Mark as watched/unwatched  on a channel - erases all the displayed play-time on all channels.
When playing any unmarked channel then -the play-times are returning to the display... 

אגב, קצת מוזר שהערוץ היחיד שאינו בFHD 1080P הוא 11 
למרות שהוא היחיד שבאמת משדר באויר בHD....

**Comment by Fishenzon** [comment]
@rafi-d 
אני לא מתערב באיך קודי מסמן נצפה/לא נצפה.
לגבי איכות השידור של ערוץ 11, זה מה שיש באתר
