### ISSUE TITLE
לא ניתן להכנס לערוץ ולתחנות הרדיו של רשת כאן

### ISSUE THREAD

**Issue by SharonHala** [Fishenzon/repo#161]
נראה ששאר התחנות כמו גלגלצ וכו פועלות, הבעיה רק בתחנות של רשת כאן, באפליקציות רדיו השונות התחנות פועלות כרגיל.

עריכה: נראה שגם הערוץ עצמו של כאן 11 לא פועל דרך ההרחבה

**Comment by tzagim** [comment]
#157

**Comment by SharonHala** [comment]
> #157

צודק, טעות שלי לא ראיתי שפורסם.

**Comment by Fishenzon** [comment]
נא לעדכן לגירסה 3.4.0
