### ISSUE TITLE
ערוצים 13,21 לא עובדים לי כבר זמן מה ותוכן מכאן 11 לא מתנגן

### ISSUE THREAD

**Issue by pashosh** [Fishenzon/repo#164]
ערוץ 13 על שלוש האפשרויות שלו בתוסף, פשוט לא מתנגן. זה כבר זמן מה כך. זה קורה לי בקודי על המחשב (עובד על לינוקס) וגם באנדרואיד TV. בשני המקרים יש סימן של העיגול שמתגלגל עד אין קץ ואין הגעה לשידור עצמו. אני על קודי 20.1 ותוסף עידן + גרסה 3.4.1.

 אותו כנ"ל לערוץ 21. לא עובד כבר תקופה כלשהי.
לא שאני צופה בו באדיקות אבל לעיתים אני רוצה להיקרע קצת מצחוק והערוץ הזה מספק רגעים טובים.

תוכן מכאן 11 לא מתנגן כלל. אני מדבר על ה-VOD. נניח מחפשים את התוכנית _עצם העניין_, מגיעים אליה אבל כשלוחצים על תוכנית בתאריך כלשהו, לא מתנגן דבר. אותו הדבר אם מחפשים למשל את התוכנית _מהצד השני_. החיפוש מצליח אבל כשלוחצים על תוכנית כלשהי, לא מתנגן דבר.

ראוי לציין שאני נמצא בספק אקספון בשוק הסיטונאי של בזק (לא סיבים)

**Comment by Fishenzon** [comment]
זה נראה שיש אצלך חסימה כלשהי.
אתה נמצא בחו"ל?
אולי שינוי DNS?
לגבי החיפוש, זה לא אינדיקציה מספיק טובה. הוא עובד בצורה אחרת מהאתר.
תנסה להיכנס לתכניות של ע כאן 11, לכל התכניות ותראה אם מופיע לך רשימה של התכניות.

**Comment by pashosh** [comment]
שמע אתה נהדר.
בראוטר הוגדר (מתמיד) dns ראשי של גוגל 8.8.8.8
ומשני 1.1.1.1
החלפתי ביניהם (כלומר הראשי הפך להיות 1.1.1.1) ועכשיו אין בעיה בכלל.
רואים את 13, 21 וגם את עצם העניין בכאן 11.
ממש ממש מוזר...
ליתר בטחון הפכתי אותם מחדש ושוב ניסיתי להיכנס ל13 ושוב הייתה אותה בעיה (גלגל מסתובב לעולם ועד).
אז כן, מסתבר שזו בעיית dns.

**Comment by pashosh** [comment]
אגב השינוי הזה פתר לי בעיה נוספת שצצה לאחרונה:
תוכניות דרך גוגל פודקסטס (בעיקר טייכר וזרחוביץ') התחילו לפעול הרבה אחרי שלחצתי play.
הרבה אחרי = לפעמים גם מספר דקות (2-3).
עכשיו שמתי לב שהתוכנית עולה מיידית.
המסקנה שלי היא שיש לאקספון איזושהי בעיה עם ה DNS של גוגל.
בספק קודם בו הייתי לא היו הבעיות הספציפיות האלו כאשר הDNS היה של גוגל (אבל כן היו בעיות אחרות).

**Comment by Fishenzon** [comment]
מעולה.
