### ISSUE TITLE
VOD של כאן 11 - הפסיק לפעול

### ISSUE THREAD

**Issue by tzagim** [Fishenzon/repo#165]
ה-VOD של כאן 11 הפסיק לפעול, בגרסה האחרונה

**Comment by pashosh** [comment]
מאשר.
רואים את הכותרות של התוכניות וגם החיפוש עובד, אבל כשנכנסים פנימה, אין תוכן.

**Comment by Fishenzon** [comment]
בוקר טוב.
היה שינוי גדול באתר.
מוזמנים לעדכן לגירסה 3.4.3

**Comment by pashosh** [comment]
תודה רבה.

**Comment by tzagim** [comment]
עובד מעולה, תודה רבה

**Comment by aharonha** [comment]
הבעיה עדיין קיימת בגרסה 3.4.6

**Comment by pashosh** [comment]
תן דוגמא ספציפית, מה לא עובד לך?
כל מה שאני מנסה להפעיל מכאן11, עובד לי.

**Comment by aharonha** [comment]
רשימת התכניות תקינה אבל בתוך התכניות אין כלום (רואים רק את התיקייה ״..״)

**Comment by aharonha** [comment]
בדקתי אתמול והכל הסתדר, תודה @pashosh
