### ISSUE TITLE
ערוץ הידברות לא עובד

### ISSUE THREAD

**Issue by yochananrachamim** [Fishenzon/repo#166]
הסטרים לייב של הידברות כנראה השתנה לאחרונה.
בדקתי והמקור הוא משהו כזה 
https://edge-fs-10.cybercdn.live/HidabrootIL/Live97/HidabrootIL/Live97_high/l_11372_79460960_45658.ts?nimblesessionid={sessionID}
אני עדיין לא יודע איך לקבל את ה SessionID משרת ה סטרימינג
החלפה לURL כזה נותנת ניגון תקין (בדקתי באמצעות VLC)

**Comment by yochananrachamim** [comment]
עדכון, הURL הנכון לניגון הוא : https://edge-fs-20.cybercdn.live/HidabrootIL/Live97/HidabrootIL/Live97_high/chunks.m3u8
רק צריך לעדכן אותו בקובץ hidabroot.py - אשמח לעזרה בביצוע.

**Comment by yochananrachamim** [comment]
אוקי, נבדק ותקין, אחרי שאני מעדכן את הURL ששמתי למעלה הצפיה בהידברות תקינה.

**Comment by Fishenzon** [comment]
תודה.
תוקן בגירסה 3.4.9
