### ISSUE TITLE
VOD כאן חינוכית לא פועל

### ISSUE THREAD

**Issue by tzagim** [Fishenzon/repo#167]
VOD של כאן חינוכית חדל לפעול.
נראה שכל הקישורים מפנים כעת לאתר החדש (ישן?) https://www.kankids.org.il

וכל התוכן נמצא תחת https://www.kankids.org.il/content/kids/hinuchit-main/XXXXX/עונה-Y/

XXXXX= p-xxxxx / שם התוכנית
Y= מספר העונה

**Comment by Fishenzon** [comment]
תודה.
תוקן בגירסה 3.4.9

**Comment by tzagim** [comment]
תודה, עדיין לא תוקן לגמרי, יש הרבה שמופיעים רק ב"אתר ישן" והוא עדיין לא תוקן

**Comment by tzagim** [comment]
@Fishenzon 
מסתבר שכולם מופיעים באתר החדש אך הסקריפט לא מושך אותם, לדוגמה: גלילאו, פרפר נחמד ועוד

**Comment by Fishenzon** [comment]
היה שינוי באתר, סידרתי ועכשיו זה אמור להציג מה שיש באתר

**Comment by tzagim** [comment]
תודה רבה, עובד מעולה!
