### ISSUE TITLE
חיפוש

### ISSUE THREAD

**Issue by MrTal** [Fishenzon/repo#17]
היי,
שמתי לב שאין חיפוש ב-VOD של:
כאן
רשת
ערוץ 10
ערוץ 20
רק בקשת קיים חיפוש
האם זה לא אפשר מבחינה טכנית? ידוע לך העניין?
ראיתי יש אפשרות של סינון דרך התפריט, אבל זה עובד על הפנים בעברית ולא מזהה טוב בכלל

בנוסף לכך האם יש דרך להוסיף את הפודאקסטים של כאן להרחבה?:
https://www.kan.org.il/podcast/

תודה מראש!

**Comment by Fishenzon** [comment]
@MrTal 
נוסף חיפוש תכניות למסך הכניסה של ההרחבה.
אבדוק בהמשך פודקאסטים

**Comment by MrTal** [comment]
עובד מעולה החיפוש!
תודה רבה!
עוד משהו שהייתי ממליץ לתקן  זה שבהגדרות שלוחצים על קביעת איכות שידור אתה מגיע לתפריט שצריך לכתוב בו משהו, לא בידיוק ברור איך לכתוב מה לכתוב
הייתי ממליץ פשוט במקום התפריט כתיבה לתת את האופציות שיש (1080 720 וכו')
וכל משתמש יבחר, יותר נוח לדעתי

**Comment by Fishenzon** [comment]
@MrTal 
נוספה האפשרות לקבוע איכות שידור מירבית גם בקליק ימני על פרק ברשימה.

**Comment by Fishenzon** [comment]
@MrTal 
תפריט הבחירה נלקח מהלינק שמנסים לנגן.
לכן, יכולים להופיע לך בפרקים שונים מאותו האתר איכויות שונות.
בפתיחת ההגדרות, אין לי נתונים של אף לינק לניגון

**Comment by MrTal** [comment]
@Fishenzon 
הבנתי לא קריטי חח
תודה על ההשקעה,
בזמנך הפנוי
https://www.kan.org.il/page.aspx?landingpageid=1039
הוסיפו ל-VOD שלהם גם
:תוכנית מהחינוכית
https://www.kan.org.il/page.aspx?landingPageId=1083
http://prntscr.com/l1a5j4
אם יהיה אפשר להוסיף זה יהיה גם אחלה
וגם הם ערכו כמה שינויים בשמות באתר אז הייתי ממליץ  במקום:
http://prntscr.com/l1a6qv
לכתוב "כל התוכניות" (זה מוביל לתפריט של כל התוכניות"
ובמקום "רצועת אקטואליה"  לכתוב "תוכנית אקטואליה"
לא שזה קריטי אבל סתם אולי שיהיה מעודכן
כמובן בזמנך הפנוי!!
תודה רבה על על ההשקעה

**Comment by Fishenzon** [comment]
@MrTal 
נוספו תכניות החינוכית.
נוספו הפודקאסטים.
שמות הקטגוריות עודכנו לכיתוב שבאתר.

**Comment by MrTal** [comment]
@Fishenzon 
תודה רבה!
אם תוכל להוסיף גם את זה חח:
https://www.kan.org.il/program/?catId=1114
וגם שמתי לב שבכאן אי אפשר לבחור איכות שידור, זה בגלל שזה לא אפשרי טכנית גם באתר שלהם?
ועכשיו mako tv הפסק לעבוד משום מה

**Comment by Fishenzon** [comment]
@MrTal 
לגבי מאקו, אתה צודק - טעות שלי.  בדוק את גירסה 1.8.3
כמעט כל התכנים של כאן נלקחים מיוטיוב, גם ההרחבה מפנה את הלינקים לניגון דרך יוטיוב. לכן השליטה על האיכות היא דרך הגדרות ההרחבה של יוטיוב.
לא כללתי בחיפוש את תוכניות הרדיו והפודקאסטים, אנסה להוסיף.
כנ"ל לגבי הקטגוריה שהבאת.

**Comment by MrTal** [comment]
@Fishenzon 
אחלה תודה רבה!
שמתי לב שנעלם גם האופציה לבחירות איכות צפייה במאקו בעדכון האחרון

**Comment by Fishenzon** [comment]
@MrTal 
לא נעלם.
לפעמים יש פרקים באתר שמנוגנים בפורמט שונה ואז לא ניתן לבחור איכות.
לפעמים זה קורה בפרק חדש ואחרי כמה זמן מתעדכן לו המקור ואז אפשר שוב לבחור איכות.

**Comment by MrTal** [comment]
@Fishenzon 
הבנתי
ואני לא רואה איפה שזה מופיע בל התכוניות, לא מצאתי שם לדוגמה את קדם האריווזיון

**Comment by MrTal** [comment]
ומשהו נוסף, שיגעתי אותך חח כמובן בזמנך הפנוי ואם יש לך כוח
להוסיף גם את התכנים של רשת 13 להרחבה:
https://reshet.tv/news/channel2-news/

**Comment by Fishenzon** [comment]
> @Fishenzon
> הבנתי
> ואני לא רואה איפה שזה מופיע בל התכוניות, לא מצאתי שם לדוגמה את קדם האריווזיון

התכנית (הדף) נקראת "כאן ספיישלים"

**Comment by MrTal** [comment]
@Fishenzon 
צודק עכשיו שמתי לב
יהיה נחמד אם יהיה אפשר להוסיף גם את זה לחיפוש, כנראה לא מצאתי את זה כי התוכניות שנמצאים שם לא מופיעות בתוך החיפוש אם זה אפשרי מבחינה טכנית זה יהיה נחמד

**Comment by MrTal** [comment]
@Fishenzon 
ועל הדרך אם זה אפשר להוסיף גם בחיפוש את מה שנמצא בתוך
 "כאן דרמה"
"כאן דוקו"
"מכאן ומשם"

**Comment by Fishenzon** [comment]
@MrTal 
בשלב זה החיפוש מחזיר רק תוכניות ולא פרקים.
במקרים האלו, זה השם של התכנית.

**Comment by MrTal** [comment]
@Fishenzon 
לא יודע למה אבל לא הכול בחיפוש עובד, לדוגמה כתבתי "המובן מאליו" זה לא מצא לי
בדקתי וזה כן מופיע בפודקאסטים

**Comment by MrTal** [comment]
@Fishenzon 
נראה שהסתדר העניין של החיפוש בפודקאסטים ועכשיו הוא כן מוצא את כל הפודקאסטים
בזמנך הפנוי ובמידה ויש לך כוח להוסיף גם את התכנים שפה לרשת::
https://reshet.tv/news/channel2-news/

**Comment by MrTal** [comment]
@Fishenzon 
שמתי לב גם לאיזה באג, במידה ולוחצים על קבע איכות ניגון ואז אתה לוחץ על "ביטול" זה מכניס אותך אוטומטי לאיכות הכי גבוהה ולא מבטל את החלונית

**Comment by Fishenzon** [comment]
@MrTal 
ככה בניתי את זה. זה ביטול של בחירת האיכות, לא ביטול של הניגון עצמו.

**Comment by rafi-d** [comment]
> משהו נוסף ששמתי לב שקצת מפריע שאתה נכנס לתוך תוכנית יומיות עם הרבה פרקים זה מציג לך אותם בצורה מבולגנת ולא על פי התאריך עלייה שלהם, לדוגמה: אם תכנס "הכול אישי" עונה 2 תראה שהתאריכים לא מופיעים לפי הסדר שלהם:

זה תלוי בבחירה שלך לכל ערוץ - לפי סדר באתר או לפי 
A-Z
הבעיה היא שזה משפיע גם וגם - גם על רשימת התוכניות וגם בתוך כל תוכנית
יותר טוב היה אם לא היתה השפעה של זה על רשימת הפרקים/עונות ואלו תמיד היו מסודרים לפי תאריך (= מס פרק)

**Comment by rafi-d** [comment]
לא בטוח שיש טעם באופציה. פרקים/עונות תמיד רצוי לסדר לפי סדר הקרנתם (תאריך או מספר רץ)
ואולי תמיד בסדר הפוך
 או שאת זה לשים כאופציה (האחרון למעלה)

**Comment by MrTal** [comment]
@rafi-d 
שאני חושב על זה אתה צודק,

@Fishenzon 
אז בקיצור חח אם אפשר בזמנך הפנוי לעשות שה"הצג לפי הסדר באתר / לפי ABC"
ישפיע רק על הרשימה של הסדרות ולא על הרשימה של הפרקים עצמם - ששם לעשות שזה תמיד יסודר לפי סדר הפרקים מהחדש לישן

**Comment by Fishenzon** [comment]
@MrTal 
רשימת הפרקים במאקו מסודרת עכשיו לפי תאריך.
משום מה פונקצית המיון המובנית של קודי לא מסדרת נכון לפי תאריך

**Comment by rafi-d** [comment]
תודה.
 תוכל גם להפעיל עבור פרקים את האופציה ACCENDING DECCENDING 
של קודי 
או/ו  לתת אופציה גלובלית כזאת אצלך?

**Comment by MrTal** [comment]
@Fishenzon 
עכשיו עובד מעולה, תודה!

**Comment by rafi-d** [comment]
והיום זה כבר לא כ"כ מעולה... 
בדקתי 012 - חדשות - התוכנית הכלכלית. נראה שהסידור שם לא לפי תאריך, אלא אלפאבתי - 1.11 מופיע בראש 
הרשימה ולא בסוף.
מה לעשות - התאריך 1.11 צ"ל אחרי... אוקטובר.. 

בקיצור - שנה->חודש->יום 
לא משמאל לימין...

**Comment by MrTal** [comment]
@rafi-d 
הכול שם מסודר לפי התאריך רק משום מה הפרק החדש נמצא בראש הרשימה
מה שכן הייתי מציע שהתוכנית הכי חדשה תופיע ראשונה ואחר כך הישנים (אם לוחצים על לשנות סדר עולה / יורד ) זה לא משפיע, אבל אני לא הכי בטוח שזה אפשרי מבחינה טכנית

**Comment by MrTal** [comment]
@rafi-d 
לדוגמה ברשת זה עובד מעולה בלי בעיות

**Comment by rafi-d** [comment]
:נכון, אבל שים לב:
שם השידור הוא בסדר תאריכים יורד 
ו-שם אין את הכיתוב של התאריך עצמו כמו כאן, ושלדעתי יש מצב שגורר את הבאג הזה בגלל בפורמט בישראלי שלו - DD-MM-YY

**Comment by Fishenzon** [comment]
@MrTal , @rafi-d 
היו שני סוגי תאריכים במאקו, סידרתי שיסדר בשני המקרים בסדר יורד.
בתכניות של כאן נוספו תכניות שלא הוצגו כי הלינק שלהם היה רק קיצור דרך לדף אחר. (לדוגמה: "בואו לאכול איתי")

**Comment by MrTal** [comment]
@Fishenzon 
תודה רבה עכשיו מעולה!
מתאים שיש לך זמן, יהיה מעולה ונחמד מאוד להוסיף את התכנים שפה שמשום מה לא מופיעים בהרחבה:
https://www.mako.co.il/news-channel2?partner=BreadCrumbs
(כנראה בגלל שהם באתר של MAKO ולא בMAKO TV)
אם זה אפשרי זה יהיה מעולה
(כנ"ל לגבי רשת: https://reshet.tv/news/channel2-news/ שהזכרתי לך אז)
כמובן בזמנך הפנוי, תודה!

**Comment by rafi-d** [comment]
> @MrTal , @rafi-d
> היו שני סוגי תאריכים במאקו, סידרתי שיסדר בשני המקרים בסדר יורד.
> בתכניות של כאן נוספו תכניות שלא הוצגו כי הלינק שלהם היה רק קיצור דרך לדף אחר. (לדוגמה: "בואו לאכול איתי")

תודה, נראה מסודר סבבה!

**Comment by rafi-d** [comment]
המיזוג בוטל...
ועוד מעט גם ערוץ 10 לא יהיה...

 @MrTal    
מציע לסגור את ה באג הזה..

**Comment by rafi-d** [comment]
"במועצת הרשות מחכים להמלצות ועדת הריכוזיות, שעמה היא צריכה להתייעץ. המלצות הוועדה יכולות להתייחס "הם לעצם אישור המיזוג והן לתנאים מגבילים

אז זה לא סופי... רק כמעט...

**Comment by rafi-d** [comment]
מי יודע, אולי יתנו להם שני ערוצים לשידור במקביל...

**Comment by MrTal** [comment]
@rafi-d 
כל ההערכות שהם יתחילו לשדר כבר באחד בינואר
בכל מקרה זה לא הדיון חח,
אולי בנתיים להוסיף רק את התכנים של קשת, שם זה נשאר בטוח:
https://www.mako.co.il/news-channel2?partner=BreadCrumbs
(אם זה לא עבודה קשה)

**Comment by Fishenzon** [comment]
נחכה קודם למיזוג

**Comment by MrTal** [comment]
אין בעיה
שמתי לב למשהו בכאן
הנגן של כאן הוא ביוטיוב, אז שבוחרים נגיד לבחור פרק אז האיכות ברירת מחדל שתוצג לך 720p 
ואין דרך לשנות אותה ל-1080p
דוגמה:
https://www.youtube.com/watch?v=ddEEE3COe0A 
זמן אמת - זמן באתר של כאן (ביוטיוב) ב-1080p
בהרחבה ב-720p
http://prntscr.com/ljz7mv
יש משהו לעשות עם זה? או שבגלל שזה ביוטיוב זה בלתי אפשרי

**Comment by Fishenzon** [comment]
@MrTal 
צריך לשנות הגדרות של יוטיוב ושל InputStream

![screenshot000](https://user-images.githubusercontent.com/29551534/48687446-274bcb80-ebca-11e8-92f1-9cb628b07108.png)
![screenshot001](https://user-images.githubusercontent.com/29551534/48687447-274bcb80-ebca-11e8-9375-40c229e8aece.png)
![screenshot002](https://user-images.githubusercontent.com/29551534/48687449-274bcb80-ebca-11e8-90a8-c4cb517c0f5f.png)
![screenshot003](https://user-images.githubusercontent.com/29551534/48687450-274bcb80-ebca-11e8-89a8-4e5ec705daa8.png)

**Comment by MrTal** [comment]
@Fishenzon 
עשיתי וזה נשאר עדיין אותו דבר
וזה לא נותן לי לשנות שום דבר ב-MPEG- DASH
http://prntscr.com/lk79z6
זה ככה ברירת מחדל
(InputStream היה מנוטרל אצלי עד עכשיו אז הפעלתי אותו עכשיו והגדרתי גם שם)

**Comment by Fishenzon** [comment]
נסה שוב, זה אמור לעבוד.

![screenshot004](https://user-images.githubusercontent.com/29551534/48712268-03ae7280-ec16-11e8-9cf6-ad00e11906c5.png)

**Comment by Fishenzon** [comment]
@MrTal 
אני יכול להוסיף את זה בגירסה הבאה.
דרך אגב, כותרת המשנה מופיעה באתר בזמן ניגן פרק. 
תוכל לראות את זה תחת פרקים נוספים.

לגבי הסדרה שרשמת היא הופיעה בשתי התצוגות.
היא לא הופיעה בחיפוש כי אני מעדכן את הרשימה פעם בכמה ימים.

![capture](https://user-images.githubusercontent.com/29551534/49132014-1f370e80-f2e3-11e8-9910-baa99f8ec758.JPG)

**Comment by MrTal** [comment]
@Fishenzon 
שבוע טוב!
בלי קשר, משום מה התוכנית "המיזם" של רשת לא מופיע בהרחבה:
https://reshet.tv/news/hameyzam/

**Comment by Fishenzon** [comment]
@MrTal 
הוספתי בגירסה האחרונה אפשרות להסתרת כותרת משנה לתכניות מאקו.
משום מה רשת החליטו לשים את התוכנית "המיזם" באתר במיקום אחר משאר ה-VOD ולכן היא לא מופיעה
אני הולך לסגור את השרשור הזה שהפך להיות צ'אט, עדיף לצורך המעקב לפתוח על כל שאלה או הצעה שרשור חדש.

**Comment by MrTal** [comment]
@Fishenzon 
עובד יפה האופציה, תודה רבה הרבה יותר נוח ומסודר עכשיו.
כן גם אני חשבתי נהיה פה כבר באלגן חח, אתה יכול לסגור ופשוט אפתח חדש על בעיה חדש או  הצעה חדשה
תודה רבה!
