### ISSUE TITLE
חלוקת קטגוריות בכאן 11

### ISSUE THREAD

**Issue by test01203** [Fishenzon/repo#173]
היי שמתי לב שאין חלוקת קטגוריות כמו באתר של כאן 11 
https://www.kan.org.il/lobby/kan-box/
לדוגמה קטגוריות סרטים, פשע וכו 
לעומת זאת כן יש תוכניות אקטואליה 
אשמח לעדכון

**Comment by Fishenzon** [comment]
בוקר טוב.
נוספה חלוקה לקטגוריות לפני כמה גירסאות
