### ISSUE TITLE
קטגוריות מאוחדות

### ISSUE THREAD

**Issue by test01203** [Fishenzon/repo#174]
בישראל יש רק שלוש ערוצים קשת רשת וכאן 11 - 
ומה שהרוב רוב זה סרטים וסדרות בהם 
יהיה טוב אם תהיה קטגוריות מאוחדת לשלושתם ומתעדכנת לפי תאריך
כאשר נקבל את התכנים הכי חדשים בכל את מהקטגוריות

**Comment by Fishenzon** [comment]
תודה על ההצעה אבל אין לי זמן להשקיע בזה.
