### ISSUE TITLE
urrlib3 addon update broke Idan Plus

### ISSUE THREAD

**Issue by TwilightMercy** [Fishenzon/repo#178]
urrlib3 addon updated to 2.1.0:

![image](https://github.com/Fishenzon/repo/assets/29895680/66ca5a06-f9ea-4302-9353-85ca1b8c473b)

After the update:

```
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
			- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
		   Error Type: <class 'ImportError'>
		   Error Contents: cannot import name 'appengine' from 'urllib3.contrib' (C:\Users\<censored>\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\contrib\__init__.py)
		   Traceback (most recent call last):
			 File "C:\Users\<censored>\AppData\Roaming\Kodi\addons\plugin.video.idanplus\resources\lib\requests_toolbelt\_compat.py", line 48, in <module>
			   from requests.packages.urllib3.contrib import appengine as gaecontrib
		   ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (C:\Users\<censored>\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\contrib\__init__.py)
		   
		   During handling of the above exception, another exception occurred:
		   
		   Traceback (most recent call last):
			 File "C:\Users\<censored>\AppData\Roaming\Kodi\addons\plugin.video.idanplus\default.py", line 3, in <module>
			   from resources.main import route
			 File "C:\Users\<censored>\AppData\Roaming\Kodi\addons\plugin.video.idanplus\resources\main.py", line 4, in <module>
			   import resources.lib.common as common
			 File "C:\Users\<censored>\AppData\Roaming\Kodi\addons\plugin.video.idanplus\resources\lib\common.py", line 4, in <module>
			   import resources.lib.cloudscraper as cloudscraper
			 File "C:\Users\<censored>\AppData\Roaming\Kodi\addons\plugin.video.idanplus\resources\lib\cloudscraper\__init__.py", line 14, in <module>
			   from resources.lib.requests_toolbelt.utils import dump
			 File "C:\Users\<censored>\AppData\Roaming\Kodi\addons\plugin.video.idanplus\resources\lib\requests_toolbelt\__init__.py", line 12, in <module>
			   from .adapters import SSLAdapter, SourceAddressAdapter
			 File "C:\Users\<censored>\AppData\Roaming\Kodi\addons\plugin.video.idanplus\resources\lib\requests_toolbelt\adapters\__init__.py", line 12, in <module>
			   from .ssl import SSLAdapter
			 File "C:\Users\<censored>\AppData\Roaming\Kodi\addons\plugin.video.idanplus\resources\lib\requests_toolbelt\adapters\ssl.py", line 16, in <module>
			   from .._compat import poolmanager
			 File "C:\Users\<censored>\AppData\Roaming\Kodi\addons\plugin.video.idanplus\resources\lib\requests_toolbelt\_compat.py", line 50, in <module>
			   from urllib3.contrib import appengine as gaecontrib
		   ImportError: cannot import name 'appengine' from 'urllib3.contrib' (C:\Users\<censored>\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\contrib\__init__.py)
		   -->End of Python script error report<--
```

Previous urllib3 version works:
https://mirrors.kodi.tv/addons/nexus/script.module.urllib3/

From the log - the requests_toolbelt dependency broke
https://github.com/requests/toolbelt

**Comment by pierre-leon** [comment]
+1

**Comment by oferchen** [comment]
+1

**Comment by mayrund** [comment]
I was having the issue the issue this morning, temporary solution you can manually install urllib3 1.26.13 from
https://mirrors.kodi.tv/addons/nexus/script.module.urllib3/

**Comment by leeronr** [comment]
Apparently, `urllib3` v2  (and through it `requests`) deprecated support for Google App Engine (GAE), along with anything else that's not CPython or PyPy3 (https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html), so GAE requests will have to be made using a different module.

WIll try to take a look at the code later but @mayrund 's workaround should do the trick for now and I'm sure @Fishenzon is probably already on it anyways.

**Comment by TwilightMercy** [comment]
> Yes, that's why the told me in their github:
> 
> ```
> This was removed in 2.0 https://urllib3.readthedocs.io/en/stable/changelog.html#id10
> 
> Please read the changelog before upgrading and confirm your system and it's dependencies are compatible. You should determine what plugin is incompatible and file a bug with them as we will not be adding this back.
> ```

Can you send a link of this issue?

**Comment by burekas7** [comment]
> cannot import name 'appengine' from 'urllib3.contrib'

https://github.com/urllib3/urllib3/issues/3220

**Comment by oferchen** [comment]
look like requests toolbelt mentions these changes about 7 months ago https://github.com/requests/toolbelt/blob/master/HISTORY.rst
can the build be updated to use a more recent requests toolbelt? https://github.com/requests/toolbelt/tree/master

**Comment by Fishenzon** [comment]
did you try restart Kodi after the update?
I need logs to see if there are errors.

**Comment by oferchen** [comment]
logs are at `~/.kodi/temp/kodi.log`

**Comment by techproent** [comment]
> Yes it’s after restart, can you point me to the logs?

Did you update/refresh the Fishenzon Repo (to pull the new 3.5.3 version)?

**Comment by Fishenzon** [comment]
what's the Kodi version? "script.module.requests" version and "script.module.urllib3" version?

**Comment by asherungar** [comment]
Kodi 19.1
Requests 2.31
Urllib 2.1.0 

I downgraded urllib as mentioned above for a workaround for now.

**Comment by burekas7** [comment]
> I can confirm v 3.5.3 works for me. thanks for fixing this so fast, much appreciated !!

Works for me too.
Thanks!
