### ISSUE TITLE
תיקון בחירת רזולוציה עבור כאן 11 (הרגיל) ל 1080

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#180]
שלום,

התוסף נותן את כאן11 באיכות 720P בלבד, אבל בלינק ללקויי שמיעה יש - 1080P . תוכל בבקשה להחליף  ל1080P גם בערוץ הרגיל שלהם? 
(יש לי לינק מתאים אם אתה צריך...)

**Comment by Fishenzon** [comment]
הי.
אצלי זה מנגן 1080, תבדוק אם לא שמרת קיצור דרך ישן או שלחצת דרך התפריט בלחיצה על הערוץ על קביעת איכות ניגון.

**Comment by rafi-d** [comment]
צודק, ברגע שבחרתי אוטומטי (שוב) זה הסתדר. כנראה היה שמום באיזה מקום פנימי מקודם...

**Comment by Fishenzon** [comment]
מעולה

**Comment by rafi-d** [comment]
אגב, שמתי לב שאם  אתה מסמן בקודי "HIDE WATCHED" (אולי בתוסף אחר) - נעלמים ערוצים גם מהרשימה הזאת...  אולי כדאי לבטל את האופציה הזאת מהבחירות הרגילות של קודי ברשימה הזאת בלבד (אם זה לא קשה מדי...).
