### ISSUE TITLE
ערוץ 21, ערוץ הקניות לא עובד כבר תקופה. 

### ISSUE THREAD

**Issue by pashosh** [Fishenzon/repo#181]
כשמנסים להיכנס פשוט לא קורה דבר.

**Comment by Fishenzon** [comment]
לא ראיתי בעיה עם הערוץ

**Comment by pashosh** [comment]
בטוח?
זה רק אצלי?
לא עובד לי בכלל...

**Comment by pashosh** [comment]
אוקיי בדקתי במספר התקנות שונות של קודי ובאחת מהן ואחת בלבד (דווקא על ווינדווז) 21 עובד לי תקין.
בלינוקס שלי לא עובד בכלל כבר חודשיים לפחות.
אותו הדבר בסטרימר.
לא יודע מה פה קורה פה.

**Comment by pashosh** [comment]
יצרתי log של קודי.
נכנסתי לעידן + וניסיתי להפעיל את ערוץ 21 שלא עובד ואז יצרתי את הלוג שנמצא בכתובת הזו:
https://paste.kodi.tv/ayacorewoy
כמו כן, בדקתי את זה על מחשב אחר.
גם שם (יש עליו ווינדווז) 21 תקין.
זה ניראה שהבעיה היא בלינוקס (לפחות אצלי) ובסטרימר שלי.

**Comment by pashosh** [comment]
עדכון מרתק נוסף.
התקנתי ווינדווז בתוך מכונה וירטואלית, על הלינוקס שלי.
שם התקנתי את קודי ולא יאמן אבל גם שם ערוץ 21 עובד היטב.
כלומר במארח (הלינוקס שלי) 21 לא עובד אבל בתוך המכונה הוירטואלית (בווינדווז) הוא כן עובד.

**Comment by rafi-d** [comment]
> לא ראיתי בעיה עם הערוץ

תבדוק באנדרואיד , רק שם זה לא עובד.  בחלונות זה עובד.
