### ISSUE TITLE
[Request] Any chance to add Stremio add-on support?

### ISSUE THREAD

**Issue by SubEdict** [Fishenzon/repo#182]
Hi
While it works great on Kodi, now that Stremio works on Samsung TV's it will be a great add to [Strermio addons community](https://stremio-addons.netlify.app/).
Just wondering.

Heb: ?עכשיו שסטרימיו נתמך בטלוויזיות של סמסונג, האם יש סיכוי לבניית תוסף בדיוק כמו לקודי

Thanks

**Comment by oferchen** [comment]
Hello,I’ll write in English to simplify things.Stermio is based around nodejs which means the extension would have to be rebuilt from scratch(possible) but I’m not sure it is related to this project.Thank you,OferSent from my iPhoneOn 14 Jan 2024, at 17:27, SubEdict ***@***.***> wrote:﻿
Hi
While it works great on Kodi, now that Stremio works on Samsung TV's it will be a great add to Strermio addons community.
Just wondering.
Heb: ?עכשיו שסטרימיו נתמך בטלוויזיות של סמסונג, האם יש סיכוי לבניית תוסף בדיוק כמו לקודי
Thanks

**Comment by SubEdict** [comment]
Oh… "Rebuilt from scratch", yeah, that a lot, thought it's the same code, bummer.
Thanks anyway @oferchen and hope you keep up maintaining this one, great job. 🤟

**Comment by oferchen** [comment]
Oh I’m not the one maintaining it I just took a look at Stremio to understand what will it take to port it over. I don’t expect it to be took difficult to redo from scratch.OferSent from my iPhoneOn 14 Jan 2024, at 19:26, SubEdict ***@***.***> wrote:﻿
Oh… "Rebuilt from scratch", yeah, that a lot, thought it's the same code, bummer.
Thanks anyway @oferchen and hope you keep up maintaining this one, great job. 🤟

**Comment by pashosh** [comment]
בעיקרון אתה יכול להשתמש בקודי כבר עכשיו ממש כמו שאתה משתמש בסטרמיו.
יש תוסף לקודי בשם elementum שמאפשר לך לצפות בטורנטים, ממש כמו שסטרמיו עושה.
אם אתה מדבר על שירותים בתשלום כמו real debrid, גם פה יש תוספים לקודי כמו twilight או fen או seren.
