### ISSUE TITLE
שאלה בקשר לקביעת איכות ניגון בעידן פלוס.

### ISSUE THREAD

**Issue by ASD2356** [Fishenzon/repo#185]
אולי, אתם יודעים, שאלה, בהגדרות ההרחבה של עידן פלוס, פישינזון, יש לשונית שכתוב בה, מאקו, ושאני בוחר באפשרות של קביעת איכות ניגון, אז אני מקבל מקלדת, מה לרשום במקלדת כדי לשנות את איכות הניגון בתכני מאקו?

**Comment by rafi-d** [comment]
לפני שאתה צופה בערות מסויים, תפעיל ע"י קליק ימני - "בחירת איכות ניגון" - ותראה רשימה של רזולוציות (720[], [576], [320] וכו). תוכל לשים בהגדרות כל אחד מהם.

אני מסכים אתך שזה ממה לא ידידותי למשתמש, וממליץ לשנות את המימוש - כך שאפשר יהיה להכניס כל מספר כרזולוציה *מכסימאלית* , נניח עד 4096 (4K) .  התוסף יבצע את הגבוה ביותר שניתן לביצוע עבור הערוץ מהאפשרויות הקימות בו.

ככה לפחות לא יצטרכו לנחש/לבדוק מה ההרשימה בפועל...

בינינו, אני לא מביו למה בכלל לנסות ולהגביל איכות, כשכל מכשיר מודרני היום (סטרימר/מחשב) יכול לנגדן עד 1080P בלי בעיה... בד"כ גם 4K שממילא אין לנו בערוצים...

**Comment by Fishenzon** [comment]
קביעת / בחירת האיכות מתבצעת לפי הביטרייט ולא לפי הרזולוציה הכתובה בסוגריים.
יש מצבים שיכול להיותר ביטרייט גבוה יותר באותה הרזולוציה.
אפשר לכתוב ישירות בהגדרות מספר ביטרייט וההרחבה תמצא את הביטרייט הכי גבוהה שקטן או שווה למספר הזה.

![image](https://github.com/Fishenzon/repo/assets/29551534/7348b8b0-0f31-4e93-8e49-c99dfb6b0fdf)

**Comment by rafi-d** [comment]
לדעתי, יהיה נוח יותר אם אפשר יהיה להשתמש גם במספרים המוכרים לכולם (והקצרים...) של הרזולוציה . 
אפשר אולי לתת גם את הזיהוי לפי זה? נניח - כל המספרים מתחת ל 10000 - ילקחו כרזולוציה, וינוגן הסטרים שקטן או שווה לביטרייט הגבוה ביותר שמשויך להם?

**Comment by Fishenzon** [comment]
אולי נוסיף בהמשך כשיהיה לי זמן
