### ISSUE TITLE
שאלה בקשר להגדרת איכות צליל בניגון

### ISSUE THREAD

**Issue by ASD2356** [Fishenzon/repo#186]
שאלה, אולי אתם יודעים, בהגדרות ההרחבה של עידן פלוס, פישינזון, יש לשונית שכתוב בה, מאקו, ושאני בוחר באפשרות של קביעת איכות ניגון, אז אני מקבל מקלדת, אז השאלה היא, מה לרשום במקלדת ששם כדי לשנות את איכות הניגון בתכני מאקו?

**Comment by Fishenzon** [comment]
לא בוחרים איכות צליל אלא על איכות וידאו. 
תיכנס להרחבה עצמה, תלחץ קליק ימני (או לחיצה ארוכה) על פרק מסויים (או על ערוץ 12 אם מדובר על שידור חי) ותבחר על קביעת איכות.
