### ISSUE TITLE
חוסר סנכרון בין  וידאו לאאודיו

### ISSUE THREAD

**Issue by albilia** [Fishenzon/repo#187]
שלום, 
לאחרונה התקנתי את הריפו על טלויזיה מדגם LG WEB OS [פרטים בתחתית הפוסט],
וחווה חוסר תיאום/סנכרון בין תנועת השפתיים לאאודיו, אם בוחר להכנס דרך טלויזיה/ערוצים/כל הערוצים. 

קיימות 2 אופציות להכנס לערוצים החיים דרך הריפו.
א. לחיצה על האייקון 'עידן פלוס' ולאחר מכן 'טלויזיה'. 
ב. בקובץ ההגדרות Iptv Simple Client ניתן להגדיר שהתוסף ישתמש בקבצי עידן פלוס. 
ברגע שהברירה הזו נבחרה וניגשים להפעיל את הערוצים החיים מ - 'טלויזיה' > 'ערוצים' 
וצופים בערוצים החיים משם, קיים חוסר סנכרון בין הוידאו לאאודיו.
כלומר, אם מסתכלים לצורך העניין בתנועת השפתיים של מגיש החדשות, השמע לא מסונכרן בהתאם.
זה קורה רק באופציה ב'. 

*** ההעדפה כמובן לעבוד דווקא דרך אופציה ב' מאחר וניתן לגלול דרך השלט בנוחות יותר ולקבל מידע בדרך הזו.
ודווקא באפשרות הזו הדילאיי קיים. 

אשמח לדעת האם קיים פתרון. 

צופה בטלויזיה Lg Web Os
גרסת ווב או.אס: 8.2.0-20
קודי הותקן דרך: Homebrew Channel
גרסת קודי: 21.0 בטה 2. 
20.90.821

תודה מראש. 
![אופציה ב](https://github.com/Fishenzon/repo/assets/21350120/f0ed0163-7fa5-4b06-aa46-59473bd50db2)

**Comment by Fishenzon** [comment]
מדובר על עבודה מול טלויזיה חיה, זה לא בשליטת ההרחבה

**Comment by Fishenzon** [comment]
לפי מה שכתבו פה בנושא דומה, צריך לבטל כנראה את ה-TIMESHIFT  בהגדרות של הטלויזיה חיה
