### ISSUE TITLE
Timeshifting buffering in live tv (except for Kan11)

### ISSUE THREAD

**Issue by lamama1234** [Fishenzon/repo#189]
היי ותודה על העבודה המדהימה.

שדרגתי קודי מגירסה 19.4 ל-20.3 על אנדרואיד טיוי (TCL). אחרי התקנת תוסף עידן+ אני מקבל תופעה מוזרה. כשאני מנגן תחנות טלויזיה דרך ה-PVR אני מקבל באפרינג (תקוע חזק ולא משתחרר) אחרי כמה שניות של ניגון תקין. זה קורה רק בערוצים 12,13,14 אבל ב-11 הכל תקין. כשאני מנגן את הערוצים דרך התוסף - הכל תקין ואין באפרינג באף ערוץ. מה יכול לגרום לזה ב-PVR? ד"א בגירסה 19.4 זה לא קרה.

תודה שוב

**Comment by lamama1234** [comment]
מצאתי - זה קורה רק כאשר אופציות TIMESHIFT מאופשרת. העניין שאפשר לעשות טיימשיפט בכאן 11 אבל בשאר הערוצים תהיה תקיעת באפרינג אחרי כ-10 שניות. אז כרגע ניטרלתי את האופציה אבל השאלה אם זה משהו פתיר.

שיניתי את הנושא בהתאם.

**Comment by Fishenzon** [comment]
תודה רבה על מציאת הפתרון. זה כנראה קשור לשיטת השידור של הערוץ או לאופן הפעולה של רכיב ה-TIMESHIFT .
בכל מקרה נראה שזה לא קשור להרחבה.
