### ISSUE TITLE
זהו זה ב-VOD

### ISSUE THREAD

**Issue by go-vegan** [Fishenzon/repo#191]
ישנן 2 בעיות עם "זהו זה" ב-VOD של ערוץ 11:
1. שמות הפרקים לא תקינים.
2. בשבוע האחרון לא ניתן בכלל להיכנס לרשימת הפרקים. הקודי נתקע.

גירסא 3.5.4

**Comment by go-vegan** [comment]
יש רעיונות?
האם צריכים עוד מידע?
האם זה קורה גם אצלכם?
תודה.

**Comment by rafi-d** [comment]
כן, קורה גם אצלי. 

לפי הקוד/HTMP  בוא הדפים כתובים , יש את המידע המדוייק על התינקים והשמות בכל דף ודף, במבני הנתונים הבאים, שאולי יעזרו למפתח לאתר שמות ולינקים (ולא לתחזק רשימות ידנית...) :

עבור דף ראשי של סדרה (מנייכ) : 
`<link href="[/sb/kan-layout-css.css.v2024020623](view-source:https://www.kan.org.il/sb/kan-layout-css.css.v2024020623)" rel="stylesheet" />


        <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          "itemListElement":[

             {
                 "@type": "ListItem",
                 "position": 1,
                 "name": "דף הבית",
                 "item": "https://www.kan.org.il/"
             },
            
             {
                 "@type": "ListItem",
                 "position": 2,
                 "name": "ספריית תוכן",
                 "item": "https://www.kan.org.il/content/"
             },
            
             {
                 "@type": "ListItem",
                 "position": 3,
                 "name": "כאן",
                 "item": "https://www.kan.org.il/content/kan/"
             },
            
             {
                 "@type": "ListItem",
                 "position": 4,
                 "name": "כאן 11",
                 "item": "https://www.kan.org.il/content/kan/kan-11/"
             },
                        {             
                 "@type": "ListItem",
                 "position": 5,
                 "name": "מנאייכ"
            }
          ]
        }
    </script>`

עבור פרק של סגרה (מנייכ S3E1):
`<link href="[/sb/kan-layout-css.css.v2024020623](view-source:https://www.kan.org.il/sb/kan-layout-css.css.v2024020623)" rel="stylesheet" />


        <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          "itemListElement":[

             {
                 "@type": "ListItem",
                 "position": 1,
                 "name": "דף הבית",
                 "item": "https://www.kan.org.il/"
             },
            
             {
                 "@type": "ListItem",
                 "position": 2,
                 "name": "ספריית תוכן",
                 "item": "https://www.kan.org.il/content/"
             },
            
             {
                 "@type": "ListItem",
                 "position": 3,
                 "name": "כאן",
                 "item": "https://www.kan.org.il/content/kan/"
             },
            
             {
                 "@type": "ListItem",
                 "position": 4,
                 "name": "כאן 11",
                 "item": "https://www.kan.org.il/content/kan/kan-11/"
             },
            
             {
                 "@type": "ListItem",
                 "position": 5,
                 "name": "מנאייכ",
                 "item": "https://www.kan.org.il/content/kan/kan-11/p-12394/"
             },
            
             {
                 "@type": "ListItem",
                 "position": 6,
                 "name": "עונה 3",
                 "item": "https://www.kan.org.il/content/kan/kan-11/p-12394/s3/"
             },
                        {             
                 "@type": "ListItem",
                 "position": 7,
                 "name": "מנאייכ עונה 3 | פרק 1"
            }
          ]
        }
    </script>`

**Comment by Fishenzon** [comment]
תוקן בגירסה 3.5.5

**Comment by rafi-d** [comment]
קצת OFF, אבל אם תנסה לסדר את התוכניות לפי א-ב, תראה מייד את הבעיה של תוכניות P-XXX שנמצאות בראש הרשימה (במשך כשני דפים)* ולא מזוהות עדיין.

**Comment by Fishenzon** [comment]
סודר
