### ISSUE TITLE
עידן פלוס ערוץ 12 וכל ערוצי וי או די תקלה כבר כשבוע 

### ISSUE THREAD

**Issue by taxi4u** [Fishenzon/repo#195]
תקלה שנמשכת כבר שבוע בכל הפלטפורמות אנדרואיד,ווינדוס 10 ו 11
ערוץ 12 לא נפתח וי או די לא מתפקד בכלל
מצאתי דרך שמאפשרת פתיחה של ערוץ 12ע"י ריסט של עידן פלוס לברירת מחדל אך לאחר שיוצאים מ 12 ורוצים לחזור הוא לא נפתח שוב וצריך את אותו תהליך כדי לפתוח אותו .

**Comment by tzagim** [comment]
https://github.com/Fishenzon/repo/issues/194#issuecomment-2105926858

**Comment by Fishenzon** [comment]
תודה.
נסו את גירסה 5.3.8
