### ISSUE TITLE
עידן פלוס לא נפתח חוץ מערוץ 13התקלה נמשכת 

### ISSUE THREAD

**Issue by taxi4u** [Fishenzon/repo#196]
גם לאחר שינוי מס מזהה מכשיר מאקו עדיין התקלה קיימת  הבעיה קיימת עם ערוצים 11-12-24 כל ערוצי הרדיו VOD פשוט כל פעם צריך לאפס את ההגדרות ולצאת מהקודי ולהיכנס שוב ואז 12 עולה עד למעבר לערוץ אחר ושוב כלום לא עובד 
מקווה יימצא פתרון

**Comment by rafi-d** [comment]
הבנתי מה כן עובד אצלי... רק בסטרימר עם אנדרואידtv 11 עליו... 

בסטרימר אנדרואיד 9 וחלונות - לא עובד.
עוזר למצוא מעקף?

**Comment by taxi4u** [comment]
אפשר לעקוף זמנית . כנס לעידן פלוס הגדרות .בחר בברירת מחדל תאשר את השינוי ולחץ אישור .לאחר מכן צא לגמרי מהקודי .כנס חזרה והערוצים יעבדו עד לפעם הבאה שתצא מצורפים צילומי מסך 
![IMG_20240512_133616](https://github.com/Fishenzon/repo/assets/152781642/41271630-4257-4bf6-9b00-09a4218dfc27)
![IMG_20240512_133659](https://github.com/Fishenzon/repo/assets/152781642/fcc35f8e-c3b6-4b42-9e04-41c7f30c53d7)

**Comment by rafi-d** [comment]
תודה, ההצעה לא פרקטית. תחשוב איך מנצלים את המיידע לשנות agent בקוד?

**Comment by Fishenzon** [comment]
תודה.
נסו את גירסה 5.3.8

**Comment by taxi4u** [comment]
אחי אתה אלוף האלופים !!!! אכן עדכון לגרסה. 3.5.8 פותר את כל הבעיות כל הערוצים חזרו לתפקד כרגיל
