### ISSUE TITLE
בקשה: להוספת פונקציית חיפוש ל VOD

### ISSUE THREAD

**Issue by leorg99** [Fishenzon/repo#197]
האם ניתן להוסיף פונקציית חיפוש ל VOD? 
למשל, [קשת 12](https://www.mako.co.il/mako-vod-index) תאפשר לחפש תוכניות , מה שייקל משמעותית על מציאת תכניות מיוחדות ששודרו, שהן לא  חלק מהתוכניות הרגילות.

**Comment by rafi-d** [comment]
יש כבר, זו פונקציה קיימת בקודי... אתה נכנס ל'כל התוכניות,' פותח את הפאנל השמאלי , לוחץ filter ומכניס כמה אותיות מהשם.

חוצמזה, לתוכניות יש אופציה למיון  אלפבתי, אז לא בעיה לחפש...

**Comment by tzagim** [comment]
אמממ, האמת שחשבתי לכתוב על נושא החיפוש בעצמי.
הבעיה שניתן לחפש רק בהיפוך סדר האותיות, "עצמאות" לא ימצא דבר אך "תואמצע" ימצא את התוכניות הכוללת את המילה עצמאות.

@Fishenzon

**Comment by rafi-d** [comment]
> אמממ, האמת שחשבתי לכתוב על נושא החיפוש בעצמי. הבעיה שניתן לחפש רק בהיפוך סדר האותיות, "עצמאות" לא ימצא דבר אך "תואמצע" ימצא את התוכניות הכוללת את המילה עצמאות.
> 
> @Fishenzon

לא נראה לי שזה קשור לתוסף, אלא להתקנת/שימוש  קודי שלך... 
אצלי זה עובד מעולה (VJKUBU,. למדתי שאסור להשתמש בדיאלוג העריכה שלהם ב WINDOWS (אולי אז הופך), אלא פשוט להקיש את האותיות רגיל (לא הפוך) בפילטר. זה הכי פשוט לתפעול גם.
באנדרואיד עובד גם עם הדיאלוג (עברית).

![image](https://github.com/Fishenzon/repo/assets/2458280/730b06ed-32e8-43f2-b183-4737cb9daea1)

**Comment by tzagim** [comment]
> באנדרואיד עובד גם עם הדיאלוג (עברית).

בדקתי במספר התקני אנדרואיד, בכולם הוא מצליח רק כאשר הופכים את האותיות.

**Comment by rafi-d** [comment]
שכחת לכתוב  "אצלי".... :) כנראה משהו שונה אצלך בהגדרות המערכת.
(אגב, אצלי זה 20.5 על  ATV, simboxtv) לא בדקתי על האנדרואיד הרגיל שלי, השימוש שם לא רב...)

**Comment by tzagim** [comment]
> כל הממשקים לקודי - באנגלית

רגע, אולי עלית על משהו, כל הממשקים שבדקתי היו בעברית...

**Comment by rafi-d** [comment]
בקיתור, תקנה מיני מקלדת פיסית... ב6$ ...
