### ISSUE TITLE
No links for VOD

### ISSUE THREAD

**Issue by asilverman** [Fishenzon/repo#199]
When I look in the VOD section it will list the VoD channels but no links are available
please help ❤️

using version 3.5.9

**Comment by rafi-d** [comment]
Which channel, all of them? From abroad?

**Comment by asilverman** [comment]
I am seeing in all channels, it's from abroad (US). Also specifically with chan12

**Comment by rafi-d** [comment]
12 is real, the rest is goe-location blocking, try with using a VPN (with IL server) ...

**Comment by omegavegas1313** [comment]
Which VPN are you all using?  I'm in the u.s. as well.

**Comment by rafi-d** [comment]
My VPN does not support server(s) in Israel...Search google for anyone that gives you free trial, and confirm if resolves your issue first.

**Comment by asilverman** [comment]
> Which VPN are you all using?  I'm in the u.s. as well.  

Surf shark

**Comment by omegavegas1313** [comment]
I used NordVPN in the past, specifically for Kan11, it does work; impressive layout, but at times slow & stutters.  Its not as good as a direct connection.   I heard good things about Surf Shark as a vpn, how smooth is it as for ch11 & 12?    BTW, why is there a geoblock?  kan11 youtube channel also has a geoblock, very frustrating.  You would think they would want to unite all of us no matter where we are.

**Comment by rafi-d** [comment]
Geo block is usually related to limitation of the content they buy/rent. Like rights to broadcast the Euro games limited to local viewers only.

**Comment by omegavegas1313** [comment]
Thanks for the info rafi-d, I'll look into it.  As far as the geo-block, if its Eurovision, sports game etc, I understand.  But to watch nostalgic shows from the 70s and 80s, education videos that teach English for example in the Kan youtube education channel, some of which are in black & white, where is the sense in that?  In the beginning they had lots of views, now its a graveyard. They should drop the geoblock and let the rest of us that are spread worldwide watch it.  It would also unite us and bring us closer.

**Comment by rafi-d** [comment]
Leaving Zionism asdide, Do you know of any other country BC service online service  that is open world wide? I don't.
Practically speaking, there is no "us" , it is the whole world ..  I imagine they (and us, taxpayers) should invest more in their site-server to support the extra load. Maybe a kind of paid subscription service for local material  can work...

**Comment by omegavegas1313** [comment]
Very good point rafi-d.  There are many of us who would be more than happy to pay a monthly fee to get these channels.  I tried screen.il and it was just limited in content.  Why pay a vpn when you can pay directly and support Israel at the same time.

**Comment by rafi-d** [comment]
I guess the "demand" for this is low, so not worth for them (all ISPs) to invest... 
There are couple of other alternatives you can try - 
1.  https://gurutv.online (and a more limited app - https://play.google.com/store/apps/details?id=com.gurugurutv.israel ) 
2.  the Kodi Idanplus addon - https://github.com/Fishenzon/repo/tree/master/zips/plugin.video.idanplus (includes all VODs as well!...) 
3.

**Comment by omegavegas1313** [comment]
> Yes started with latest version. I am seeing in all channels, it's from abroad (US). Also specifically with chan12

@asilverman are you able to view ch12 Live TV and VOD via surfshark vpn?  I'm considering getting it.  Ch12 at the moment works 1/4 of the times from the u.s.

**Comment by rafi-d** [comment]
> > Yes started with latest version. I am seeing in all channels, it's from abroad (US). Also specifically with chan12
> 
> @asilverman are you able to view ch12 Live TV and VOD via surfshark vpn? I'm considering getting it. Ch12 at the moment works 1/4 of the times from the u.s.

I am seeing the same thing (12 vod) here . This is not abroad ... Happening only from time to time. I have tried to disable IPV6 in the router, which seems to improve the situation, but I am not sure if it solves it...

**Comment by omegavegas1313** [comment]
Thanks Rafi-d, I'll try your suggestions.  Would different Kodi versions; 19, 20 vs 21 make any difference?  I recall for different plug-ins that people continue to use kodi 19.

**Comment by rafi-d** [comment]
No, I see it on both  19.5 and 20.2 . It's a new bug...

**Comment by omegavegas1313** [comment]
I was thinking about that.  Where can I find  the previous version?

**Comment by omegavegas1313** [comment]
Update:  Disable and Enable seem to work so far :-)  Good detective work Rafi

**Comment by rafi-d** [comment]
I can assure you - it will not be for long... ;P It's a WA... 
[plugin.video.idanplus_538.zip](https://github.com/user-attachments/files/15887135/plugin.video.idanplus_538.zip)

**Comment by omegavegas1313** [comment]
Have you ever tried to play the same show at the same time from two different devices, where it works on one and not the other?  Or same show same time from two different locations?   Maybe this will give a further clue of what the issue is.

**Comment by rafi-d** [comment]
Nope,  no real  need...

**Comment by omegavegas1313** [comment]
I did try it, it made no difference.  It goes by individual device.  The disable/enable works most of the time, good enough for me.  Rafi, are you part of the Idan team or just an advance user helping others?

**Comment by rafi-d** [comment]
Not part of any team ... Just a long time user...
