### ISSUE TITLE
need your help please

### ISSUE THREAD

**Issue by ebs111** [Fishenzon/repo#2]
http://player.kan.org.il/player/?stream=vod&account=ipbc&is_mms=true&medias[0]=ipbc-y6F2C1-TkEs&width=100%25&height=100%25&font_size=10&style_schema=ipbc&fullScreen=true&showEmbedded&qualityChange

Hi.
i just writen an addon to the new kan.
most of the links are youtube.
but some are not and i cannot resolve them can you help?
For example

**Comment by ebs111** [comment]
Thanks alot

**Comment by Fishenzon** [comment]
Hi @ebs111.
1. 
Take the 'metadataURL' url from the response, for example:
var metadataURL = 'http://player.kan.org.il/vod/vod/ipbc-y6F2C1-TkEs/hls/metadata.xml?smil_profile=default&';

2.
Get the response from the url from step 1,
From the response choose the url from "SmilURL" or one of "FileURL" (if you want to choose quality manually).

3.
In the new url, replace the domain (ipbc-s.vidnt.com) with the IP in <Server priority="1">.

4.
Play the final url.
for example:
http://62.90.90.44/ipbc_vod/_definst_/smil:ipbc-y6F2C1-TkEs.smil/playlist.m3u8?ttl=1508907520&amp;cdn_token=feb080bd9c86a11569e79ec021838f1f

**Comment by ebs111** [comment]
Hi, thank you so much for your help. Its working now.
Need your help with another site. I canr seem to get the html from it, can you help?
The site is
http://www.bali-perek.com
Why wont you join the telegram group?
Thanks for your help
