### ISSUE TITLE
רענון ידני ? תוכן לא עדכני ברדיו?  

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#20]
נתקלתי בבעיה מוזרה: כאן ב-תוכניות ב23:00
תוכנית למשל - "זה מגיע לכם" משודרת ב19:00
המבחר כלל תוכניות עד אתמול. בדקתי באתר, והתוכנית העכשוית מהיום כבר היתה שם.
לצערי, גם יציעה וכנוסה מהתוסף או אף מקודי לא עזרה לרענן
מציע לבדוק אם אין בעיה של CACHE 
או סיבה אחרת, כי חשוב שיהיה את כל המבחר העדכני מהאתר (במקרה הזה האתר די טוב העדכטו - שעה אחורה.

אשמח אם יהיה פתרון אוטומטי, אן אם לא - אופציה לרענון ידני עו בתפריט של כל תחנה, או התפריט הראשי.

תודה

**Comment by Fishenzon** [comment]
@rafi-d 
תודה. 
היה שינוי באתר.
תבדוק את גירסה 1.8.8

**Comment by rafi-d** [comment]
כיצד אמורה להיות ההתנהגות כשהתוסף פתוח ונוספה תוכנית תוך כדי?
מתי תתווסף לרשימת התוכניות כשאתה כבר בתוכה?
