### ISSUE TITLE
Keshet, Mako, Channel12 issues && N12 alternative or addition

### ISSUE THREAD

**Issue by x9t9** [Fishenzon/repo#204]
Great Job @Fishenzon  on this addon, seriously, been using that for years.
With all the frequent changes with the IL channels web structure and Streams, it is not easy to followup.
Anyhow in the last 2-3 month I have noticed that _Channel12_ ( Keshet) has started to make some issues, and finally about a month ago it totally stopped working. 

First appeared on :
- LibreELECT 9
- Kodi 18.1
- on RPI 3
- Plugin version v3.5.6 ( which was somewhat working sporadically, maybe from some cache ) and  than all the way up to v3.6.0. 

Two days ago I thought that it might be the old kodi / LibreELECT versions so installed a new one 

- LibreELECT 12
- Kodi 21
- on RPI 4 
- Plugin version v3.6.0.  updated both manually from here and from repo ( kodi UI ) 

Both were tryied with multiple VPN configs, multiple servers both inside IL and outside, and multiple different IP's
To no avail.

Some issues occur mainly :
Ch12 VOD list is now empty [ similar to #199 probably ]
Ch12 IPTV stream is "dropped" without even trying to connect, seems almost like an instant crash of some process ( I did not trace the whole stack / netwrok / sources or processes )

I have noticed new Settings for "Mako" [ "שם משתמש". "סיסמא" . "מזהה מכשיר" ] - which are empty by default 
( I do remember the DID was there before in some earlier versions ) so I assume that it MIGHT be part of the issue ? 
Are those mandatory now ?  [ if yes, maybe a small popup alert could be beneficial for users ] 

Also, browsing through the code, specifically `keshet.py` i have noticed that, just like before, the `baseUrl` refers to` *.mako.co.il` which makes sense for the VOD lists, but then it occured to me that a live Stream, or IPTV of the same channel exists openly also on the __`N12.co.il`__ website for each browser or user-agent to access [ several locations ] and that it might help solve the issue of this specific channel live stream assuming the issue is account base protected content. 
BTW same website which is only for NEWS related content, has also a VOD section. 

After all that, my question are very simple
1 - Anyone aware of the above issues with CH12 or is it only my own setup that is causing "private" issues ? [ see edit below ] 
2 - Are those only [ mako ] user accoutnt related ? User-agent ?
3 - Any other suggestions for debugging ?
4 - Can the IPTV stream of above mentioned N12 help to solve at least the Stream option [ or even maybe added as a "new" channel / resource or  "content" ?

Again, thanks for the continuos development, Great work indeed, especailly in those times. תודה

__Edit__
After writing all of that I saw #194 , #195, #196 etc, that were closed ( should have checked before ) i will try 3.5.8 and report, however I would leave the above written in regards to `N12 `suggestion [ Edit II - saw #121 maybe related  ]

**Comment by rafi-d** [comment]
3.6.0 works...

**Comment by x9t9** [comment]
@rafi-d  Thanks for the reply 
You mean 
>"disabling-enabling" it... 
Each time you use or view, or a single time cures all ?

**Comment by rafi-d** [comment]
One time, no restart. It Should be good for unknow # of Kodi runs... 
See https://github.com/Fishenzon/repo/issues/199

**Comment by x9t9** [comment]
@rafi-d 
Thanks again for prompt reply
Still not working for me. Nor does cleaning the cash manually [ right click "ניקו קאש"  both main menu and sub menu specific channels ] Nor returning to "Default" in settings.
I am yet to try the 3.5.8 suggested in that thread.

**Comment by rafi-d** [comment]
Best check their website, see if you are not Geo blocked.

**Comment by x9t9** [comment]
Nope, no geoblock I have also mentioned in OP that I have tried different locations ( both inside IL and outside )  different devices and different VPN servers.

**Comment by rafi-d** [comment]
> Best check their website, see if you are not Geo blocked.

Which direct  link / website have you tried successfully? Geo blocking is the most likely cause IMHO...

**Comment by x9t9** [comment]
It is indeed a likely cause, and this is also why I tried in israel itself, and also with VPNs located in israel, and the regular websites and streams on normal browser at *mako.co.il etc ( which works )

**Comment by x9t9** [comment]
@rafi-d 
In relation to above message - Example of a working stream 

`https://www.mako.co.il/AjaxPage?jspName=embedHTML5video.jsp&galleryChannelId=7c5076a9b8757810VgnVCM100000700a10acRCRD&videoChannelId=d1d6f5dfc8517810VgnVCM100000700a10acRCRD&vcmid=1e2258089b67f510VgnVCM2000002a0c10acRCRD `

The vcmid or others might need different signatures 


![image](https://github.com/user-attachments/assets/9315f7b7-d8b9-444c-91b1-99a980a36a8e)



@Fishenzon might also want ot look into this as an alternative ..

**Comment by rafi-d** [comment]
Just FYI, the second live link for Keshet is not working locally either...

**Comment by x9t9** [comment]
> Just FYI, the second live link for Keshet is not working locally either...__
Not sure I understand what is refered to as a "Second" live link, you mean inside the idan+ add-on ? 

Iam attaching a video, look at the link posted [here ](https://github.com/Fishenzon/repo/issues/204#issuecomment-2238160667)
Is that stream working for you ?
For me yes, so geoblocking is not applied here for sure.
screenshots 
![image](https://github.com/user-attachments/assets/412bf7df-cb76-4b45-a07d-4c9b613de8f5)



https://github.com/user-attachments/assets/33c907e6-a3d8-4b5e-9150-fa6381678711

com/user-attachments/assets/bd0f93bd-3dcd-4aaf-b86e-f53aeaa8e1c4)


Atatched clip screenscast from NOW Live.

**Comment by rafi-d** [comment]
Looks Ok to me..

**Comment by x9t9** [comment]
I am working on a CLEAN install now, only add-on that is istalled is this one we are talking about.
For me - BOTH are not working, like described on the OP. 
after a LOT of trial and error and clicking and cache cleaning, a SINLE time happened taht suddenly i saw the "FOLDERS" list of CH12 VOD -  but empty - which also those disappeared after the next try to access same list.
Again, I did not traced everything, for now just trying to understand if the issue is wrong stream links ( that were ok in the past but now restricted ) or something else.

**Comment by rafi-d** [comment]
PS: this is on ver. 20.5 , not 21 ...

**Comment by x9t9** [comment]
I have here 18.1, 19, 21 - all same behaviour. 
BTW I am on PI / LibreELEC, not android, now win.
I guess you are on Win ?

**Comment by rafi-d** [comment]
Both, Win10 and android/ATV

**Comment by Orel-A** [comment]
Yes, channel 12 has stopped working also in MediaBoxIL app. But with XDBox app it's working...

**Comment by rafi-d** [comment]
Just a longshot: disable IPv6 in your router/LAN , see if that have any impact...

**Comment by leorg99** [comment]
Keshet 12 isn't playing for me either @Fishenzon . Stopped working today.

**Comment by tzagim** [comment]
חזר לפעול, כנראה תקלה מטופשת בסדרת התקלות באתר הזה.
מישהו צריך להסביר להם שלא מעלים לפרודקשן ביום חמישי....
ובכלל כדאי לבדוק לפני שעושים שינויים.

**Comment by leorg99** [comment]
This is the [error](https://github.com/user-attachments/files/16322752/kodi.log) I get when trying to watch keshet 12.

**Comment by rafi-d** [comment]
> This is the [error](https://github.com/user-attachments/files/16322752/kodi.log) I get when trying to watch keshet 12.

Log wasn't taken in debug mode... 
Regardless, if there is no Geo block (you are using IL IP) try with default settings or uninstall + clear data and reinstall.

**Comment by x9t9** [comment]
@leorg99 can you take a log in DEBUG mode ?

As per [Kodi wiki](https://kodi.wiki/view/Log_file/Easy#Steps) :

Enable the setting Enable debug logging in the settings page located at [Settings > System Settings > Logging](https://kodi.wiki/view/Settings/System/Logging#Debug)
Pressing ctrl+⇧ Shift+d on a keyboard
Create an entry in the [advancedsettings.xml](https://kodi.wiki/view/Advancedsettings.xml#loglevel) file. See: [Advanced Method](https://kodi.wiki/view/Log_file/Advanced)

**Comment by leorg99** [comment]
@x9t9 It is working again. Thanks for your help!

**Comment by x9t9** [comment]
@leorg99 I did absolutley nothing to help, and for me personally the situation is actually the same.

**Comment by adieldar** [comment]
I have the same problem - קשת 12 - in live tv works normally but whenever commercials cycle starts it's frozen for most of the commercials, just few seconds before they finish the streaming returns but with unsynchronized sound and video that is stuck for 1-2 seconds every ~10 sec. If I stop the channel and start it again everything is fine until the next commercials. I'm running on Firestick 4k and latest addon 3.6.2. I used Nexus and few days ago updated to latest Omega, same issue persists. I tried to alter advanced settings and increased read factor to x10, x15 it doesn't help.

**Comment by Fishenzon** [comment]
> @rafi-d In relation to above message - Example of a working stream
> 
> `https://www.mako.co.il/AjaxPage?jspName=embedHTML5video.jsp&galleryChannelId=7c5076a9b8757810VgnVCM100000700a10acRCRD&videoChannelId=d1d6f5dfc8517810VgnVCM100000700a10acRCRD&vcmid=1e2258089b67f510VgnVCM2000002a0c10acRCRD `
> 
> The vcmid or others might need different signatures
> 
> ![image](https://private-user-images.githubusercontent.com/23067248/350239004-9315f7b7-d8b9-444c-91b1-99a980a36a8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDE3OTUsIm5iZiI6MTczMTMwMTQ5NSwicGF0aCI6Ii8yMzA2NzI0OC8zNTAyMzkwMDQtOTMxNWY3YjctZDhiOS00NDRjLTkxYjEtOTlhOTgwYTM2YThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA1MDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNjExZGExOGQ0MTU2MGZhNzU1ZDFiNGI2MDViZjIwM2U0YzNlOTg3MTY3ZWViYWViOWY2ZmVkYTFiNWJiNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n_eJUht52x8XiiNElSxbQu0Oq-ou1mqL2jvxVAq-THk)
> 
> @Fishenzon might also want ot look into this as an alternative ..

בוקר טוב.
תודה, המקור נוסף לפני כמה גירסאות

**Comment by peaceful108** [comment]
שלום לכולם, 
מישהו יכול לשתף לינק m3u8 פעיל לערוץ קשת 12?

**Comment by rafi-d** [comment]
> שלום לכולם, מישהו יכול לשתף לינק m3u8 פעיל לערוץ קשת 12?

הכוונה להפעלה דרך התוסף ב LIVE TV ?  התוסף מוציא לך רשימה כזו בעצמו

**Comment by peaceful108** [comment]
> > שלום לכולם, מישהו יכול לשתף לינק m3u8 פעיל לערוץ קשת 12?
> 
> הכוונה להפעלה דרך התוסף ב LIVE TV ? התוסף מוציא לך רשימה כזו בעצמו

היי רפי, תודה על תשובתך. 
אני רוצה לצפות בשידורי הערוצים הישראליים על טלוויזית סמסונג בעזרת אפליקציית TVapp
https://github.com/KaashDev/TVapp

לצורך כך, אני צריך את לינק ה- m3u8 המלא (כולל תחילית https://...).


הבעיה היא, שבעמוד שמפרט את לינקים הערוצים בתוסף Fishenzon מופיע לינק לערוץ 12 בלי התחילית.

<img width="527" height="225" alt="Image" src="https://github.com/user-attachments/assets/0658e088-451a-40f2-b384-268384de9795" />
