### ISSUE TITLE
VOD בעיות עם רשת 13 

### ISSUE THREAD

**Issue by leorg99** [Fishenzon/repo#205]
I am not able to play any episodes of בלקספייס. 
Is this a known issue?
Using it outside of Israel - in the US.

**Comment by rafi-d** [comment]
No issues here (also with US vpn).
Try the W/A mentioned in #199 (disable+re-enable the addon).

**Comment by leorg99** [comment]
I am trying it from three different places (my house, my parents house, friends house). Cannot get it to work. I disabled/enabled the addon. Also tried with a complete new install of Kodi on my PC, doesn't work. Logs attached.

[kodi.log](https://github.com/user-attachments/files/16354270/kodi.log)

**Comment by Fishenzon** [comment]
צהרים טובים.
חזרתי מחופשה בחו"ל וגם לי לא עבד שם בלקספייס.
הפעלתי NordVPN עם שרת בישראל וזה עבד לי.
