### ISSUE TITLE
ערוץ 14 לא עולה כבר כמה ימים 

### ISSUE THREAD

**Issue by taxi4u** [Fishenzon/repo#206]
בעיות ערוץ 14 לא עולה בכלל כבר כמה ימים

**Comment by leorg99** [comment]
same here - working in mediabox.

**Comment by taxi4u** [comment]
Hey , i found an easy way to get it back to Kodi i opened channel 14 live
via ytube than i add it to Kodi's favourites & play it from there smooth &
easy

בתאריך יום ב׳, 29 ביולי 2024, 0:39, מאת Leor Greenberger ‏<
***@***.***>:

**Comment by leorg99** [comment]
oh very nice trick! i didn't know it streams on youtube.

**Comment by Fishenzon** [comment]
צהרים טובים.
חזרתי מחופשה והוצאתי את גירסה 3.6.1
ערוץ 14 אמור לעבוד עכשיו

**Comment by taxi4u** [comment]
אין מה לומר ...אלוף האלופים .תודה  באותה נשימה שאלה : אני גר בחו"ל וכבר
שנים  הקודי זה הערוץ היחידי שלי לקבל מידע על ישראל בזמן אמת .פעם הייתי
מצליח להיכנס לוי או די בכל בערוצים 11-12-13 היום רק ערוץ 12 מאפשר לנו וי או
די האם יש דרך או תיקון לזה ? תודה מראש על כל מה שאתה עושה

בתאריך יום ד׳, 31 ביולי 2024, 14:34, מאת fishenzon ‏<
***@***.***>:

**Comment by rafi-d** [comment]
תשתמש בVPN עם שרת בארץ...

**Comment by taxi4u** [comment]
אני מצליח להשתמש ב  vpn דרך הדפדפן אבל אין לי מושג איך להתקין אותו קבוע על
הקודי

בתאריך יום ה׳, 1 באוג׳ 2024, 14:39, מאת rafi-d ***@***.***>:

**Comment by Fishenzon** [comment]
ההרחבה מנגנת מה שיש באתרים. אם יש חסימה גאוגרפית זה לא בשליטתי.

**Comment by taxi4u** [comment]
כרגע הכל עובד 11-12-13-14
Vod -12


בתאריך יום ד׳, 14 באוג׳ 2024, 17:36, מאת fishenzon ‏<
***@***.***>:

**Comment by taxi4u** [comment]
Great!

בתאריך יום ה׳, 15 באוג׳ 2024, 8:08, מאת fishenzon ***@***.***
