### ISSUE TITLE
בעיה בערוץ 14

### ISSUE THREAD

**Issue by shahaf1122** [Fishenzon/repo#209]
שלום,
מה שלומך?
קודם כל תודה על ההרחבה, שמתי לב לכמה דברים שיש בעיה עליהם.
בערוץ 14 יש בעיה בלייב. הקישור של הלייב השתנה. זה הקישור החדש

 "https://ch14-channel14-content.akamaized.net/hls/live/2104807/CH14_CHANNEL14/master.m3u8"
 
נלקח מהAPI שלהם, אתה יכול להוסיף את הקוד לאיפה שהלייב נלקח.

import requests
url = "https://insight-api-channel14.univtec.com/cms/interface/channels/play?relations=true&filter=guid||$eq||b676b906-5625-48af-a331-11a5d22e151b"
headers = {
    "x-tenant-id": "channel14"
}
response = requests.get(url, headers=headers)
data = response.json()
print(data.get('vod').get('hlsMaster')) #live url

**Comment by Fishenzon** [comment]
תודה.
חזרתי מחופשה והוצאתי את גירסה 3.6.1
ערוץ 14 אמור לעבוד עכשיו
