### ISSUE TITLE
Vod

### ISSUE THREAD

**Issue by sawa1980** [Fishenzon/repo#21]
היי 
לא עובדת ההרחבה של ערוץ 10 ושל מאקו בבילד פינומינל של כמיליון . 
לטיפולך

**Comment by Fishenzon** [comment]
@sawa1980 
אני לא יודע על מה אתה מדבר. אין הרחבה של ערוץ 10 ואין הרבה של מאקו.
יש הרחבה אחת שקוראים לה עידן פלוס והתכנים של ערוץ 10 ושל מאקו עובדים בה.
זה לא תלוי בבילד כזה או אחר.

הנה, גם קמיליון פנומנל עובד
![screenshot000](https://user-images.githubusercontent.com/29551534/48669676-2f483480-eb12-11e8-85f6-9a0f70f83752.png)
![screenshot001](https://user-images.githubusercontent.com/29551534/48669677-2f483480-eb12-11e8-9520-858dcf058f8e.png)
