### ISSUE TITLE
[Bug] Keshet VOD - Episodes don't play

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#210]
Keshet VOD - Episodes don't play

version 3.6.0

**Comment by Fishenzon** [comment]
צהרים טובים.
חזרתי מחופשה והוצאתי את גירסה 3.6.1
לא נתקלתי בבעיות בניגון, תבדוק אם זה עובד לך בגירסה הזאת.

**Comment by burekas7** [comment]
תודה! @Fishenzon 
עם 3.6.1 חזר לעבוד.
