### ISSUE TITLE
[Bug] Idan plus favorites list - Reshest Tv Shows

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#211]
Every time after I add a program to the Idan Plus favorites list, 
after a certain period when I enter the program through the Idan Plus favorites, 
I'm getting a menu with empty content.

version 3.6.0

**Comment by Fishenzon** [comment]
ראיתי את הבעיה.
זה קורה בגלל שינוי שעשיתי פעם בעקבות שינוי באתר.
אצטרך להדוק איו לשנות את זה.
אתה יכול לשמור בינתיים תכניות דרך האיזור של ארכיון רשת 13, שם זה ממשיך לעבוד כמו שהיה באתר הישן.

**Comment by Fishenzon** [comment]
תודה.
שיניתי את הפניה לסדרות של ערוץ 13.
צריך להוסיף מחדש למועדפים וזה אמור לעבוד עכשיו.

**Comment by burekas7** [comment]
@Fishenzon 
תודה.
אני אעדכן את הגרסה ואבדוק, 
בינתיים סוגר כאן ואם יהיו בעיות בעתיד אני אפתח מחדש בעת הצורך.
