### ISSUE TITLE
בעיה בVOD  13

### ISSUE THREAD

**Issue by shahaf1122** [Fishenzon/repo#213]
היי,
מה קורה?
שמתי לב שאין את הסידרה ווארט בסדרות בערוץ 13. הסתכלתי על הקוד והבנתי מה הבעיה, בכללי 13 עברו לAPI אחר מאז האפליקציה שלהם ולכן הקישור לאתר איטרנט של ווראט לא רשום
כלומר הוא URL = ''

{'id': '613', 'poster': 'https://media.reshet.tv/image/upload/v1715157765/uploads/2024/904047991.jpg', 'url': '', 'title': 'ווארט'}

ושמתי לב שבקוד ברגע של URL הוא ריק אז זה מדלג עליו בפונקציה (GetSeriesList(url, iconimage))

if serie['url'] == "":
					continue

אם תוכל אולי להוסיף תנאי לפני זה שבעצם יבדוק אם זה ווראט ואז לא ידלג על זה

if serie['title'] == "ווארט":
					serie['url'] = '/all-shows/vort/'
					
בדקתי וזה עובד, זה הקישור לאתר איטרנט.
או אם אתה מעדיף לפי ID אז הוא 613.

if serie['id'] == "613":
serie['url'] = '/all-shows/vort/'

**Comment by Fishenzon** [comment]
תודה.
עד שאסתכל על זה, אפשר להיכנס לסידרה בינתיים דרך VOD - רשת 13 - ארכיון רשת 13

**Comment by Fishenzon** [comment]
תודה.
הוספתי את התכנית
