### ISSUE TITLE
ערוץ 11 וי.או.די - לא מציג תמונות

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#218]
ב-VOD של ערוץ 11 אין תמונות בתפריט כשעוברים על התוכניות וגם בתוכן.
רלוונטי לגרסה הנוכחית 3.6.3 אבל התחיל כבר בגרסה קודמת.

**Comment by tzagim** [comment]
היי @burekas7 
התמונות קיימות, רק שהן טוענות מעט לאט.
אגב, גם הטקסט נטען לאט, כך שסביר שמדובר במשהו בקוד שאולי ניתן לתיקון.

**Comment by burekas7** [comment]
@tzagim 
העניין הוא שקודי לא מרענן את התפריט שוב כשהתמונות עלו.
מופיעה רשימה התוכניות אבל כשעומדים על התוכנית התמונה לא מופיעה.
בעבר זה כן היה עובד טוב, אולי הם שינו שם משהו.

**Comment by tzagim** [comment]
@burekas7 
תיקון מהיר.
תצא מקודי ותמחק את הקובץ הבא: Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.idanplus/kanSeries.json
בכניסה הבאה לקודי הקובץ ירד מחדש, ייתכן וזה יפתור את הבעיה.

**Comment by burekas7** [comment]
@tzagim 
הקובץ אכן ירד מחדש, אבל עדיין אותה בעיה.
במעבר על התוכניות לא מוצגת התמונה של כל תוכנית.

**Comment by rafi-d** [comment]
נכון שזה לוקח שניה או שתיים, אבל המונות כן מוצגות אצלי על כל תוכנית וכל פרק (שם בצהוב). 

שמות של קטגוריות ( בטקסט לבן) לא. מרגיש כאילו קודי לא שומר תמונות בראש אולי.. 

סטרימר אנדרואיד tv חזק, קןדי  22.1

**Comment by Fishenzon** [comment]
צהרים טובים.
התמונות לא יורדות בגלל הגנה של cloudflare.
הוספתי בהגדרות של ההרחבה בלשונית של "כאן11" אפשרות לאפשר שמירה מקומית של התמונות.
יש שם גם אפשרות למחוק את התמונות.
בפעם הראשונה שנכנסים לקטגוריה עם רשימה ארוכה, יכול לקחת זמן לתמונות לרדת אבל בפעם הבאה זה כבר עובד מהר יותר כי רוב התמונות כבר שמורות.

**Comment by tzagim** [comment]
ייתכן שייפתר על ידי #221

**Comment by Fishenzon** [comment]
תודה רבה.
נא לבדוק בגירסה 3.6.6.
**אין** צורך לשנות בהגדרות של ההרחבה לשמור מקומית את התמונות.

**Comment by burekas7** [comment]
נבדק עם 3.6.7 ועכשיו עובד מעולה!
תודה לכל מי שעזר.
