### ISSUE TITLE
שגיאה בהגדרת תת שידור רשת - גרסה 3.6.4

### ISSUE THREAD

**Issue by tzagim** [Fishenzon/repo#220]
בקובץ resources/lib/baseChannels.py

בשורה [35-36](https://github.com/tzagim/plugin.video.idanplus/blob/main/plugin.video.idanplus/resources/lib/baseChannels.py#L35)
במקום:
```py
	{'ch':'ch_i24news', 'index': 20......}
	{'ch':'ch_i24news', 'index': 20.....}
```

צריך להיות:

```py
	{'ch':'ch_13nofesh', 'index': 20......}
	{'ch':'ch_13reality', 'index': 20.....}
```

**תודה על ההרחבה הנהדרת.**

אגב, לא ניתן למשוך את פירוט הסדרות של כאן דרך ה-json (או שמא מהסקריפט שהמתכנת שלהם מחבב משום מה) שהאפלקציה מושכת את הנתונים?
מהסקריפט באתר מורכב למשוך מכיוון שנראה שיש להם cloadflare או מתווך קשוח אחר, וגם כי השמות היום אמורות להיות מקושרות לתיאור התמונה (name = ImageAlt) ואין לכל התמונות...
התבנית המתאימה היא:
```py
digitalSeries:\s*\[(.*?)\]
```

**Comment by Fishenzon** [comment]
תודה, תוקן בגירסה 3.6.5
לא בדקתי מה קורה באפליקציה, אני מסתמך על האתר.
בחלק מהדפים יש json ובחלק אין.

**Comment by tzagim** [comment]
ראה את #221 
בעצם לחקות את הדרך שבה האפליקציה מקבלת את המידע......
