### ISSUE TITLE
פתרון לשלל בעיות כאן 11

### ISSUE THREAD

**Issue by tzagim** [Fishenzon/repo#221]
עם קצת מאמץ מצאתי דרך למשוך את המידע מהאתר של התאגיד מבלי להזדקק לקבצי json ידניים או ידניים למחצה, פתרון זה יעזור גם לבעיית התמונות שלא יורדות בגלל ההגנה של cloudflare על האתר.

שים לב שה-API מוגבל ל-200 רשומות בכל פעם, לכן בכדי לקבל את נתוני כאן 11 נדרשות 3 קריאות לפחות.

* [חינוכית קטנטנים](https://mobapi.kan.org.il/api/mobile/subClass?from=1&id=4462)
* [חינוכית ילדים ונוער](https://mobapi.kan.org.il/api/mobile/subClass?from=1&id=4453)
* [דיגיטל](https://mobapi.kan.org.il/api/mobile/subClass?from=1&id=4464)
* [כאן 11 (1/3)](https://mobapi.kan.org.il/api/mobile/subClass?from=1&id=4444)
* [כאן 11 (2/3)](https://mobapi.kan.org.il/api/mobile/subClass?from=201&id=4444)
* [כאן 11 (3/3)](https://mobapi.kan.org.il/api/mobile/subClass?from=401&id=4444)

יישמתי את זה אצלי בקובץ פייתון שרץ יומית.

בכדי לחסוך לך טרחה אציין כאן את הבעיות שנתקלתי בהן ואת הפתרון:
1. צריך להסיר את קישור הבסיס מהקישור לתמונה או להתאים את kan.py בהתאמה, (ניתן לקרוא את התמונה גם עם www, אך ייתכן שהגנת cloudflare תפריע מעט).
2. כדאי להסיר את הסיומת של הקישור לתוכנית, הוא מסתיים ב`?app=true`.
3. מתוך מאות התוכניות לכ-5 מהם (נכון למועד כתיבת השורות) `description = null`, (אפשר פשוט לשים את הכותרת במקרה כזה או למשוך מקובץ שיהיה בו רק ה"תקולים").
4. עדיף לקחת את התמונה הרביעית (מבחינת הגודל והעיצוב), במקרי קצה שאין אותה כדאי לקחת את תמונה 2

ואפשר כמה רעיונות קדימה..
1. להוריד גם את הפוסטר וגם את הרקע מהקישור, ולהציג אותם לעיצוב נעים יותר.
2. בדיקה יומית או תלת שבועית של עדכוני סדרות מהקישורים, ו/או כאשר הוא נתקל בקישור שאינו מופיע ב-json הוא יוריד מחדש את הקובץ ויעדכן בהתאם את הרשימה.

**Comment by Fishenzon** [comment]
תודה.
השתמשתי בלינקים ושיניתי גם את הלינקים לתמונות בשאר הקטגוריות.
