### ISSUE TITLE
ערוצי המוסיקה של גלגלץ לא עובדים

### ISSUE THREAD

**Issue by eldadkd** [Fishenzon/repo#223]
תודה על ההרחבה המצויינת!
`סופשבוע רגוע` ו`גל עברי` לא מנגנים
אני עם קודי 21.1 (osmc 2024.8)
תודה

**Comment by Fishenzon** [comment]
צהרים טובים.
ניסיתי לנגן את הערוצים והם מתנגנים.
יכול להיות שהיתה תקלה זמנית?

**Comment by eldadkd** [comment]
היי 
מצטער על העיכוב בתגובה אבל זו לא תקלה זמנית. ניסיתי עוד כמה פעמים וזה עדיין לא עובד
יוכל להיות שזה קשור במערכת ההפעלה שעליה רץ הקודי? אני מריץ על רסברי פאי עם OSMC מעודכן.
אני אנסה להתקין קודי על המחשב (windows) ואבדוק

**Comment by eldadkd** [comment]
התקנתי מחדש את ההרחבה וזה עובד!
