### ISSUE TITLE
תחנות רדיו "מתות"...

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#23]
היום התחנות האלו אינו עובדות:
דרום
102FM
כאן הערבי השני
כאן נוסטלגי
כאן ים תיכוני

תוכל בבקשה לבדוק?

תודה

**Comment by Fishenzon** [comment]
@rafi-d 
יצאה גירסה עם תיקונים לתאימות לשינויים שנעשו באתר כאן.
לא ראיתי שום בעיה עם רדיו דרום ורדיו 102.
לאחר שהוצאתי גירסה ראיתי שיש בעיה עם רדיו 102 אילת, אוציא עדכון נוסף.

**Comment by MrTal** [comment]
@Fishenzon 
יש מצב אתה מוסיף גם את קול הים התיכון?
https://www.rlive.co.il/station/kol-hayam-hatichon

**Comment by rafi-d** [comment]
> @Fishenzon
> יש מצב אתה מוסיף גם את קול הים התיכון?
> https://www.rlive.co.il/station/kol-hayam-hatichon

יש מצב שתפריד בין בעיות לחידושים, ותפתח נושא נפרד (לנוחות המפתח) כפי שהעירו?...
לטעמי יש להתמקד במה שנתמך בעידן+ באוויר בעיקר, כי אין לזה סוף!

**Comment by MrTal** [comment]
@rafi-d 
ראיתי שיש כבר על רדיו אז לא רציתי להציף ולפתוח חדש בגלל תחנה אחת.
זה לא מספיק חשוב בשביל לפתוח חדש, זה סתם הצעה לייעול לשיקולו של המפתח
אז בכל אופן אתה מוזמן לנעול בעצמך את הפוסט.

**Comment by rafi-d** [comment]
@Fishenzon 
נראה הכל תקין כעת, פרט לערוץ הערבי השני . לא ממש חשוב...
תודה!

**Comment by Fishenzon** [comment]
@rafi-d 
התחנה הפרסית (ערוץ ערבי שני) לא פעילה כרגע באתר.

@MrTal 
התחנה תתוסף בעדכון הבא
