### ISSUE TITLE
ערוץ 24 לא עובד... 

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#24]

**Comment by Fishenzon** [comment]
@rafi-d 
אתה מוזמן לכתוב מכתב תלונה לאתר מאקו.
הערוץ לא משדר בו תקין כבר כמה ימים.

**Comment by rafi-d** [comment]
לא ידעתי

תודה

**Comment by Fishenzon** [comment]
@rafi-d 
בוקר טוב.
נראה שחזר לעבוד

**Comment by rafi-d** [comment]
720P בלבד?

**Comment by Fishenzon** [comment]
אין פה מה לתקן, אני מביא מה שיש באתר.
יש להם לכל רזולוציה 2 לינקים

**Comment by rafi-d** [comment]
OK תודה!

**Comment by rafi-d** [comment]
אגב, "האח הגדול" נראה לי לא רלונטי כעת..
וגם לא פועל...

**Comment by Fishenzon** [comment]
אמור לחזור ב-12.1, נראה אם יחזור באותה מתכונת או שנצטרך עדכון

**Comment by Fishenzon** [comment]
@rafi-d 
האח הגדול התחיל לשדר שקופית

**Comment by rafi-d** [comment]
אכן.... 
אגב, יש תכנון לערוץ 22 חדש (מתחרה לאח הגדול).  שווה לעקוב...

**Comment by rafi-d** [comment]
תודה על העידכון.
אגב, "רענון הרשימה" כעת אחד לפני הסוף. אחרי השינוי ...
אולי יהיה נוח יותר להעביר את "רענון הרשימה" לראשה...או גם לאחר הכפתורים בתפריט משמאל

**Comment by Fishenzon** [comment]
@rafi-d 
זה אצלך אחד לפני הסוף, כי נשמרו אצלך הגדרות מגירסה ישנה של ההרחבה.
אם אתה תבצע בהגדרות איפוס או שתתקין על קודי נקי, זה יהיה בסוף.
אתה יכול להזיז עמצאית (או להעלים) למיקום אחר דרך ההגדרות

**Comment by rafi-d** [comment]
תודה, ברור.

**Comment by rafi-d** [comment]
ערוץ 24 לא עובד , שוב...
