### ISSUE TITLE
 הוספה תוכנית של חברת החדשות

### ISSUE THREAD

**Issue by MrTal** [Fishenzon/repo#26]
שלום,
עכשיו אחרי המיזוג, רציתי לשאול אם יש אפשרות להוסיף להרחבה את התוכניות של חברת החדשות של קשת 12 שלא מופיעות בהרחבה:
https://www.mako.co.il/news-channel2?partner=BreadCrumbs

בנוסף לכך התכנים של חברת החדשות של רשת 13:
http://10tv.nana10.co.il/Category/?CategoryID=600340&sid=169&pid=58 (עריכה: לאחר בדיקה קיים, מופיע בארכיון)
https://www.10.tv/6amnonlevy
https://www.10.tv/barcodeshow
https://www.10.tv/jacobeilon
שגם לא מצאתי אותם בהרחבה
כמובן אם זה אפשרי מבחינה טכנית ולא מסובך וגם לא לוקח הרבה עבודה,
נתון לשיקולך המלא, תודה רבה מראש!

**Comment by MrTal** [comment]
@Fishenzon 
עדכון:
קשת התחילה לעלות את התכנים של חברת החדשות ל-MAKO TV:
http://prntscr.com/mezn0i

**Comment by Fishenzon** [comment]
@MrTal 
נוספו תוכניות של חדשות 13 לתוך ה-VOD של ערוץ 13

**Comment by MrTal** [comment]
@Fishenzon 
תודה רבה
שבוע טוב
