### ISSUE TITLE
ערוץ האח הגדול לייב

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#27]
היי,

רציתי לשאול איך אני משיג את הקישור הפעיל לערוץ האח הגדול לייב ברשת?
`https://reshet.tv/home/bb-livestream/`

הקישור הנוכחי הפסיק לעבוד:
`https://besttv512.aoslive.it.best-tv.com/egress/bhandler/reshet/bb01/chunklist_b3682304.m3u8|User-Agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36&Referer=http://reshet.tv/home/bb-livestream/`
(בעבר היה 511 במספר שם, אבל שינוי ל-512 עזר, עכשיו גם זה לא עובד)

תודה

**Comment by Fishenzon** [comment]
אני לוקח את הקישור כמו שהוא נוצר באתר.
תנסה לבדוק בקובץ לוג של קודי.

**Comment by burekas7** [comment]
הקישור שציינתי זה קישור שעבד תקופה ארוכה מאוד, בפעם הקודמת כשהפסיק, שיניתי את המספר ופתאום חזר לעבוד, אבל אז שוב הפסיק לעבוד (אומנם חזר לכמה שעות והפסיק שוב)

לא כל כך הבנתי "כפי שהוא נוצר באתר", איך מגיעים לקישור?
הדבר היחיד שמצאתי במקור הוא זה: http://reshet.tv/home/bb-livestream/
אגב גם הקישור לרשת הרגיל כפי שקיים בהרחבה מבוסס על besttv. 
איך מוצאים את הקישור המעודכן גם ללייב של האח הגדול?

תודה מראש
