### ISSUE TITLE
קובץ לוח שידורים לא נוצר בקודי 18 

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#28]
https://www.hometheater.co.il/vp2924961#2924961

**Comment by Fishenzon** [comment]
נוצר לי בפלאפון גם באנדרואיד.
אולי יש בעיה במכשירים מסויימים?

**Comment by rafi-d** [comment]
אולי, אין לי שמץ... 
אין לי 18 באנדרואיד, וכך דווח בפורום (בלינק)

**Comment by Fishenzon** [comment]
@rafi-d 
נסה שוב עם גירסה 2.0.2

**Comment by rafi-d** [comment]
OK ננסה בפורום

**Comment by rafi-d** [comment]
כעת קובצי IPTV   
 לא נוצרים ב17.6... 
 על WIN

התקנתי 18 במקביל כPORTABLE על WIN - שם נראה שנוצר 

בפורום מדווחים שעל 18 באנדרואיד עובד. FYI.

**Comment by Fishenzon** [comment]
@rafi-d 
הקובץ נוצר בסדר גמור בקודי 17, בדקתי עכשיו

**Comment by rafi-d** [comment]
צודק, נוצר
מה שקורה - שהבחירה של 
USE IPTV
נעלמה לה לאחר שדרוג הגרסה ולכן הוא לא נוצר...
אולי זו בעיה שצפציפית קורית בעת שידרוג גרסה?

אגב, נראה שערוץ 24  לא עובד, שוב... זה בתוסף או באתר?

**Comment by Fishenzon** [comment]
הבחירה לא אמורה להשתנות וזאת גם ברירת המחדל.
כנראה נלחץ לך בטעות.
ערוץ 24 לא עובד גם [באתר](https://www.mako.co.il/mako-vod-live-tv/VOD-b3480d2eff3fd31006.htm)
אולי זה קשור לזה שהערוץ נמכר מקשת לטלעד?
