### ISSUE TITLE
לוח שידורים ריק

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#29]
היי,
רציתי לברר אם ידועה בעיה עם נתוני לוח שידורים?
משום מה אין נתונים, וכשאני בודק את הקובץ
EPG.xml
אז אין בו מידע על התוכניות וכו'

גירסה 2.0.2
קודי 17.6
ווינדוס 10

תודה

**Comment by rafi-d** [comment]
גם כשאתה מיצר את הקובץ באופן יזום?
בהגדרות ->IPTV -> MAKE IPTV FILES ו USE IPTV

**Comment by burekas7** [comment]
כן בדר"כ זה מה שאני עושה וזה לא עזר.
אבל עכשיו איתחלתי שוב את קודי והנתונים חזרו.

אולי באמת היה משהו זמנית.
תודה
