### ISSUE TITLE
IdanPlus 1.1.x addon - ch 13 (Reshet) -> VOD section is empty on Kodi 16.1/android

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#3]
Hi,
I have been using your addon successfully on both my Windows 10 /PC (using Kodi 17.6) and my Android 6.1 TV Box (using pre-installed Kodi 16.1). 

A couple of weeks ago (cannot say exactly which version) , Kodi 16.1/Android started having issues with the 13->VOD section. When you try to enter *any* show (like "המירוץ למליון") you can see an EMPTY  list! There is no warning or errors, just empty lists for all VOD shows.  Kodi 17.6/Win -is working fine with  your latest v1.1.7.

I have tried:
1. regressing to 1.0.4 which I have access to on supperrepo - no issues there
2. Using your RESHET addon - also w/o any issue

Can you please have a look , see if you can track and fix the issue?  Sadly I cannot update Kodi on my TV box, probably because of Firmware issues (cannot "update" from playstore nor APK). 

Thank you for the very useful addon!

Rafi

**Comment by Fishenzon** [comment]
שבוע טוב.
הבעיה עם ה-VOD של רשת מתרחשת בקודי 16 על אנדרואיד?
אפשר לקבל אולי קובץ לוג?
אנסה לבדוק ממה נובעת הבעיה.

**Comment by Fishenzon** [comment]
@rafi-d 
נסה בבקשה את גירסה 1.1.8

**Comment by rafi-d** [comment]
תודה, בדקתי. הVOD של 13 עובד כעת.    מצד שני, נראה לי שהלינק הישיר של 13 לא עובד (לא מגיב בכלל).  לא בטוח שהבעיה בתוסף...

**Comment by rafi-d** [comment]
נב: 
אגב, יש ענין תפעולי קטן - העדכונים חדשים לא מוצגים/תופסים (לפחות אצלי) עד שלא מבצעים "עדכון" לREPO עצמו (למרות שהגרסה לא השתנתה).  מוזר.

**Comment by Fishenzon** [comment]
@rafi-d 
לא בוצע כל שינוי שנוגע לניגון של הערוץ.
זה עבד לך בעבר?

**Comment by rafi-d** [comment]
צודק. הוא לא עובד גם ב1.0.4 בקודי 16.  כנראה שראיתי אותו ממש מזמן עם התוסף שלך (קניתי בינתיים DONGLE DVB-T2...) .

כן, עם גרסה 1.2.0 גם צפייה בערוץ 13 חי  עובדת ב16 וב17 , תודה!
איך אתה מסביר שזה כן עבד  בקודי 17.6? 

נראה לי שאפשר לסכם את היום המוצלח בכך שהכול עובד (להיום...) ובברכת עלה והצלח... :) 

שוב תודה

רפי

**Comment by Fishenzon** [comment]
זה בגלל שימוש ב-SSL שלא נתמך בגירסאות ישנות של פייתון.
בקודי 17.6 יש גירסת פייתון שתומכת בזה.
