### ISSUE TITLE
 EPG  VOD ערוצים ישראלים בשפה הרוסית כולל רדיו 

### ISSUE THREAD

**Issue by Tima-1980** [Fishenzon/repo#30]
שלום fishenzon
בקשה לפיתוח הרחבה ל
 EPG  VOD ערוצים ישראלים בשפה הרוסית כולל רדיו 
או צירוף ערוצים להרחבה קיימת
ב שיתוף פעולה אני יעזור בתירגום אתרי אינטרנת ברוסית  שתבין מה ואפו נמצה

רדיו כאן REKA https://www.kan.org.il/live/radio.aspx?stationid=10 יש כבר בהרחבה
רדיו pervoe radio http://www.891fm.co.il/  כולל שידור חיי וידאו
ערוץ 9  http://9tv.co.il/
ערוץ ILAND https://www.iland.tv/  משדר רק באינטרנת
ערוץ ITON TV http://www.iton.tv/  משדר רק באינטרנת
ערוץ הקבלה ברוסית  http://kab.tv/#/stream
ערוץ STMEGI ברוסית  https://stmegi.com/tv/  משדר רק באינטרנת ערוץ של יהודי קווקז ברוסית

**Comment by Tima-1980** [comment]
תודה רבה מראש

**Comment by Fishenzon** [comment]
@Tima-1980 
נוספו שידורי רדיו ווידאו של 89.1
נוסף ערוץ ILand
נוסף ערוץ הקבלה ברוסית
לערוץ 9 אין שידור חי באתר
לערוצים ITON ו-STMEGI אין שידור חי באתר, יש שם רק שידור לא חי מיוטיוב

**Comment by Tima-1980** [comment]
תודה רבה  אתה תותח 
 אבל לא רואים את הערוצים
הוספתה להרחבה קיימת או עשיתה חדש?
קישור לשידור חיי ערוץ 9 בטורנת טי וי http://127.0.0.1:6878/hls/manifest.m3u8?id=2ab21170654a4c063d867907e3c828d6814e2fe5    יש גם עוד קישורים http://only-tv.org/9-kanal-izrail.html  גם http://tivix.co/378-9-kanal-izrail.html
iton tv ם stmegi  זה רק VOD

**Comment by Fishenzon** [comment]
הוספתי להרחבה הקיימת, שים לב שההרחבה התעדכנה ל-2.0.3, אני לא מעוניין לפתח הרחבה נוספת.
לגבי ערוץ 9, אני לוקח רק לינקים מהאתרים הרשמיים.
אני גם מנסה להישאר בתחום של עידן פלוס עם תוספת קטנה של ערוצים או תחנות.
נראה לי שנשאיר את ה-VOD לערוצים הרשמיים של עידן פלוס

**Comment by Tima-1980** [comment]
בסדר  תודה רבה לך

**Comment by Tima-1980** [comment]
מה הדרך לM3U במחשב וינדובס 10?
אני לא מצליח למצוע

אני יכול להוסיף ערוצים רק בישבילי

**Comment by Tima-1980** [comment]
יש אפשרות לעשות רק VOD לערוץ 9?
89.1  תכניות רדיו  https://www.oles.tv/891fm/shows/

**Comment by Fishenzon** [comment]
אני יכול להוסיף לתכניות של רדיו 89.1
אני לא מבין רוסית ואני לא יודע איפה באתר של ערוץ 9 נמצא ה-VOD

**Comment by rafi-d** [comment]
גוגל מבין רוסית... :)
http://translate.google.com/translate?hl=en&sl=auto&tl=en&u=http%3A%2F%2F9tv.co.il%2F
->TELEARCHIVE
עדיין, לא בטוח שההשקעה כדאית...

**Comment by Tima-1980** [comment]
telearchive     זה תוכניות ישנות
television  זה תוכניות חדשות

תודה רבה

**Comment by Tima-1980** [comment]
body  זה תוכנית עדשות פוליטיקיים

**Comment by Fishenzon** [comment]
נוספו בגירסה 2.0.4 תוכניות הרדיו של 89.1
נוסף גם VOD של ערוץ 9

**Comment by Tima-1980** [comment]
אתה תותח   תודה רבה
