### ISSUE TITLE
 תוכניות חסרות ב ערוץ 13

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#33]
היי
שמתי לב שחסרות תוכניות בעיקר בתחום האקטואליה  בערוץ 13 VOD 
למשל מכאן- 
https://13news.co.il/programs/
ברקוד, החדשות , שישי עם אילה חסון וכו

תוכל להוסיף? 

תודה

רפי

**Comment by Fishenzon** [comment]
נוספו תוכניות של חדשות 13 לתוך ה-VOD של ערוץ 13
בדוק את גירסה 2.0.5

**Comment by rafi-d** [comment]
תודה!
