### ISSUE TITLE
Sport 5 VOD

### ISSUE THREAD

**Issue by MrTal** [Fishenzon/repo#34]
שלום,
האם יש אולי אפשרות להוסיף את התכנים שיש ב-VOD 
של ערוץ הספורט להרחבה?
https://vod.sport5.co.il/?Vc=3968
(ה-VOD והתוכניות נמצאים פה:
http://prntscr.com/ngy4q0)
  כמובן אם זה לא מסובך מדי אם זה עבודה קשה מדי אפשר לוותר
תודה רבה!

**Comment by Fishenzon** [comment]
@MrTal 
נוסף ה-VOD.
כמו כן, נוסף שידור הרדיו לתחנות הרדיו וגם שידור הרדיו מהאולפן (במידה ויש כזה באתר) לערוצי הטלויזיה

**Comment by MrTal** [comment]
@Fishenzon 
תודה רבה עובד מעולה!
יש אפשרות אולי להוסיף גם את התוכניות רדיו של ספורט 5?
"5 באוויר":
http://radio.sport5.co.il/#!/page?path=3336ecea-4234-4761-8a00-d5f64edffc2c
והפודקאסטים:
"http://radio.sport5.co.il/#!/page?path=a9c24c7b-9fe5-4087-b2cc-098705329ea6
תודה!

**Comment by rafi-d** [comment]
@Fishenzon
רק הערה, אין בעיה עם הסטרמה של תכנים מערוצים מסחריים, שמעולם לא שודרו חינם באוויר?
הרי בעצם הם בונים על פירסומות באתר, וכאן יש פגיעה בפרנסה שלהם...
(לא שאכפת לי אישית, רק שלא יתנקלו אולי לתוסף בגלל זה...)

**Comment by MrTal** [comment]
@rafi-d 
אתה יכול להגיד את זה גם על קשת ורשת הם גם מתבססים על הפרסומות (בעבר הם גם ניסו להילחם בזה ובסוף התייאשו) 
וגם השימוש בתוסף ירד מבעבר 
לא רואה אישית בעיה שיכולה להוות נזק

**Comment by rafi-d** [comment]
ההבדל שהתכנים של אילו היו חופשי באוויר ושל 5 לא... בגישה הזאת, למה לא לתת
את ערוץ 5hd חי התוסף? אני רק אשמח....

**Comment by Fishenzon** [comment]
@rafi-d
כל התכנים נלקחים מהאתר הרשמי שלהם.
אם הם יעלו לשם גם את השידור החי, אין לי בעיה להוסיף אותו.

**Comment by MrTal** [comment]
@rafi-d 
גם התכנים של ספורט 5 הם חופשי באוויר,
כמו שהסביר התכנים נלקחים רק מהאתר הרשמי ולא ממקור אחר.

**Comment by MrTal** [comment]
@Fishenzon 
ראיתי גם הוספת חיפוש ממש מוסיף!
תודה רבה עובד מעולה!
בזמנך הפנוי אם לדעתך צריך אולי להוסיף גם את התוכניות רדיו והפודקאסטים של "רדיו 5"
"5 באוויר":
http://radio.sport5.co.il/#!/page?path=3336ecea-4234-4761-8a00-d5f64edffc2c
והפודקאסטים:
"http://radio.sport5.co.il/#!/page?path=a9c24c7b-9fe5-4087-b2cc-098705329ea6
חוץ מזה הוספת ממש הכול והחיפוש גם אחרי בדיקה נהדר
תודה רבה על ההשקעה!

**Comment by Fishenzon** [comment]
@MrTal 
נוספו התכניות של הרדיו והפודקאסטים.

**Comment by MrTal** [comment]
@Fishenzon 
תודה רבה!
נעלתי פה
