### ISSUE TITLE
חסרות תוכניות אחרונות בכאן-רדיו (למשל 88)

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#35]
בהמשך ל#20
תוכניות כאן 88 מוצגות *ללא* התוכניות האחרונות המרוכזות בדף הראשי/מיידי באתר
כנראה שוב היה שינוי..

מצרף דוגמא
![1](https://user-images.githubusercontent.com/2458280/57122278-33e16c00-6d85-11e9-8028-fa2a7271c80b.png)

**Comment by Fishenzon** [comment]
תודה.
אסתכל על זה בהזדמנות

**Comment by Fishenzon** [comment]
@rafi-d 
בוקר טוב.
באמת היה שינוי.
טופל

**Comment by rafi-d** [comment]
אבדוק הערב, תודה...
