### ISSUE TITLE
 עדכון חדש מופיע ריק \\ גרסאות

### ISSUE THREAD

**Issue by x9t9** [Fishenzon/repo#36]
<span dir="RTL">

 מאתמול (עדכון אחרון?) רשימת התוספים מופיעה ריקה 
רואים רק את התוספים המותקנים כבר

 ניסיתי להסתכל ב commits  אבל האמת שלא מצאתי שום בעייה באחרונים
חוץ מהעובדה שאין שינוי במספר הגרסה - יש סיבה לזה? זה מקשה על דיבאגינג אם כולם מופיעות אותו מספר
דרך אגב אם צריך עזרה לתחזוק התוסף אני מוכן ..
</span>

**Comment by Fishenzon** [comment]
@x9t9 
שבוע טוב.
לא ברור על מה מדבר, כנראה בעיה אצלך

**Comment by x9t9** [comment]
@Fishenzon 
אכן בעייה אצלי
מצטער על הבלבול

בכל מקרה השאלה למה לא לעדכן מס גרסא עדיין עומדת
הרי קודי משתמש במספר גרסא בשביל לבדוק עדכונים אוטומטיים
`Addon.xml` לפי  המספר שמוגדר ב

**Comment by Fishenzon** [comment]
מספר הגירסה מתעדכן בכל גירסה.
היום יצאה גירסה 2.0.9

**Comment by x9t9** [comment]
אוקיי - אתה מתכוון לגירסא של עידן פלוס כנראה
לא משנה -תשכח
ותודה על העבודה- אם אתה צריל עזרה בתחזוק או פיתוח נוסף אני פנוי
