### ISSUE TITLE
בעייה ב VOD כאן 

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#39]
https://www.kan.org.il/program/?catid=1117
"החיים הסודיים של גן החיות" - שום לינק לא עובד :( באתר הכל תקין. ניתן לסדר?
  יתכן וגם עוד תוכניות בבעיה?

תודה

**Comment by Fishenzon** [comment]
תודה.
תוקן

**Comment by rafi-d** [comment]
זה היה משהו נקודתי בתוכנית הזו או משהו כללי יותר לכל הVOD?

**Comment by Fishenzon** [comment]
נראה כמו טעות נקודתית.

**Comment by rafi-d** [comment]
עובד, תודה!
