### ISSUE TITLE
יש לי בקשה/בעיה אולי תוכל לעזור לי בה 

### ISSUE THREAD

**Issue by swizytv** [Fishenzon/repo#4]
היי
ראשית אני חושב שאתה עושה עבודה נהדרת 

גבי הבעיה/בקשה 
אפשרות לעבור ערוצים י"ע מספרים בשלט (הוריי מבוגרים וקשה ללמד אותם תרגילים חדשים)

ערוצים 12/13 לא עובדים -לא מצאתי לינקים בפורמט M3U בקודי תחת PVR ושם יש אפשרות לעבור ערוצים בשלט ע"י מספרים 
התוסף IdanPlus addon נותן פיתרון נהדר לערוצים החסרים.

יש אפשרות ליצור addon  נוסף שיש ניתן להשתמש במספרים לעבור ערוצים 
וגם אך שנכנסים לaddon  זה יתן את רשימת הערוצים לחסוך דילוג לדף הבאה 

אשמח אם תוכל לעזור בנושא
נ.ב
אני חושב שעוד אנשים ישמחו לקבל פתרון לנושא

**Comment by rafi-d** [comment]
רעיון טוב! מצטרף .... :)
מציע אולי להתחיל פשוט - מזה שהתוסף תמיד ישמור בקובץ 
M3U
 מקומית את הלינקים של כל הערוצים

בPVR 
נוכל להסתנכרן/לפתוח את הקובץ הזה

בהמשך - אולי ניתן להפעיל את 
הPVR
 ישירות מכפתור בתוך התוסף עצמו?

**Comment by Fishenzon** [comment]
@swizytv 
לגבי הצגת רשימת הערוצים בפתיחת ההרחבה, אתה יכול להוסיף קיצור לזה למועדפים.
תלחץ כפתור ימני על שידורים חיים ותוסיף את זה למועדפים.

@rafi-d 
הבעיה עם רשימה ל-PVR היא שהלינקים לחלק מהערוצים נוצרים בזמן אמת.
ה-PVR לא יודע לייצר את הלינק בזמן אמת, הוא רק מנגן את הלינק שיש לו ברשימה

**Comment by rafi-d** [comment]
- ברור. בהנחה שהלינקים לערוצים לא משתנים כ"כ דינמית בכל רגע שהתוסף אכן ייצר אותם דינאמית (כפי שאתה אומר שקורה כעת) וישמור את הרשימה הזאת (סטטית) בזיכרון ,  או על הדיסק/קאש המקומי. בלחיצה על "כפתור PVR" בתוסף - הוא יופעל מול הרשימה הסטטית הזאת. 

בהפעלה הבאה של התוסף (או בהפעלה הבאה של הPVR מתוכו) - הרשימה תוכל להתעדכן.

לגבי EPG - האם תיאורתית גם אפשרי ליצא לPVR ?

**Comment by Fishenzon** [comment]
@rafi-d 
EPG זה לא בעיה לעשות בפורמט של PVR
לגיב הערוצים, ערוץ 12 הכי בעייתי ונוצר במקום, שאר הערוצים די קבועים

**Comment by rafi-d** [comment]
אם כך, אולי להפעיל  לניסוי ללא ערוץ 12 (ממילא החדשות משותפות ל13...) ובהמשך לחשוב על פתרון?

**Comment by swizytv** [comment]
היי תודה על המענה
אני מודע שאפשר להוסיף קיצור למועדפים 
הכיוון שלי זה להפעיל הכל רק עם קיצורים לשלט אני יודע להגדיר שכפתור מסוים יפתח את ה addon מסויים במסך הראשי שלו
אולי את מכיר דרך לעשות קיצור דרך לשלט/מקלדת שיפתח את לינק מסויים מהמעודפים ?
אני יודע שאפשר לערוך את keymap.xml רק לא את הערך שיש להזין כדי שיעבוד ***
<keymap>
   <global>
      <keyboard>
        <One> PlayMedia(***) </ one>
      </keyboard>
   </global>
<keymap>

**Comment by Fishenzon** [comment]
אתה יכול להוסיף למועדפים גם תפריט בתוך הרחבה וגם לינק.
אתה יכול לראות מה נוצר בקובץ favourites.xml שבתוך התיקיה userdata.
לדוגמה:
<favourites>
    <favourite name="[B]שידורים חיים[/B]" thumb="C:\Kodi18\portable_data\addons\plugin.video.idanplus\icon.png">ActivateWindow(10025,&quot;plugin://plugin.video.idanplus/?iconimage=C%253A%255CKodi18%255Cportable_data%255Caddons%255Cplugin.video.idanplus%255Cicon.png&amp;mode=1&amp;module&amp;moredata&amp;name=%5bB%5d%d7%a9%d7%99%d7%93%d7%95%d7%a8%d7%99%d7%9d%20%d7%97%d7%99%d7%99%d7%9d%5b%2fB%5d&amp;url&quot;,return)</favourite>
    <favourite name="[COLOR yellow][B]קשת 12[/B][/COLOR] - [COLOR orange][B]מהדורה ראשונה[/B][/COLOR] [COLOR burlywood][16:30-17:15][/COLOR]" thumb="C:\Kodi18\portable_data\addons\plugin.video.idanplus\resources\images\keshet.jpg">PlayMedia(&quot;plugin://plugin.video.idanplus/?moredata=best&amp;name=%5BCOLOR+yellow%5D%5BB%5D%D7%A7%D7%A9%D7%AA+12%5B%2FB%5D%5B%2FCOLOR%5D+-+%5BCOLOR+orange%5D%5BB%5D%D7%9E%D7%94%D7%93%D7%95%D7%A8%D7%94+%D7%A8%D7%90%D7%A9%D7%95%D7%A0%D7%94%5B%2FB%5D%5B%2FCOLOR%5D+%5BCOLOR+burlywood%5D%5B16%3A30-17%3A15%5D%5B%2FCOLOR%5D&amp;url=12&amp;iconimage=C%253A%255CKodi18%255Cportable_data%255Caddons%255Cplugin.video.idanplus%255Cresources%255Cimages%255Ckeshet.jpg&amp;module=keshet&amp;mode=10&quot;)</favourite>
</favourites>
אתה יכול להעתיק את הפקודה הרצויה משם

**Comment by swizytv** [comment]
כן ניסיתי את זה
לא עובד...

**Comment by rafi-d** [comment]
אצלי עובד... 
 הנה הקובץ שלי 
...\userdata\keymaps\keyboard.xml 

https://drive.google.com/file/d/1CdpcCiiVFoHQjQa4SJdyfLcuMgJ7BAOP/view?usp=sharing

 - מוגדרים
control 1-2-3-4 
לערוצים 11-12-13-14

(הועתקו בדיוק מהמועדפים)

עדיין חבל לי שאין קובץ M3U לטובת ה PVR :(

**Comment by swizytv** [comment]
הצלחתי הפעם תודה
נראה שאני אסתפק בנתיים בקיצורים עם השלט רק חבל שזה מגביל אותי ל10 קיצורים

**Comment by popcorntv** [comment]
היי פישנזון שלום לך ראשית רציתי לומר שאני משתמש בהרחבה שלך תענוג הרחבה מיוחדת במינה ואני משתמש בה קבוע ונהנה מימנה מאוד ורציתי להציע הצעה אם תוכל בבקשה להוסיף לה אפשרות בהגדרות שתאפשר לי לקבוע ולשנות את הברירת מחדל של הניגון של כל ערוץ לדוגמה כל הערוצים עובדים לי נהדר ב 1080 חוץ מערוץ 10 שהוא משודר באיכות 720 שאחרי צפייה של פרק זמן מסוים הוא נתקע ובבחירת איכות ניגון יש לך שם שני אכויות של 480 שהתחתון מבניהם עובד יפה מאוד ולא נתקע וללא שום באפר בכלל והייתי והייתי רוצה להגדיר אותו קבוע במקום כל פעם להיכנס לבחירת איכות ניגון ושם לבחור את אותו קישור ושוב ותודה רבה על ההרחבה הנהדרת אני מאוד מקווה שתענה להצעה שלי והמשך ערב טוב והיה נחמד אם היית מצטרף לטלגרם אם היה לך שם איזה קבוצת תמיכה להרחבה שלך להצעות ושיפור ההרחבה אולי אפילו בתור התחלה תיכנס לקבוצה של החתול תוכל בחיפוש לרשום KODICAT :) 👍

**Comment by rafi-d** [comment]
ערוץ 10 לא משודר ב1080P בהוט/YES? 
יש מצב למצוא לינק FHD אליו?

**Comment by Fishenzon** [comment]
@popcorntv 
אתה יכול להפעיל את הערוץ ישירות באיכות הזאת, למשל ע"י פלייליסט-לודר עם הכתובת:
`plugin://plugin.video.idanplus/?module=ten&mode=6&moredata=1240800`
או במועדפים של קודי:
`<favourite name="[COLOR yellow][B]עשר 14[/B][/COLOR]" thumb="C:\Kodi18\portable_data\addons\plugin.video.idanplus\resources\images\ten.png">PlayMedia(&quot;plugin://plugin.video.idanplus/?moredata=1240800&amp;name=14&amp;url=14&amp;module=ten&amp;mode=6&quot;)</favourite>`

**Comment by popcorntv** [comment]
כן אבל אני מעדיף שיהיה נוח וישירות דרך ההרחבה שלך ודרך הישומון (וויג'ט) לא עדיף ככה? שיהיה הגדרה אני לא היחידי שהערוץ הזה לא עובד לו חלק וגורם לתקיעות

**Comment by Fishenzon** [comment]
@popcorntv 
נוספה (בגירסה 1.5.2) האופציה לקבוע איכות שידור לערוץ.
תראה את זה בתפריט מתחת לבחירת איכות (שהיא חד פעמית), באופציה של קביעה זה ישאר קבוע.

**Comment by rafi-d** [comment]
יש בעיה: הרזולוציה ב SET לא נשמרת ... (WIN10 /17.6)
לטעמי יש גם למצוא דרך להציג את הבחירה לצד הערוץ , כדי לזכור ש"קלקלנו"... אולי גם את הטווח במצב "AUTO".

**Comment by Fishenzon** [comment]
@rafi-d 
תבדוק בהגדרות אם נרשם לך הביטרייט ליד הערוץ.
אין סיבה שלא ישמרו לך ההגדרות.
ה-AUTO בסה"כ מוחק את הביטרייט נותן להרחבה לנגן בלי לקבוע לה ביטרייט מסויים.
אולי אוסיף לשם הערוץ סימון שמעיד שנקבעה לו ידנית איכות ניגון

**Comment by rafi-d** [comment]
אוקיי, נראה ש אכן פנימית הוא שומר את הרזולוציה וגם מנגן בה. 
בדקתי בהגדרות, לא רואה שום סימון ליד הערוץ שם.
איפה בדיוק אמורים לראות את זה בהגדרות? אולי אני מפספס משהו...

https://drive.google.com/file/d/1q_pX3gm6vdFKv1iiFSAYyWc9jSL72uO2/view?usp=sharing

**Comment by Fishenzon** [comment]
@rafi-d

**Comment by Fishenzon** [comment]
גם הבחירה באוטןמטי עבדה אצלי במכשירים שונים

**Comment by popcorntv** [comment]
Fishenzon
מושלם תודה רבה רבה לך ותבוא לטלגרם נצרף אותך לקבוצה טובה ששם ישמחו לדבר איתך לשתף אותך ברעיונות חדשים ותוכל להציע רעיונות חדשים להרחבות אחרות

**Comment by Fishenzon** [comment]
@swizytv 
נוספה תמיכה בטלויזיה חיה בקודי 18
הקבצים לטלויזיה החיה נמצאים בתיקית הפרופיל של ההרחבה
רשימת ערוצים:
idanplus.m3u
מדריך שידורים:
epg.xml.tar.gz
