### ISSUE TITLE
חיפוש בעייתי (עברית?)

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#41]
Kodi 17.6
Windows 10
גרסה מעודכנת של התוסף

מנסה חיפוש של תוכנית רדיו בכאן11-רשת ב ע"פ מילה (שם) ולא מצליח למצוא
לא בדקתי בערוצים אחרים, אבל אני מניח שהתופעה דומה
בעיה בהגדרות שלי של קודי? בעיה בתוסף? בעיה כללית עם חיפוש בעברית?
![1](https://user-images.githubusercontent.com/2458280/65217878-e9efed00-dabd-11e9-8fef-f1304b53f197.png)

**Comment by Fishenzon** [comment]
זאת בעית כללית בקודי

**Comment by rafi-d** [comment]
כנראה שלא שמת לב גם לפתרון/דוגמא שהבאתי... תסתכל בראשית התמונה
תראה דוגמא מהLIVE TV 
שעובדת היטב.
תוגל להעתיק משם את הקוד?
