### ISSUE TITLE
חיפוש בעייתי (עברית?)

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#42]
Kodi 17.6
Windows 10
גרסה מעודכנת של התוסף

מנסה חיפוש של תוכנית רדיו בכאן11-רשת ב ע"פ מילה (שם) ולא מצליח למצוא
לא בדקתי בערוצים אחרים, אבל אני מניח שהתופעה דומה
בעיה בהגדרות שלי של קודי? בעיה בתוסף? בעיה כללית עם חיפוש בעברית?

![1](https://user-images.githubusercontent.com/2458280/65218086-5cf96380-dabe-11e9-8603-c0f61f145193.png)

**Comment by rafi-d** [comment]
נב: אותה בעיה ב"FILTER"

**Comment by Fishenzon** [comment]
תבדוק בעוד הרחבות.
לפי מה שראיתי, מעל 2 אותיות זה לא עובד.

**Comment by rafi-d** [comment]
בדקתי ב LIVE TV 
עובד...
אתה פשוט "מבתלבל" בימין-שמאל בחלון החיפוש או פילטר
אם מקלידים הפוך זה עובד.... גם אצלך 
![1](https://user-images.githubusercontent.com/2458280/66121845-c745f400-e5e6-11e9-9cc1-72d8857a68dd.png)


ראה דוגמאות....

**Comment by Fishenzon** [comment]
אז מצאת את הפתרון, לכתוב מהסוף להתחלה.
בדקתי עכשיו בתכניות רדיו של כאן 88 וזה עובד.
![Annotation 2019-10-03 164334](https://user-images.githubusercontent.com/29551534/66132140-4a724480-e5fd-11e9-9a4b-3f23ea70f6e2.jpg)

**Comment by rafi-d** [comment]
העלת חיוך על פני.... 
לא ממש, מצאתי רק רמז לפתרון, שהתוכנה שלך ושל קודי צריכה להשתמש למשתמש השפוי בארץ שלנו...:)

**Comment by Fishenzon** [comment]
זאת בעית כללית בקודי
