### ISSUE TITLE
תקיעות בשידורי קשת

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#44]
היי,
משהו השתנה מבחינת העברת שידורי קשת?
בימים האחרונים יש ממש תקיעות בעייתיות עד כדי הקפאה של התמונה (השידור לא נסגר), השאלה אם זה משהו אצלם או בתוסף שהשתנה?

גירסה 2.2.8

תודה מראש

**Comment by Fishenzon** [comment]
לא ראיתי שום בעיה.
תבדוק את ספק האינטרנט שלך

**Comment by burekas7** [comment]
מוזר. לא החלפתי או שיניתי משהו בספק,  ושאר הערוצים כן עובדים תקין.
רק קשת מתחיל 20-30 שניות ואז נכנס לפריז. זה לא היה ככה קודם.

**Comment by Fishenzon** [comment]
כמו שכתבתי, לא ראיתי בעיה.
צפיתי עכשיו 10 דקות רצוף.
זאת כנראה בעיה מקומית אצלך או אצל הספק שלך.
נסה לצפות דרך רשת הסלולר שלך ותראה אם יש שינוי

**Comment by burekas7** [comment]
וואלה צדקת.
בהתחלה חשבתי הספקית, התשתית.
בסוף מסתבר שהלפטופ שלי של Dell
והם מתקינים תוסף\תוכנה בלי לשאול שנקראת SmartByte
שאיכשהו הצניחה לי את הוויפי מ-90 מגה ל-10 מגה.
אחרי שהעפתי הכל חזר (צריך לשים לב שזה לא מותקן שוב מדי פעם)
אז שתדעו.
