### ISSUE TITLE
בעיה עם החיפוש תוכניות

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#45]
יש בעיה מוזרה עם החיפוש.

כשאני מנסה להריץ בחיפוש הכללי וגם בחיפוש של mako vod את השם של התוכנית:
"ביום שהאדמה רעדה", או רק את המילים בנפרד, הוא לא מציג תוצאות (והתוכנית כן קיימת ברשימת התוכניות)
אבל כשאני אחפש למשל "הכוכב הבא" הוא כן מוצא.
מה מיוחד בסדרה שהוא לא מצליח למצוא אותה בחיפוש?

**Comment by Fishenzon** [comment]
לא יודע למה זה לא מוצא בחיפוש של מאקו.
לגבי החיפוש הכללי של עידן פלוס, עדכנתי עכשיו את הרשימות וזה ימצא לך את הסדרה.

**Comment by burekas7** [comment]
אחלה תודה!
הייתה לי הרגשה שזו כנראה בעיה שקשורה אליהם יותר.

אגב אנצל את התגובה שיש בעיה קטנה עם לוח השידורים שיורד לקובץ ה-epg.
או שאין מידע על התוכניות או שהתוכנית מוצגת רק כרבע שעה ולא באורכה המלא.
כנראה נוצר מאז המעבר לשעון חורף.
השאלה אם גם כאן זו בעיה במקור שממנו אתה לוקח את הנתונים.

**Comment by Fishenzon** [comment]
באיזה ערוץ מדובר?
תנסה לרענן את לוח השידורים דרך הגדרות ההרחבה, יכול להיות שאתמול באמת היתה בעיה בעקבות מעבר השעון.

**Comment by burekas7** [comment]
רלוונטי לי שלושת הערוצים בעיקר של כאן, קשת ורשת.
ושכחתי לציין, אני מתכוון לגבי לוח השידורים של ה-Live TV שמתבסס על הקובץ שההרחבה יוצרת.

ביצעתי את כל הרענונים דרך ההגדרים (force, make iptv files ...)
עשיתי גם ניקיון של נתוני ה-Guide דרך הגדרות ה-live tv בקודי.

**Comment by Fishenzon** [comment]
![screenshot000](https://user-images.githubusercontent.com/29551534/67666178-e9c3f680-f973-11e9-9ab9-f8d98d785f90.png)

כנראה שבכל זאת עשית משהו לא בסדר
תלחץ בהגדרות של 
live tv 
גם על איפוס נתונים בהגדרות הכלליות

**Comment by burekas7** [comment]
מה שלא הולך במוח הולך בכוח חח
בסוף מחקתי את ה-epg.db של קודי, הוא יצר אותו מחדש והכל חזר והסתדר, תודה.

@Fishenzon

**Comment by burekas7** [comment]
היי,
עדכנתי לגירסה האחרונה, אבל עדיין הוא לא מוצא את "ביום שהאדמה רעדה", גם בחיפוש הכללי וגם בזה הפנימי של מאקו VOD.

**Comment by burekas7** [comment]
היי,
עדכנתי לגירסה האחרונה, אבל עדיין הוא לא מוצא את "ביום שהאדמה רעדה", גם בחיפוש הכללי וגם בזה הפנימי של מאקו 
VOD.

**Comment by rafi-d** [comment]
תסתכל ב ISSUE  #42
זה עובד הפוך. לפעמים... 

![1](https://user-images.githubusercontent.com/2458280/67676611-8ee9c980-f98a-11e9-9bb9-9329c1af9f5e.png)

התירוץ היה "בעיה כללית בקודי...

**Comment by Fishenzon** [comment]
@burekas7 
תמחק מתיקית הפרופיל (תקית המשתמש) של ההרחבה את הקובץ
series.json
או שתחקה עוד כמה שעות ותנסה שוב.
אם הקובץ שאצלך בין פחות מ-24 שעות, לא יורד אליך הקובץ החדש מהשרת.

**Comment by burekas7** [comment]
@Fishenzon 
אלוף! אחרי מחיקת הקובץ זה מציג.
אבל כאמור רק בחיפוש הכללי, בחיפוש בתוך מאקו וי.או.די, כמו שציינת כנראה בעיה מוזרה אצלם.
למרות שלמשל אני מריץ חיפוש עם המילה "ביום" הוא מביא לי שלוש תוצאות שבכלל לא מכילות את המילה בכותרת (אולי בתיאור מופיעה אבל בחיפוש לא רואים תיאור, רק כותרת)

@rafi-d 
אין שום בעיה עם היפוך, אני כותב רגיל.
תוכניות אחרות כן ימצא כמו למשל "הכוכב הבא" ועוד
