### ISSUE TITLE
VOD כאן11 - שמות תוכניות משתבשים לאחר צפיה 

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#46]
לאחר צפיה כלשהי, וחזרה לרשימת התוכניות - שם התוכנית שצפית בה - משתבש 
מסתדר שוב ברגע שמדפדפים או צופים בתוכנית אחרת...
![1](https://user-images.githubusercontent.com/2458280/68512205-70d07300-0280-11ea-8d7a-dcecab63f098.jpg)

**Comment by rafi-d** [comment]
נב: ללא קשר, אולי כדאי להוסיף את תאריך השידור?

**Comment by Fishenzon** [comment]
זה קורה בגלל שהניגון מתבצע דרך ההרחבה של יוטיוב והיא מעדכנת על הדרך את השם התכנית.
תאריך השידור לא מופיע באתר

**Comment by rafi-d** [comment]
ואי אפשר לבצע REFRESH אח"כ?
אגב, יתכן וזה קורה רק באנדרואיד, ולא בWIN.
לא בטוח. זה עוזר?

**Comment by rafi-d** [comment]
לא ציינתי קודם, מותקן 17.6 באנדרואיד.
עדכנתי באנדרואיד  לקודי 18.4, והבעיה נעלמה.
FYI
אפשר לסגור
תודה

אגב, לאלו שמעדכנים ל18 ומשתמשים בסקין אחר (אצלי
XONFLUENCE)
עדיף להעביר לסקין דיפולט לפני העדכון, לעדכן ב18 את הסקים הדרסה חדשה, ורק אח"כ להחליף חזרה לסקין החלופי...
