### ISSUE TITLE
מספר ערוץ במועדפים

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#47]
תוכל בבקשה לנסות להוסיף את מספר הערוץ לצד שם התוכנית בעת הוספה למועדפים 
?(של עידן+ ו/או הכללי)

תודה

רפי

**Comment by Fishenzon** [comment]
בוקר טוב
אם הכוונה שלך היתה ששם הערוץ ממנו לקוח הפריט ברשימת המועדפים יופיע לצידו, הוספתי את זה עכשיו בגירסה 2.3.7

**Comment by rafi-d** [comment]
(...)כן, זו הייתה הכוונה. תודה!

מה שמזכיר  רעיון נוסף, אפשרות לגישה/בחירה ישירה  לערוצים ע"י הקשת מספרם בשלט?
 ?אני מבין שלצורך זה ידרוש להוסיף ספרור רץ
מה שפחות נוח, בקודי, שלא מכיר שם דרך למפות מספרים לבחירתך לערוצים. אם תהיה גם אפשרות כזו - יהיה מאוד נוח לגישה מהשלט.
אגב, אפשרות כזו גם קיימת ב 
שבקודי live TV 
במחשבה שניה, היות ואין לנו עשרות ערוצים, אולי השימוש החיצים שהשלט מספיק... מה דעתך?

**Comment by rafi-d** [comment]
PS:
תוכל לעשות את אותו הדבר גם בהוספה למועדפים של קודי?
אגב, יש לך טעות בפורמט שם, ולכל בשימות נוסף התו "/B"

**Comment by rafi-d** [comment]
ועוד הצעה - לאפשר מיון לפי שם במועדפים (זה נראה חסום כעת)

**Comment by Fishenzon** [comment]
הוספתי אפשרות מיון במועדפים.
הוספה למועדפים של קודי זה משהו חיצוני להרחבה.
הצגת סימן ההגדשה (או חלק ממנו) במועדפים, תלוי בסקין שבו אתה משתמש. כנראה שהסקין מנסה לעשות הדגשה בעצמו וזה מתערבב עם ההדגשה והצבעים של הכיתוב שנלקח מההרחבה.
לגבי מספור ערוצים, אני לא נכנס לזה.

**Comment by rafi-d** [comment]
אוקיי, מובן.
כדאי לנסות לדעתי לעשות משהו לגבי שירבוב הפורמט לסקין, אולי אפילו לוותר בכלל על שינויים לפונט במועדפים אם אח אפשר אחרת.

ניתן לסגור מבחינתי, תודה!
