### ISSUE TITLE
מועדפי עידן פלוס - כפילות שם ערוץ בכותרת

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#48]
כשמוסיפים פריט מהחיפוש תוכניות הכללי של ההרחבה למועדפים בהרחבה, אז הכותרת מופיעה פעמיים.
זה קרה אחרי העדכון האחרון נדמה לי.
* כשמוסיפים למועדפים מתוצאות החיפוש של ה-וי.או.די של אותו ערוץ אז אין כפילות, מדובר רק בחיפוש הכללי.
אכן בעבר התוספת של הערוץ הייתה מצורפת רק להוספה מהחיפוש הכללי ולא כאשר ההוספה הייתה מתוך הערוץ עצמו. כי כשאתה עושה חיפוש כללי אתה רוצה לדעת מאיזה ערוץ התוצאה התקבלה שזה הגיוני, ולכן הכפילות כרגע.

![image](https://user-images.githubusercontent.com/13424257/69175007-a0e30600-0b0b-11ea-8bb2-d9d703662e44.png)

**Comment by burekas7** [comment]
אפרופו מועדפים והתוספת של "שיטת המיון", בקשה קטנה:
יש מצב להעביר את הבחירה הזו כחלק מהגדרות ההרחבה ולא כחלק מהרשימה?
פשוט אני משתמש בזה כווידג'ט וזה מכניס גם את האופציה הזו לתוכן בווידג'ט וזה קצת מפריע.

**Comment by rafi-d** [comment]
לא ממש אינטואיטיבי לחפש מיון ב SETUP

**Comment by burekas7** [comment]
אני יודע, פשוט מנסה לחשוב על דרך להסתיר את האופציה הזו ברשימה.
אולי להוסיף בהגדרות "הצגת איפשור שיטת מיון - הפעלה\ביטול"

גם לא ברור ספציפית למועדפים אם יש צורך, לא חושב שאנשים שם מכניסים עשרות מועדפים שדרוש מיון כלשהו, אבל זו דעתי.

**Comment by rafi-d** [comment]
כן, לאפשר/לבטל זה אולי אפשרי...  
עם DEFAULT - מאופשר
למה זה בדיוק מפריע? זה סטנרדטי בקודי.

**Comment by burekas7** [comment]
ציינתי, ענייני ווידג'ט במסך הראשי, זה מציג אותו כפריט מן המניין וזה מפריע בתצוגה

**Comment by Fishenzon** [comment]
@burekas7 
סידרתי שלא תהיה כפילות (תמחק ותוסיף מחדש מה שכבר מופיע עם כפילות)
הוספתי אפשרות להסתיר את האופציה בהגדרות

**Comment by burekas7** [comment]
@Fishenzon 
מעולה! תודה רבה, אלוף.

* אגב, משהו קטן ולא קריטי:
אם מישהו בחר למיין לפי א,ב אז אין חשיבות לאופציות של "הזז למעלה\למטה\למיקום"
כרגע הם עובדים רק כאשר שיטת המיון שנבחרה היא "לפי סדר הוספה"
למרות שגם זה די מבלבל, כי אחרי שמזיזים זה כבר סוג של
Custom

אבל אין צורך לגעת כרגע, סתם כהערה.

**Comment by Fishenzon** [comment]
תודה.
הסתרתי את האופציות כשהרשימה ממוינת.
שיניתי את את סדר הוספה לסידור אישי

**Comment by rafi-d** [comment]
אני רק שאלה:
למה המיון לא נעשה ע"י ה
SORT 
 של קודי שנמצא ב
TAB 
 משמאל?

**Comment by burekas7** [comment]
@rafi-d 
מיון של קודי הוא בדר"כ לפי זמן, כותרת וז'אנר
ממה שאני מכיר אין שם אפשרות של 
custom

הרעיון של מיון לפי שם ערוץ גם יכול להיות נחמד.
למרות שלדעתי מיון לפי א,ב, אמור לתפוס את זה, 
אלא אם כן ה-א,ב הולך רק לפי שם התוכנית בלבד ושם הערוץ לא נכלל בכותרת.

**Comment by rafi-d** [comment]
כרגע, טוב יוצא לפי שם תוכנית, כי בכותרת שם הערוץ הוא אחרי שם התוכנית.  פשוט צריכים להפוך את הסדר לשם-ערוץ ואחכ שם תוכנית

או, פשוט להוסיף קטגוריה נוספת.

**Comment by rafi-d** [comment]
לפני שסוגרים את הבסטה כאן, עוד הערה-בקשה....
דוגמא:
אני בוחר את "הכוכב" הבא" למועדפים, אבל כדי לחסוך, בוחר ישר את עונה 7 . במקרה הזה מוצג רק "עונה 7"... 

מציע לבנות לוגיקה שתציג את השם המלא (עד רמת הערוץ) , במקרה הזה:
קשת 12 - הכוכב הבא - עונה 7
(כיום מוצג קשת 12 - עונה 7....) 

חושב שאפשרי?

תודה!
