### ISSUE TITLE
PVR Support 

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#5]
היי,
בהמשך להערות בISSUE הסמוך (הבקשה לSHORTCUTS עם מספרי ערוצים)
העליתי רעיון להוספת תמיכה בפורמט PVR של קודי (עם SIMPLE PVR CLIENT למשל) לערוצים החיים.
בניתי קובץ M3U בסיסי עם הלינקים המדויקים שהתוסף יוצר (נלקחו מהלוג) , ובינתיים נראה שהם עובדים בסדר כבר כמה ימים.
בפורמט הזה, השימוש בשלט או SHORTCUTS לערוצים עוד  יותר פשוט. כמובן, שכל הממשק למשתמש - מתאים יותר לערוצים חיים.

מציע, שוב, לשקול להוסיף יצירה אוטומטית של קובץ כזה בתוסף , כמובן עם ICONS וEPG שלא הוספתי בבדיקה שלי.

תודה ושבת שלום!

רפי

הקובץ לדוגמא כאן:
https://drive.google.com/file/d/1YXUomocOjhUZPCR1UZFpCSpiS_pbJ1-i/view?usp=sharing

**Comment by swizytv** [comment]
יפה!
תוכל להכווין אותי אך על איזה לוג מופעים הלינקים? 
(נלקחו מהלוג)
ערוץ 12 הפסיק צריך לעדכן אותו

**Comment by rafi-d** [comment]
כן, היה צפוי שיפסיק מדי פעם לפעול, לכן השילוב התוסף היה יכול לפטור את הבעיה... :( 
הקובץ הוא kodi.log נמצא באותו מקום בו מחיצות USERDATA ו ADDONS
מפעילים את ערוץ 12 בתוסף ואז מחפשים שורת:
NOTICE: VideoPlayer: Opening: https://keshethlslive .... 
ומעתיקים את כל הכתובת ... 

יש לינק לרשימה דומה לקובץ הזה שהעליתי לרשת (מעודכנת) אבל נראה לי שאני כבר לא אתייחס לערוץ 12 . אולי נוותר אליו

הוראות שימוש כאן:
https://www.hometheater.co.il/vt296401.html

**Comment by rafi-d** [comment]
עדיין מקווה לתמיכה בממשק הזה מתוך התוסף 
(  בעיקר בהקשר ללוח שידורים שדי חסר לי שם כיום )

**Comment by Fishenzon** [comment]
@rafi-d 
בגירסה 1.7.3 נוצרים בתיקיית הפרופיל של ההרחבה קבצים לטלויזיה חיה.
התמיכה היא בקודי 18 ומעלה, שבה נוספה אופציה לפתיחת לינקים של הרחבות מתוך טלויזיה חיה

**Comment by rafi-d** [comment]
לצערי אין מצב להריץ את גרסה 18 על הטיוי -בוקס שלי...
הקושחה שלה לא תתאים לזה
במה תומכים הקבצים האלו? 
מה מהקבצים האלו ניתנים לשימוש גם עם גירסה 17? 
למשל הEPG? בפורמט של הPVR?

הרעיון לנצל את  ממשק הPVR גם מבחינת EPG וגם להקלטות. זה יעבוד ב18?

תודה
רפי

**Comment by Fishenzon** [comment]
@rafi-d 
הקובץ של המדריך יעבוד בקודי 17.
הקובץ עם הלינקים עצמם לא יעבוד כי זה לינקים להרחבה וזה נתמך רק מקודי 18

**Comment by rafi-d** [comment]
תודה. חבל...
למעשה ב18 תתאפשר גם הקלטה או לא?

**Comment by Fishenzon** [comment]
@rafi-d 
לא יודע מה מפתחי קודי מתכננים לגבי הקלטות.
הקובץ בד"כ מעודכן 4-5 ימים קדימה

**Comment by rafi-d** [comment]
ניסיתי ואם לא טעיתי באיתור, הקובץ היחיד שאני רואה משתנה בזמן ההרצה -  הוא רשימת הערוצים ? 
idanplus.m3u
EPG בקובץ הזה? 
epg.xml.tar.gz

כי הוא לא השתנה אפילו אחרי איתחול קודי מחדש.

**Comment by Fishenzon** [comment]
@rafi-d 
כן אלו הקבצים.
מדריך השידורים מתעדכן רק כאשר מתעדכן קובץ מדריך השידורים של ההרחבה, וזה קורה רק אם המדריך בן יותר מ-24 שעות.
אתה יכול לעדכן אותו ידנית ע"י כניסה להגדרות של עידן פלוס ולחיצה על הורדת מדריך שידורים ידנית, אז תראה שהקובץ מתעדכן לך.

**Comment by Fishenzon** [comment]
@rafi-d 
גם קודי 17 יודע לקרוא את הקובץ הדחוס

**Comment by rafi-d** [comment]
אכן, עובד, תודה.
עוד עניין קטן - 
אני על חלונות 10 וכוון זמן - 
UTC+2 (ירושלים)  + כיוון שעון קיץ אוטומטי
השעון של חלונות נכון  (GMT + 3)
https://greenwichmeantime.com/time-gadgets/time-zone-converter/

הEPG יוצא שעה מוקדם יותר 
+2
אני יודע שאפשר לכוון בקודי את ההפרש, עדיין, האם זה תקין? לדעתי המחולל של הקובץ צריך לקחת את הזמן , המקומי על המחשב שלי נכון

**Comment by rafi-d** [comment]
עניין קטן נוסף - אם תוכל להוסיף ביצוע של 
PVR->CLEAR-DATA 
-מהתוכנה   כשאתה מעדכן לוח שידורים , כך שה
PVR CLIENT 
יטען את הלוח החדש כשהתעדכן לפחות בפעם הראשונה?
כך לא יווצר מצב שה
PVR 
עם רשימה/לוח ריקים, כי היא מתעדכנת רק כשקודי עולה, ולפני שהפעילו את התוסף.

**Comment by rafi-d** [comment]
הבנתי. העניין הוא שבקודי - בתוסף ה
PVR SIMPLE CLIENT 
יש בעיה לכוון את הזמן בכפולות של שעה. יש שם סליידר ולא ברור (לי) איך אפשר שם לשים +1... 
 
 אם זו בעיה בקודי אני לא רואה סיבה למה לא להקל ולא לקחת בתוסף בחשבון את שעון הקייץ, אלא רק את ה רק את איזור הזמן (כנראה זו הבעיה).
אפשרות אחרת - אולי לתת גם  בתוסף שלך כיוונון נומרי של שעות לסטיית זמן .

בעניין אחר - לאחר שבחלונות עבד לי,  ניסיתי להפעיל באנדרואיד 6.1 (TVBOX)
לצערי - לא עובד. יש לך מושג מה יכולה להיות הבעיה? יש טעם להעלות את הלוג של קודי עבורך?

**Comment by rafi-d** [comment]
ועוד מחשבה - יש אפשרות טכנית להוסיף בתוך התוסף (נניח במסך הראשי) עוד לחיץ שפשוט יפעיל את ממשק הPVR 
(לחיץ "TV" בסרגל הראשי?)

**Comment by rafi-d** [comment]
עוד שאלה - אין לי קודי 18, אבל נדמה לי שראיתי אצל חבר - שהלינקים לתוסף לא נפתחים כמו הרגילים - במסך קטן תחילה
אלא ישר במסך מלא, ועם תפריט  לא זהה בנגן (אין כפתור 
למשל EPG
 ואין יכולת חזרה למסך קטן או לקבל על הנגן את רשימת שאר הערוצים. זה אכן כך? יש מצב לשיפור?

תודה

רפי

**Comment by Fishenzon** [comment]
@rafi-d 
כנראה לא בדקתם נכון. הלינקים להרחבות נפתחים בדיוק כמו לינקים רגילים.

![image](https://user-images.githubusercontent.com/29551534/45092033-e3920b80-b11c-11e8-86be-a7b76874b1ae.png)

![image](https://user-images.githubusercontent.com/29551534/45092094-163c0400-b11d-11e8-8664-12964ddeda9b.png)

**Comment by rafi-d** [comment]
כנראה, מצטער. 👍 
מה לגבי דעתך שני ההערות/רעיונות הקודמים למעלה -?
עניין הזמן, והעניין הפעלת הממשק כולו (או ערוץ בודד בו) מתוך התוסף?

**Comment by Fishenzon** [comment]
@rafi-d 
אצלי זה עובד באנדרואיד.
לגבי קביעת אזור זמן ידני וקיצורים לטלויזיה חיה אוסיף כנראה בגירסה הבאה.

**Comment by rafi-d** [comment]
תודה!
יתכן לכדאי לציין בהערה שיעבוד רק ב
KODI 18
לא כ"כ קריטי מבחינת הזמן, כי כפי שאמרת, זה ניתן לכיוון ב CLIENT.

אני אבדוק שנית באנדרואיד. בהזדמנות

**Comment by Fishenzon** [comment]
@rafi-d 
הוצאתי גירסה 1.7.6
תחת רדיו ושידורים חיים תמצא קיצורים לטלויזיה חיה ורדיו של קודי.
בהגדרות של עידן פלוס בטלויזיה חיה תמצא הגדרה ידנית של איזור זמן ופתיחת הגדרות של טלויזיה חיה ולקוח טלויזיה חיה

**Comment by rafi-d** [comment]
זה רעיון טוב, מאוד נוח שהכל מרוכז במקום אחד במקום לבזבז זמו בניווטים בקודי... 
אם יש אפשרות לחזור לאחר הקינפוגים של 
הPVR וה CLIENT 
ואולי אפילו מיצירת הקבצים - ממש לאותו תפריט (שלך) כדי להמשיך - יהיה מצויין 
כעת חוזרים לתפריט הראשי וצריך שוב להכנס ....

איך גרסה 18? כבר יציבה?  לא נראה לי שאנשים עם קופסאות אנדרואיד יעיזו לשדרג, כי הרוב המקרים זה פשוט לא יעבוד להם מסיבות של אי תאימות לקושחה שלהם

**Comment by rafi-d** [comment]
נב:
MAKEלא נראה לי שהקבצים באמת נוצרים בלחיצה על ה
לפחות לא במקום הקודם...

**Comment by Fishenzon** [comment]
@rafi-d 
היתה באמת בעיה עם הכפתורים.
אין אפשרות לחזור לחלון ההגדרות, החלון צריך להיסגר כדי לבצע את הפקודה.
עכשיו בגירסה 1.7.7 זה חוזר להרחבה עצמה ואתה יכול ללחוץ שוב על הגדרות.

**Comment by rafi-d** [comment]
שגיאה בביצוע  MAKE
(אולי נובעת מזה שקודי כבר משתמש בקובץ?)

09:06:20.323 T:11732   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 13] Permission denied: 'D:\\Program Files\\Kodi\\portable_data\\userdata\\addon_data\\plugin.video.idanplus\\epg.xml.tar.gz'
                                            Traceback (most recent call last):
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus\default.py", line 277, in <module>
                                                MakeIPTVfiles()
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus\default.py", line 212, in MakeIPTVfiles
                                                iptv.MakeChannelsGuide()
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus\resources\lib\iptv.py", line 86, in MakeChannelsGuide
                                                with tarfile.open('{0}.tar.gz'.format(xmlFile), "w:gz") as tar:
                                              File "D:\Program Files\Kodi\system\python\Lib\tarfile.py", line 1693, in open
                                                return func(name, filemode, fileobj, **kwargs)
                                              File "D:\Program Files\Kodi\system\python\Lib\tarfile.py", line 1740, in gzopen
                                                fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
                                              File "D:\Program Files\Kodi\system\python\Lib\gzip.py", line 94, in __init__
                                                fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
                                            IOError: [Errno 13] Permission denied: 'D:\\Program Files\\Kodi\\portable_data\\userdata\\addon_data\\plugin.video.idanplus\\epg.xml.tar.gz'
                                            -->End of Python script error report<--

**Comment by rafi-d** [comment]
אופססס... טעות שלי
WINZIP קובץ היה פתוח אצלי בנפרד ב

**Comment by rafi-d** [comment]
שאלה: יש לך מושג האם הטאג - 
#EXTM3U x-tvg-url="<file url>"
אמור לעבוד גם ללא הגדרה בקליינט?
ניסיתי ולא נראה שעובד.

**Comment by Fishenzon** [comment]
@rafi-d 
אין לי מושג.
