### ISSUE TITLE
תקיעות בערוץ של קשת 12

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#51]
היי, משהו השתנה מבחינת העברת שידורי קשת? 
בימים האחרונים יש ממש תקיעות בעייתיות עד כדי הקפאה של התמונה (השידור לא נסגר), 
השאלה אם זה משהו אצלם או בתוסף שהשתנה?  

פעם קודמת אכן זו הייתה בעיה אצלי ושמתי לב מה גרם להאטה באינטרנט,
אבל עכשיו מהירות האינטרנט אצלי תקינה.

גירסה 2.4.3  

תודה מראש

**Comment by Fishenzon** [comment]
בוקר טוב.
לא נעשה שום שינוי, אצלי זה לא נתקע, 
יכול להיות שהתחילו לשדר באתר באיכות יותר גבוהה.
אתה יכול לנסות לבחור איכות נמוכה יותר ולאות אם יש שיפור.

**Comment by rafi-d** [comment]
משדרים ב  כבר זמן רב.p 900p

**Comment by burekas7** [comment]
@rafi-d 
כשאתה מציין 900p אתה מתכוון ל-1080, שהם כבר שנים משדרים באיכות הזו (לעומת רשת אגב, שתקועים על 720 עד היום)

בכל אופן, נראה שזה קשור לשעות העומס או משהו, זה מתחיל להתרחש באקראי החל מהשעה 19:00. אבל עדיין מוזר כי זה לא היה ככה מלא זמן, תמיד צפיתי ב-1080 בלי בעיות.

**Comment by rafi-d** [comment]
לא, אני מתכוון ל 
900p
לפי התוסף, זו האיכות המשודרת. קודי לא מבין את זה ומציג
1080p

**Comment by burekas7** [comment]
אבל אני בספק שאיכות 900 דורשת קצב אינטרנט גבוה משמעותית או שהמסך שלי מוגבל 1080 אז הוא מתקשה, כי כמו שציינתי בדקתי במהלך היום וזה פחות קרה (למרות ששוב צריך להשאיר את זה רצוף כדי לדעת, כי גם בערב היו פרקי זמן שהיו יחסית ללא תקיעות לאורך זמן, ואז זה התגבר בשעה מסוימת)

**Comment by rafi-d** [comment]
ממש לא נדרש קצב גבוה.
אגב, אצלי 100 מגה. 
יתכן ויש לך צרכנים אחרים שצורכים פס, או שהספקתי לא נותנת תמיד רוחב טוב . בדוק מהירות כשזה קורה.

**Comment by rafi-d** [comment]
אלו הנתונים (בהקשה על "O" במקלדת)
![Screenshot_20191225-231424](https://user-images.githubusercontent.com/2458280/71450543-8f28fa00-276c-11ea-997d-e13c57fb1a54.png)

**Comment by burekas7** [comment]
בדקתי בזמן שזה קרה.
בדר"כ אני מקבל קצב WIFI של 70-80 בממוצע, ספציפית בזמן התקיעות היה בסביבות ה-40.
אני אמשיך לעקוב נראה, אם אחרים לא מתלוננים אז משהו כנראה אצלי שגורם.

**Comment by ReuvenMash** [comment]
גם אצלנו ערוץ 12 נתקע אתמול עם buffering כל כמה שניות. אבדוק היום שוב

**Comment by Fishenzon** [comment]
אין לי כל כך מה לעשות עם זה.
זה מה שמגיע מהאתר.
אתם יכולים לבחור איכות ניגון נמוכה יותר ואולי זה יעזור.
