### ISSUE TITLE
VOD ערוץ 9 לא עובד

### ISSUE THREAD

**Issue by Tima-1980** [Fishenzon/repo#52]
שלום  חג חנוכה שמח
VOD ערוץ 9 לא עובד
http://www.9tv.co.il/

**Comment by Fishenzon** [comment]
תודה.
אבדוק מה השתנה באתר

**Comment by Fishenzon** [comment]
סידרתי לפי השינויים באתר

**Comment by Tima-1980** [comment]
תודה רבה  בינתיים לא רואים

**Comment by Tima-1980** [comment]
יש תודה
