### ISSUE TITLE
האח הגדול לייב

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#53]
היי

יש עדכון לגבי הערוץ?
הוא יתווסף לרשימת ערוצי הטלוויזיה?

ראיתי באחד העדכונים שציינת שהוספת, אבל הוא לא מופיע ברשימה.

תודה

**Comment by Fishenzon** [comment]
אם אתה לא רואה אותו ברשימות, תיכנס להגדרות של ההרחבה ותשנה את מיקום הערוץ ברשימה מאפס למיקום שאתה רוצה שהוא יופיע בו

**Comment by burekas7** [comment]
תודה הסתדר.
אגב לגבי המספור, לא הבנתי למה הוא לא נותן לי מספר אחד מעל האחרון.
או איך למשל אני שם אותו בין מספרים או ראשון, אני צריך לקדם את כולם באחד בעצם?

**Comment by Fishenzon** [comment]
או שתקדם את כולם או שתיתן לו מספר 1 ביחד עם ערוץ נוסף עם מספר 1.
אחד מהם יהיה ראשון ואחד שני. תנסה את מזלך

**Comment by burekas7** [comment]
ואם האחרון הנוכחי הוא למשל 20, למה אי אפשר להגדיר 21?
או בכללי, למה המספור לא עולה רציף, אחרי 20 קופץ הרי ל-100.
אם היה אפשר היה קל לשחק עם המיקום, אומנם לשנות את כולם אבל יכלת לבחור מי לפני מי.

**Comment by Fishenzon** [comment]
לא נראה לי שיש יותר מ-20 ערוצים.
בזמנו שמתי ב-100 את "רענון רשימה", ככה שאם אוסיף ערוצים זה ישאר אחרון.
מצד שני רציתי שאפשר יהיה להגיע לסוף או תחילת הרשימה מ-2 הכיוונים. ככה שאם יש לך ערוץ במיקום 18, אתה מעלה כלפי מעלה ומגיע מהר מאוד בחזרה ל-0.
אתה תמיד יכול לסדר את הרשימה לפי הסדר שאתה רוצה. אתה מסתיר ערוצים ע"י זה שאתה נותן להם את המספר 0
