### ISSUE TITLE
ערוץ האח הגדול

### ISSUE THREAD

**Issue by reves86** [Fishenzon/repo#54]
אהלן,

אחלה תוסף. ממש שמיש. שיחקת אותה!
בעיה קטנה ברשותך, ערוץ 26 לא עובד. טוען לשניה ופשוט מפסיק.

תודה

**Comment by Fishenzon** [comment]
הערוץ חסום לצפיה מחוץ לישראל.
אם אתה צופה מהארץ, תבדוק שגירסת ההרחבה מעודכנת.

**Comment by reves86** [comment]
10X
תודה רבה
