### ISSUE TITLE
האפליקציה קורסת בסטרמינג של עידן פלוס

### ISSUE THREAD

**Issue by ShlomoShai18** [Fishenzon/repo#55]
samsung galaxy note 9
android 10
Kodi v18.5 leia
בזמן שאני מפעיל שידורים חיים בעידן פלוס, האפליקציה קורסת לי והלוג מסתיים בשורות האלה
`2020-01-14 16:27:38.504 T:5360 NOTICE: Creating InputStream`
`2020-01-14 16:27:38.726 T:5360 NOTICE: Creating Demuxer`

ערוצים 11 ו 12 ו 13 עובדים
השאר מקריסים את האפליקציה
עד היום הכל עבד לי כמו שצריך
אבל יתכן שבגלל העדכון לאנדרואיד 10, ישנה בעיה
אשמח לעזרה, תודה רבה!

**Comment by ReuvenMash** [comment]
כנ"ל. חשבתי שזה רק אצלי.. הקודי קורס ויוצא. אחרי נסיון פעם פעמים זה מתייצב.
התחיל לאחרונה, על מיני פיסי W10
אולי משהו השתנה במקורות עצמם?

**Comment by ayv77054838282828** [comment]
( 10שלום יש לי גלקסי 10 פלוס (אנדרואיד
וההרחבה עידן פלוס בקודי לא עובדת לי בכלל (רק שידור של קשת 12 בשידור חי ) תודה מראש מחכה לתשובה

**Comment by Fishenzon** [comment]
אין לי כרגע איך לבדוק את זה.
אין לי מכשיר עם אנדרואיד 10.
אתם יכולים לצרף קובץ log ואולי אוכל לראות שם משהן.

**Comment by ShlomoShai18** [comment]
[kodi.log](https://github.com/Fishenzon/repo/files/4063314/kodi.log)

**Comment by ShlomoShai18** [comment]
[kodi.log](https://github.com/Fishenzon/repo/files/4063320/kodi.log)

**Comment by Fishenzon** [comment]
@ShlomoShai18 
אתה יכול להפעיל לוג מורחב?

**Comment by ShlomoShai18** [comment]
[kodi.log](https://github.com/Fishenzon/repo/files/4063369/kodi.log)

**Comment by Fishenzon** [comment]
תודה.
לא הצלחתי לראות משם מה הבעיה.
צריך לראות אם קודי יוציאו גירסה שתומכת טוב יותר באנדרואיד 10

**Comment by ShlomoShai18** [comment]
לי נראה בגלל שזה עובד על רנדר של אפל או משהו ואולי 
אנדרואיד 10/ סמסונג לא מסתדרת עם זה
נחכה שקודי יעדכנו את האפליקציה..
בכל מקרה תודה רבה על העזרה!!

**Comment by ayv77054838282828** [comment]
איך אני מוציא לוג?

בתאריך יום ד׳, 15 בינו׳ 2020, 14:27, מאת ShlomoShai18 ‏<
notifications@github.com>:

**Comment by ShlomoShai18** [comment]
@ayv77054838282828 
כנס לתיקיה
android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
לפני זה תפעיל לוג מורחב בתוך ההגדרות,מערכת, מצב מומחה, יומן אירועים, הפעל יומן רישום מורחב #

**Comment by ayv77054838282828** [comment]
הנה

בתאריך יום ד׳, 15 בינו׳ 2020, 19:05, מאת ShlomoShai18 ‏<
notifications@github.com>:

**Comment by Fishenzon** [comment]
בוקר טוב.
נא לעדכן לקודי 18.7 ולבדוק אם נפתרה הבעיה.

**Comment by ShlomoShai18** [comment]
תודה רבה! לפי מה שזה נראה זה הסתדר
