### ISSUE TITLE
ההרחבה לא עובדת לי 

### ISSUE THREAD

**Issue by ayv77054838282828** [Fishenzon/repo#56]
( 10שלום יש לי גלקסי 10 פלוס (אנדרואיד  
וההרחבה עידן פלוס בקודי לא עובדת לי בכלל (רק שידור של קשת 12 בשידור חי ) תודה מראש מחכה לתשובה

**Comment by Fishenzon** [comment]
בוקר טוב.
ראיתי כבר את ההודעה שלך, אין צורך לפתוח בקשה נוספת
