### ISSUE TITLE
ערוץ 13 VOD

### ISSUE THREAD

**Issue by ellabloch** [Fishenzon/repo#57]
הרבה תכניות חסרות או לא מנגנות ב-VOD של ערוץ 13
לדוגמה, חדשות - המהדורה המרכזית, משחקי השף

תודה רבה!

**Comment by rafi-d** [comment]
אצלי כל הנ"ל נראה תקין (בגרסה 2.5.4)
מציע שתשתפי פרטים נוספים כגון גירסה של התוסף ומערכת ההפעלה תחתה הוא פועל...
אין טעם שננחש...

**Comment by ellabloch** [comment]
תודה רבה על המענה המהיר! ניקיתי Cache אחרי העדכון מהמקור שלכם וזה פתר הכל.
