### ISSUE TITLE
Kodi 19 support

### ISSUE THREAD

**Issue by baerlein** [Fishenzon/repo#58]
הי
יש מצב להוסיף תמיכה לגרסה 19 של קודי?

`2020-02-04 18:22:10.428 T:6192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'ModuleNotFoundError'>
                                            Error Contents: No module named 'urlparse'
                                            Traceback (most recent call last):
                                              File "C:\Users\leo\AppData\Roaming\Kodi\addons\plugin.video.idanplus\default.py", line 2, in <module>
                                                import sys, os, urlparse, urllib, datetime, json
                                            ModuleNotFoundError: No module named 'urlparse'
                                            -->End of Python script error report<--
2020-02-04 18:22:10.445 T:8400   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.idanplus/
2020-02-04 18:22:10.445 T:8340   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.idanplus/) failed`

**Comment by Asafco123** [comment]
מצטרף לבקשה

**Comment by oferchen** [comment]
hi,
In kodi v19 the python version was changed to python3 is it possible to make the necessary modifications so that the addon will work again?

thanks!

**Comment by Fishenzon** [comment]
שבוע טוב.
יקח לי קצת זמן להתאים את ההרחבה לקודי 19.
הוא עדיין בגירסת אלפא אבל אמצא לזה זמן

**Comment by Fishenzon** [comment]
אתם מוזמנים לבדוק את גירסה 2.5.7 על קודי 19

**Comment by oferchen** [comment]
Excellent work, most of what I tested if functioning as expected.
Thank you!

**Comment by oferchen** [comment]
> אתם מוזמנים לבדוק את גירסה 2.5.7 על קודי 19

Excellent work, most of what I tested if functioning as expected.
Thank you!

**Comment by baerlein** [comment]
עובד, תודה!
