### ISSUE TITLE
גב האומה לא עובד

### ISSUE THREAD

**Issue by Jool-Pi** [Fishenzon/repo#59]
הי,

מזה כמה שבועות העונה החדשה של גב האומה לא עובדת. אפשר עדיין לראות את כל הפרקים של עונה 10 אבל שלוחצים על עונה 11 הספרייה ריקה למרות שיש כבר פרקים חדשים
תודה מראש
גל

**Comment by Fishenzon** [comment]
שבוע טוב.
זה עובד בסדר גמור.
בדוק שההרחבה אצלך מעודכנת לגירסה האחרונה.

**Comment by Jool-Pi** [comment]
עידכנתי גירסה וזה עובד!תודה


Sent from Yahoo Mail for iPhone


On Sunday, February 9, 2020, 7:18 AM, fishenzon <notifications@github.com> wrote:


שבוע טוב.
זה עובד בסדר גמור.
בדוק שההרחבה אצלך מעודכנת לגירסה האחרונה.
