### ISSUE TITLE
EPG "untill" timestamps - are wrong

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#6]
They are all +1 hour. A summer-time clock shift issue? Or a mistake at the source...

**Comment by Fishenzon** [comment]
@rafi-d 
שבוע טוב.
אתה מוזמן לבדוק שוב, המדריך שבדקת נוצר בזמן שעון חורף, המדריך הנוכחי נוצר בשעון קיץ.

**Comment by rafi-d** [comment]
אכן, נראה תקין כעת. תודה
