### ISSUE TITLE
ערוץ 13 לא עובד וגם לוח השידורים

### ISSUE THREAD

**Issue by adieldarhome** [Fishenzon/repo#60]
שלום
מזה כשבועיים שלושה ערוץ 13 חי לא עובד וגם לוח שידורים כותב על כל הערוצים "נעשה שימוש בגירסה ישנה (c) פישנזון
בדקתי והגרסה המותקנת שלי היא 
nil 2.4.3
ניסיתי לעדכן אבל זאת הגירסה האחרונה
אשמח לפיתרון
תודה!
עדי

**Comment by Fishenzon** [comment]
שלום.
זאת ממש לא הגירסה האחרונה.
אם הריפו לא מותקן אצלך, תתקין אותו מפה:
https://fishenzon.github.io
הגירסה האחרונה היא 2.5.4:
https://github.com/Fishenzon/repo/raw/master/zips/plugin.video.idanplus/plugin.video.idanplus-2.5.4.zip

**Comment by adieldarhome** [comment]
תודה רבה!
עדכנתי ל 2.5.4. וערוץ 13 עובד! אבל לוח השידורים עדיין לא עובד וכותב כנ"ל

**Comment by Fishenzon** [comment]
אתה יכול להיכנס להגדרות של ההרחבה וללחוץ שם על הורדת מדריך שידורים ידנית.
אתה יכול גם פשוט לחכות למחר, מדריך השידורים מתעדכן במכשיר רק אם עברו 24 שעות מהעדכון האחרון.

**Comment by adieldarhome** [comment]
המון תודה, הכל עובד יופי!
