### ISSUE TITLE
Error message on the channel list

### ISSUE THREAD

**Issue by agmonr** [Fishenzon/repo#63]
Got an error "נעשה שימוש בגירסה ישנה" '
when accessing the programs list. 
version 2.5.5 installed manually from the file system.
Using LibreELEC (official): 9.0.2 (RPi2.arm)

**Comment by Fishenzon** [comment]
לילה טוב.
כנראה שהיתה מותקנת לך גירסה ישנה לפני כן.
אתה יכול לנסות לעדכן את מדריך השידורים דרך ההגדרות של ההרחבה

**Comment by agmonr** [comment]
עובד. מגניב. המון תודה. תוסף נהדר. עזרת לנו לחתוך את הכבלים. :)
