### ISSUE TITLE
kodi 18.6  לא מצליח לחבר להרחבה

### ISSUE THREAD

**Issue by Tima-1980** [Fishenzon/repo#67]
שלום חנוכה שמח
הורדתי קודי 18.6
ולא מצליח לחבר ביין PVR לביין ערוצים של הרחבה

**Comment by dikodahan** [comment]
I am experiencing the same issue here.
Seems like Kodi v18.6 changed something the breaks this capability. Works without any issues on v18.5

**Comment by rafi-d** [comment]
מה בדיוק לא עובד ? מה הכוונה "לחבר ביין" הערוצים?

**Comment by dikodahan** [comment]
Under "Live TV" in the configuration you have an option to have your plugin configure the IPTV plugin with the necessary configuration so that Kodi's live tv capability will be connected to Idan Plus.
When clicking on that option, it doesn't do anything.

**Comment by Tima-1980** [comment]
שערוצים יעברו ל PVR

**Comment by rafi-d** [comment]
Is the manual configuration still working with 18.6 (using IDAN+ EPG only, and external channels' links/list)?
( https://www.hometheater.co.il/vt296401.html )

**Comment by dikodahan** [comment]
Working with the addon directly, no issues. channels are streaming properly.

On my Adnroid systems I just upgraded from 18.5 to 18.6 and no issues as the configuration was done while on 18.5.
This issue I am experiencing right now is with a fresh build running on a Mac. Haven't checked to see if the same behavior is on Android as well, cause I don't want to mess it up on my main TVs... :)

**Comment by rafi-d** [comment]
שוב, מציע עד שיסוטדר, שתעבור ותנסה קיפוג ידני כמו שמוסבר בלינק שנתתי
(משתמש ברשימת ערוצים חיצונית מהאינטרנט שזהה לזו של התוסף)

**Comment by Fishenzon** [comment]
אצלי עובד בלי בלי בעיה בוינדוס.
היתה בעיה שתיקנתי בגירסה 2.6.0 שלחיצה בהגדרות ההרחבה על הגדרה לשימוש ברשימות של ההרחבה גם ב- iptv simple client לא עבדה.
צריך לשים לב ש- iptv simple client לא מנוטרל.
כמו כן, אחרי שינויים, צריך לפעמים להפעיל מחדש את קודי
בכל מקרה, אני לא יודע מה יש ברשימות חיצוניות שאני לא יצרתי, אז זה נתון לשיקול דעתכם.

**Comment by dikodahan** [comment]
I downloaded 2.6.0 version (since you still don't have it listed in the repo for update). Manually updated to it.
I can confirm that the issue is solved on my end!
Thanks!!!

**Comment by Fishenzon** [comment]
שמח שהסתדר לך,
דרך אגב, זה כן נמצא בריפו

**Comment by Tima-1980** [comment]
תודה רבה
