### ISSUE TITLE
Reshet VOD not playing

### ISSUE THREAD

**Issue by talneder** [Fishenzon/repo#68]
Debug log:
https://pastebin.com/cExQW9AV

**Comment by Fishenzon** [comment]
יכול להיות שיש עומס באתר, מתי ניסית?
אתה מנסה מהארץ או מחו"ל?
תוודא שיש לך גירסה אחרונה של ההרחבה 2.6.0

**Comment by talneder** [comment]
מחו"ל אבל ההתנהגות לא אחידה ולכן אני מאמין שזה באג בתוסף-
פרק 34 של האח הגדול עובד תקין
פרק 33 או 35 לא עובדים

**Comment by Fishenzon** [comment]
בדקתי וכל הפרקים עובדים.
זה דווקא נראה שזה משהו באתר, או שהם חוסמים מחו"ל או משהו שקשור לעומסים.

**Comment by talneder** [comment]
אוקיי
האם התוסף תומך בפרוקסי? 
יש אפשרות להגדיר פרוקסי בהגדרות של קודי אבל אני לא יודע אם זה משפיע על תוספים

**Comment by Fishenzon** [comment]
אין התייחסות לפרוקסי בהרחבה.
לא ניסיתי אף פעם להשתמש בפרוקסי בקודי

**Comment by rafi-d** [comment]
בדקתי עם VPN לארהב ואכן יש את הבעיה שתיארת
פרוקסי לא עזר.

**Comment by talneder** [comment]
באסה. תודה

**Comment by rafi-d** [comment]
תוכל לוודא עי גישה ישירה  דרך אתר רשת . אמור להיות חסום גם שם. 
אם לא, זו בעיה של התוסף.
