### ISSUE TITLE
איכות השידור של רשת ירד

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#69]
ביממה האחרונה איכות השידור בערוצים של רשת (רשת + האח הגדול) ירדו מ-720 ל-540

הם מספקים איכות גבוהה בקישור חדש או שזה המקסימום אצלם כרגע?

תודה מראש

**Comment by rafi-d** [comment]
גם אני מוחה על האיכות הירודה....  :(

**Comment by burekas7** [comment]
הקישורים שנתנו סטרימינג של 720 הפסיקו לעבוד משום מה.
אבל גם לפני, שנת 2020 והם עדיין תקועים מאחור ולא שידרו ב-1080 לפחות.
קשת לעומתם כבר שנים רצה על איכות גבוהה באינטרנט.

**Comment by rafi-d** [comment]
יש חלופה לא רעה -  IZEE TV 
https://play.google.com/store/apps/details?id=iztv.app&gl=IL

אולי כדאי לברר אצלם מאיפה הם לוקחים רת השידור החי של רשת, כי נראה שהם מצליחים להשיג מקור באיכות גבוהה!

**Comment by burekas7** [comment]
אני מניח שזה כנראה לא מהאתר של רשת עצמו, כי התוסף תמיד משתדל להתעדכן עם האיכות המירבית. זה בטח מקור פרטי או שחיברו את הוט\יס לשרת פרטי ומזרימים.

**Comment by rafi-d** [comment]
היות וזו אפליקציה חוקית, חינמית, שגם מופצת עי גוגל, כל מה שאמרתי, שאולי כדאי למפתח התוסף להתעניין מה המקור שלהם.

ברור שהם גם מחזיקים שרת ביניים שלהם, אליו מתחברים.
