### ISSUE TITLE
ערוץ האונליין N12

### ISSUE THREAD

**Issue by hugo46** [Fishenzon/repo#71]
היי, בעבר היה ברשימה ערוץ החדשות
היום הוא הפך לערוץ N12 של האפליקציה
אפשר להכניסה אותו לרשימה?

https://keshethlslive-lh.akamaihd.net/i/c2n_1@195269/index_3100_av-p.m3u8

תודה

**Comment by Fishenzon** [comment]
תודה.
הוספתי

**Comment by ReuvenMash** [comment]
אתה איש יקר! תודה על הכל!
