### ISSUE TITLE
Kodi 19 installation error

### ISSUE THREAD

**Issue by oferchen** [Fishenzon/repo#72]
I'm using Kodi 19 Milhouse latest build from [here](http://milhouse.libreelec.tv/builds/master/Generic/LibreELEC-Generic.x86_64-9.80-Milhouse-20200317214242-%230317-g9542570.tar)
when I try to install from repository I'm receiving a message that the dependancy xbmc.python version 2.1.0 could not be met.

Thanks!

**Comment by Okoyl** [comment]
same here, kodi 19 on Libre-elec.

Thank you

**Comment by Fishenzon** [comment]
חג שמח
מחקתי את השורה הזאת בגירסה 2.6.2
תבדקו אם אתם מצליחים להתקין
