### ISSUE TITLE
VOD של כאן 11 - לא מנגן

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#76]
נראה לי שהתצוגה של הספריות - תקינה רק שבכולן התוכן לא מתנגן
"FAIL TO PLAY"

**Comment by Fishenzon** [comment]
תוכל לתת דוגמה?
יש תכנים שמתנגנים דרך יוטיוב ואז אתה תלוי בהרחבה של יוטיוב או MyYoutube שאפשר לבחור בהגדרות של ההרחבה.
חלק מהתכנים מתנגנים דרך לינק ישיר מאתר כאן.
בדקתי כרגע פרקים משתי סדרות (זהו זה ושטוקהולם) ושניהם התנגנו.

**Comment by rafi-d** [comment]
אכן, אצלי היה משום מה על
MyYouTube
ברגע ששיניתי ל
YouTube 
הסתדר. כנראה שהאיש העדכונים שלך השתנה הקינפוג....
אגב, מדוע לא לבדוק מה מותקן ופשוט להציג אזהרה ברורה גם במסך הקינפוג, וגם כשמנסים לנגן עם הרחבה שלא קיימת?

**Comment by Fishenzon** [comment]
לרוב האנשים ההרחבה של יוטיוב לא עובדת בלי API אישי.
בהרחבה הוגדרה ההרחבה של MyYoutube בתור ברירת מחדל כי היא לא דורשת API.
אם לא מותקנת בקודי הרחבה שמנסים לגשת אליה, קופצת הודעה ולחיצה על אישור מתקינה את ההרחבה החסרה.
זה עבר באופן חלק לכל המשתמשים חוץ מהפעם שאתה מתלונן על זה.
מי שיש לו API אישי, יש מצב יותר גדול שידע גם לשנות בהגדרות של ההרחבה שהיא תשתמש ביוטיוב הרגיל.
לרוב המשתמשים שאין להם מושג, עדיף שזה יעבוד כמו שזה עובד עכשיו (זה עובד ככה כבר כמה חודשים וגירסאות)

**Comment by rafi-d** [comment]
בדקתי שוב ואכן, בזמנו טרחתי והגדרתי API אישי בYOUTUBE 
בנוסף  במצב השגוי שאצלי (שלא עבד) לא הופיעה שום הודעה, הוא פשוט לא ניגן כלום
לאחר ההערות שלך, בדקתי את עצמי, ואכן מותקנת אצלי גם ההרחבה MYYOUTUBE
רק שאצלי היא לא מאופשרת.... !
במצב הזה - התוצאה היתה שאין שום הודעה.. 

אז לשיקולך מה לעשות אם בכלל

תודה

רפי

אם תרצה - סגור את הISSUE.
