### ISSUE TITLE
ערוץ הכנסת לא עובד

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#77]

**Comment by Fishenzon** [comment]
תודה.
בדוק את גירסה 2.6.4

**Comment by rafi-d** [comment]
תוקן, תודה
שאלה/הצעה - אולי יש לך רעיון: יש באותו אתר גם שידורים ישירים מוועדות הכנסת
הבעיה, שלכל וועדה נראה שיש את ה
FEED 
שלה
אולי יש לך רעיון אם אפשר לשלב את שידורי הוועדות גם בתוסף?

**Comment by rafi-d** [comment]
VOD, אולי להכניס את הערות/אתר גם לקטגורית 
ושם לתת מחיצות לפי וועדות
ואז לכל וועדה גם  לינק לשידור חי?

**Comment by Fishenzon** [comment]
השידורים החיים של הוועדות הם רק בשעות מסויימות.
לא נראה לי שזה שווה את המאמץ

**Comment by rafi-d** [comment]
יש בזה משהו. אבל חבל
