### ISSUE TITLE
תקיעות בשידורי קשת

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#79]
גם לכם ביממה האחרונה יש תקיעות בשידורי קשת (לייב ו-וי.או.די) ?

לא יודע אם זה קשור לגירסה האחרונה 2.6.4 או לקשת עצמם.
מהירות האינטרנט נבדקה והיא תקינה.

**Comment by ReuvenMash** [comment]
כבר כשבוע ערוץ 12 לא מתפקד

**Comment by rafi-d** [comment]
זה רק בתוסף או גם ישירות באתר שלהם? 
אני צופה דרך אפליקציה אמנם, אך לא רואה כל בעיה.

**Comment by Fishenzon** [comment]
אני צפיתי עכשיו בפרק יותר מ-20 דקות בלי שום תקיעה

**Comment by Fishenzon** [comment]
בדקתי שידור חי ויש באמת תקיעות כל כמה דקות

**Comment by ReuvenMash** [comment]
על שני מכשירי ווינדוס ומכשיר אחד עם LibreELEC, לחיצה על ערוץ 12: סימן המתנה ארוך שנגמר ללא כלום. 
בדיקה ישירות באתר 12: ממתין ללא סוף בנסיון להתחבר. אני מניח שהבעיות אצלם.
בדקתי שוב הבוקר: עדכנתי את ההרחבה (למרות שזו אותה גרסה) ולאחר כמה נסיונות חזר לעבוד.
אני כמעט בטוח שהבעיה לא בהרחבה.

**Comment by rafi-d** [comment]
אולי עשו הגנה משופרת?...

**Comment by burekas7** [comment]
מהצפייה היום נראה שהשידורים יותר יציבים.
אני סוגר כאן לבינתיים.
