### ISSUE TITLE
Reshet VOD - After the fix in 1.2.8 - Still many "seasons" are missing

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#8]
קודי 17.6 - WIN/ANDROID :
עדיין לא מוצגות עונות רבות ברשת וויאודי המתוקן
מצרף שתי דוגמאות (המירוץ למדליון ו מהפכה במטבח)

בנוסף, תוסף קשת העצמאי - הפסיק לפעול....

![1](https://user-images.githubusercontent.com/2458280/38199908-12bd7446-369b-11e8-86f1-437dd06b2600.png)

**Comment by Fishenzon** [comment]
@rafi-d 
בדוק את גירסה 1.2.9

הוספתי הרחבה של עידן פלוס בנוסף לשידורים החיים את מה שהיה בהרחבות כאן, עשר, רשת ומאקו.
הסרתי את ההרחבות הישנות מהרפו ואת העדכונים אני מבצע רק בהרחבה של עידן פלוס (ובהרחבה של וואלה אם יש שינויים באתר)

**Comment by rafi-d** [comment]
תודה, נראה הרבה יותר "מלא" מבחינת עונות 
לפחות ב WINDOWS 
בהזדמנות אסתכל גם באנדרואיד.

רפי
