### ISSUE TITLE
נעלם הלינק לערוץ הספורט

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#82]
סתם ככה נעלם לו הלינק מהרשימה.
התקנתי שוב - ועדיין איננו. 
מדובר תחת אנדרואיד

ראית  דבר כזה? 

אגב, בדקתי ב
PVR-LIVE-TV - הערוץ קים ועובד (גרסה 17.6 - לינקים ישירים שלי)

**Comment by rafi-d** [comment]
מצרף תמונת מסף מאתמול
![Screenshot_20200728-224420](https://user-images.githubusercontent.com/2458280/88842935-f6b69480-d1e8-11ea-9521-22f1cf887b2c.png)

היום המצב תקין. נשאר לי להניח שיש איזו בעיה שאולי קשורה ללוגיקה סביב עומס על שרת הערוץ ? היה גמר גביע אתמול....

**Comment by Fishenzon** [comment]
אין סיבה שלא יופיע לך הערוץ, מקסימום הוא לא יתנגן אם יש בעיה במקור או שינוי באתר
יכול להיות שהיה מסומן לך להסתיר פריטים שנצפו

**Comment by rafi-d** [comment]
כעת בסדר. סוגר
