### ISSUE TITLE
הרחבת עידן פלוס בקודי לא עדכנית

### ISSUE THREAD

**Issue by nsdav877** [Fishenzon/repo#83]
שלום רב
יש לי קודי גרסה 18.7 על סטרימר אנדרואיד 6.01 עם הריפו שלכם גרסב 1.0.0
עדכנתי מתוך הריפו את הרחבת עידן פלוס לגרסה2.7.0
הערוצים עובדים כולל ה
VOD
כאשר אני נכנס לערוצים נרשם לי שהגרסה לא עדכנית, אין לוח שידורים והשעה לא מעודכנת
?האם יש דרך לסדר את זה? או איך לעדכן את ההרחבה
תודה
נדב

**Comment by Fishenzon** [comment]
יכול להיות שהיתה לך גירסה ישנה מאוד לפני העדכון.
המדריך מתעדכן פעם ביום, לכן אולי לא התעדכן לך עדיין.
יש אפשרות להיכנס להגדרות של ההרחבה וללחוץ על הורדת מדריך שידורים.
אתה יכול גם להמתין יום ולבדוק אם התעדכן לך מעצמו.

**Comment by nsdav877** [comment]
תודה


עדכנתי ידנית את לוח השידורים עכשיו יש לוח שידורים רק בחלק מהערוצים ובחלק עדיין רשום שהגרסה לא עדכנית


דבר שני ראיתי שהערוצים שם לא באיכות HD לפי הגדאות הוידאו בכל ערוץ אני יודע שבממיר של עידן פלוס יש את כאן 11 ב1080P וחלק מהערוצים משודרים באינטרנט באיכות 720P




‏נשלח מ-LG Mobile שלי







On Thu, Jul 30, 2020 at 9:50 AM +0300, "fishenzon" <notifications@github.com> wrote:















יכול להיות שהיתה לך גירסה ישנה מאוד לפני העדכון.

המדריך מתעדכן פעם ביום, לכן אולי לא התעדכן לך עדיין.

יש אפשרות להיכנס להגדרות של ההרחבה וללחוץ על הורדת מדריך שידורים.

אתה יכול גם להמתין יום ולבדוק אם התעדכן לך מעצמו.

**Comment by Fishenzon** [comment]
לא נראה הגיוני שחלק השתנה וחלק לא,
לגבי איכות השידור, אין קשר למה שיש לך בממיר.
מקורות השידור מגיעים מהאתרים השונים

**Comment by nsdav877** [comment]
תודה על התשובה המהירה


אני יכול לצלם לך את המסך שתראה?




‏נשלח מ-LG Mobile שלי







On Thu, Jul 30, 2020 at 11:35 AM +0300, "fishenzon" <notifications@github.com> wrote:
















לא נראה הגיוני שחלק השתנה וחלק לא,


לגבי איכות השידור, אין קשר למה שיש לך בממיר.


מקורות השידור מגיעים מהאתרים השונים

**Comment by Fishenzon** [comment]
הסתדר לך לוח השידורים?

**Comment by nsdav877** [comment]
תודה ששאלתהכן עכשיו יש לוח שידורים בכל הערוציםוכל הערוצים עובדיםנדב
    ביום שני, 3 באוגוסט 2020, 15:46:02 GMT‎+3‎,‏ fishenzon<notifications@github.com>‏ כתב/ה:  
 
 


הסתדר לך לוח השידורים?

**Comment by Fishenzon** [comment]
מעולה
