### ISSUE TITLE
VOD  כאן11 - באנדרואיד - כניסה לבחירת פרקים ותוכניות - איטית

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#84]
שלום,
באנדרואיד, התחילה להיות איטיות עד כדי תקיעה בעת בחירת לינק של תוכנית מסויימת. אצלך תקין?
גם בהצגת רשימת תוכניות יש השהיה של דקות ארוכות מאוד.

 קודי 18.6 אנדרואיד 9 

ב - WINDOWS-   נראה תקין

**Comment by rafi-d** [comment]
בדקתי גם ב
VOD 
של רשת/קשת ושם הכל תקין ומהיר

**Comment by rafi-d** [comment]
בדקתי את הלוג דיבאג, ראיתי הרבה שגיאות מהתוסף בנוסך:
מנסה לקרוא קונפיגורציה ולא מצליח, מנסה בפורמט הקודם.

התקנתי מחדש, והמצב השתפר בהרבה

גם ניסיתי לקנפג ללא IPV6 בנתב
ולקבל כתובת חדשה

אחד מהשניים עזרו כנראה...

**Comment by rafi-d** [comment]
נראה תקין . סוגר.

**Comment by pashosh** [comment]
יופי אפשר להגיב גם כשסגור.
בכל אופן מצאתי את הפוסט הזה בעזרת חיפוש של גוגל עבור ipv6 וקודי.
אז מסתבר שהערב, אחרי שלא הייתה בעיה עם זה בכלל, מספר ערוצים חיים (דרך התוסף עידן+) הפסיקו לעבוד בקודי שעל המחשב שלי (לינוקס).
בדקתי את 13 ו-14 ושניהם לא עבדו.
כאן 11 וערוץ 12 דווקא המשיכו לעבוד.
ביטלתי בראוטר את ip6 ולפתע הכל חזר לעבוד.
כמובן הפעלתי מחדש את ip6 ובדקתי שוב כדי לוודא ואכן הערוצים הבעייתיים חזרו להיות בעייתיים.
אז לבינתיים אני מבטל את ip6 מהראוטר.
אין לי מושג למה אני צריך את זה בעצם.
