### ISSUE TITLE
VOD כאן 23

### ISSUE THREAD

**Issue by dzisu** [Fishenzon/repo#87]
כאשר נכנס ל VOD כאן 23 התכנה נתקעת ונדרש אתחול התוכנה. משתמש ב- libreelec במחש נייד.

תודה רבה על התוסף המצויין הזה!

**Comment by Fishenzon** [comment]
תודה.
לא שמתי לב להודעה.
תבדוק את גירסה 2.7.7

**Comment by dzisu** [comment]
2.7.7 פתרה את הבעיה
ממש תודה 👍
