### ISSUE TITLE
ערוץ 13 (רשת) לייב הפסיק לעבוד

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#88]
יש בעיה הערב לגבי ערוץ 13 לייב.
באתר שלהם הלייב עובד.

**Comment by Fishenzon** [comment]
המקור באתר שונה, אני לא יודע אם זה קבוע.
הוצאתי בינתיים גירסה 2.7.4 שבה הלינק של 13 גיבוי זה ללינק שבאתר

**Comment by burekas7** [comment]
ביצעתי עדכון לגירסה החדשה, אבל עדיין הוא לא מנגן.
ביצעתי גם "רענון רשימה" ולא עזר.

**Comment by Fishenzon** [comment]
אתה צריך לבדוק את הלינק של 13 גיבוי, לא את 13 הראשי.
אני לא יודע עדיין אם זה שינוי קבוע או לא

**Comment by burekas7** [comment]
הבנתי.
גיבוי עובד תקין.
נחכה תקופה מסוימת, אם הראשי לא יחזיר אז כדאי להגדיר את הגיבוי כראשי.

תודה רבה.

**Comment by Fishenzon** [comment]
לילה טוב.
הגדרתי את הלינק הראשי של ערוץ 13 וגם של לקויי השמיעה ללינקים החדשים

**Comment by burekas7** [comment]
תודה
