### ISSUE TITLE
Vod wont play

### ISSUE THREAD

**Issue by FalconEagleTest** [Fishenzon/repo#89]
hi,
there is an issue with 2.7.7 in idan plus,
the amazing race older then season 8 episode 12 wont play, not s08e10,s08e09.
thanks

**Comment by Fishenzon** [comment]
Hi,
The links in the website changed last week.
Those episodes not working in website too.
They wrote that you can watch only for 12 days after the episode aired.

**Comment by Fishenzon** [comment]
@rafi-d 
Probably they didn't finished with all changes.
I checked again now, episode 11 is working now,
