### ISSUE TITLE
שליטה בתצוגת רשימת הערוצים

### ISSUE THREAD

**Issue by m1tm** [Fishenzon/repo#9]
תודה על ההרחבה, עוזרת לי המון.
תוכל להוסיף אפשרות לשליטה ברשימת הערוצים, שאפשר יהיה להסתיר דברים, למשל את 2 השורות הראשונות או ערוץ שאני לא צופה בו?

**Comment by rafi-d** [comment]
"Update failed"

**Comment by Fishenzon** [comment]
@rafi-d
נראה כמו משהו נקודתי אצלך.
אתה יכול לנסות להסיר ולהתקין מחדש את ההרחבה

**Comment by rafi-d** [comment]
כנראה שאתה צודק, אצלי רצה אפליקציה עם פייטון חדש יותר, בנוסף ההתקנה אצלי STANDALONE.   כשהפסקתי את האפליקציה ההיא - ההתקנה הצליחה.

בכ"א אלו השגיאות שדווחו בלוג, אולי זה יעזור לך לעזור לאחרים...:





20:33:45.852 T:8476   ERROR: Failed to rename file/directory \\?\D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus to \\?\D:\Program Files\Kodi\portable_data\addons\temp\cc5cd85d-3a34-4440-b37b-37258d9fb284, Error:
20:33:45.852 T:8476   ERROR: XFILE::CFile::Rename - Error renaming file D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus
20:33:45.852 T:8476   ERROR: Failed to move old addon files from 'D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus' to 'D:\Program Files\Kodi\portable_data\addons\temp\cc5cd85d-3a34-4440-b37b-37258d9fb284', retrying in 500ms
20:33:46.354 T:8476   ERROR: Failed to rename file/directory \\?\D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus to \\?\D:\Program Files\Kodi\portable_data\addons\temp\cc5cd85d-3a34-4440-b37b-37258d9fb284, Error:
20:33:46.354 T:8476   ERROR: XFILE::CFile::Rename - Error renaming file D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus
20:33:46.354 T:8476   ERROR: Failed to move old addon files from 'D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus' to 'D:\Program Files\Kodi\portable_data\addons\temp\cc5cd85d-3a34-4440-b37b-37258d9fb284', retrying in 500ms
20:33:46.856 T:8476   ERROR: Failed to rename file/directory \\?\D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus to \\?\D:\Program Files\Kodi\portable_data\addons\temp\cc5cd85d-3a34-4440-b37b-37258d9fb284, Error:
20:33:46.856 T:8476   ERROR: XFILE::CFile::Rename - Error renaming file D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus
20:33:46.856 T:8476   ERROR: Failed to move old addon files from 'D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus' to 'D:\Program Files\Kodi\portable_data\addons\temp\cc5cd85d-3a34-4440-b37b-37258d9fb284', retrying in 500ms
20:33:47.358 T:8476   ERROR: Failed to rename file/directory \\?\D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus to \\?\D:\Program Files\Kodi\portable_data\addons\temp\cc5cd85d-3a34-4440-b37b-37258d9fb284, Error:
20:33:47.358 T:8476   ERROR: XFILE::CFile::Rename - Error renaming file D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus
20:33:47.358 T:8476   ERROR: Failed to move old addon files from 'D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus' to 'D:\Program Files\Kodi\portable_data\addons\temp\cc5cd85d-3a34-4440-b37b-37258d9fb284', retrying in 500ms
20:3

**Comment by m1tm** [comment]
תודה רבה!
בקשה נוספת, תוכל להחליף את הלאיקונים של הערוצים שיהיו בגודל אחיד?
אני מצרף כמה איקונים שתוכל לראות.
[idan.zip](https://github.com/Fishenzon/repo/files/1942584/idan.zip)

**Comment by Fishenzon** [comment]
@m1tm 
תודה, אחליף את הקבצים הרלוונטים בחדשים.
אני לא מתעסק בגרפיקה, אם יש לך קבצים לשאר התמונות אתה מוזמן לשלוח

**Comment by m1tm** [comment]
בבקשה כל הסמלים
תודה
[idan.zip](https://github.com/Fishenzon/repo/files/1943910/idan.zip)

**Comment by Fishenzon** [comment]
@m1tm 
תודה

**Comment by rafi-d** [comment]
שכחתם את הלוגו הראשי של התוסף....  ;P
