### ISSUE TITLE
תחנת רדיו ישראלית חדשה בספה רוסית 106.4 FM 

### ISSUE THREAD

**Issue by Tima-1980** [Fishenzon/repo#91]
תחנת רדיו ישראלית חדשה בספה רוסית 106.4 FM 
שם Лучшее Радио
אתר https://radio1064.co.il/
URL  https://a2.streamgates.net/TheBest/live/chunks.m3u8?
תוכניות של רדיו  https://radio1064.co.il/podcasts

אם צריך עזרה עם שפה בבקשה

תודה רבה

**Comment by Fishenzon** [comment]
תודה.
אנסה למצוא לזה זמן

**Comment by Tima-1980** [comment]
תודה רבה

**Comment by Fishenzon** [comment]
בוקר טוב.
הוספתי את התחנה לרדיו ואת התכניות רדיו

**Comment by Tima-1980** [comment]
תודה רבה
