### ISSUE TITLE
קובץ עדכון לוח השידורים

### ISSUE THREAD

**Issue by burekas7** [Fishenzon/repo#92]
היי,

אני נעזר בקובץ 
epg.xml 
כדי ליצור את לוח השידורים בקודי בעזרת התוסף:
PVR IPTV Simple Client
לפעמים אני שם לב שפתאום הלוח שידורים לא מתעדכן עבור ערוצים מסוימים או שחסר מידע מזמן מסוים והלאה.
כשאני לוחץ בהגדרות על "הורדת לוח שידורים ידנית" הוא מעדכן רק את הקובץ:
epj.json
ולא את:
epg.xml

זה אמור להיות ככה?
איך לגרום גם ל-
xml
להתעדכן?
באיזה מצבים ה-
xml
מתעדכן?
בכל הפעלה של קודי?

תודה מראש.

**Comment by Fishenzon** [comment]
בוקר טוב.
הקבצים של הטלויזיה חיה:
xml, m3u
מתעדכנים בהפעלת קודי ומאז כל 12 שעות
אתה יכול לעדכן אותם ידנית דרך ההגדרות בלשונית של טלויזיה חיה

![screenshot000](https://user-images.githubusercontent.com/29551534/97264170-1df32100-182d-11eb-95a9-2326dbd15dc8.png)

**Comment by burekas7** [comment]
תודה רבה
