### ISSUE TITLE
אתר ספורט 5 - עובד? 

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#94]
תוכל בבקשה לבדוק? 
אצלי באנדרואיד לא מצליח לראות.

**Comment by Fishenzon** [comment]
הלינק שמגיע מהאתר לא עובד.
רק הלינק שנמצא בתחנות רדיו עובד, הוא זהה ללינק שמשודר באתר עצמו. רק שמע, ללא תמונה

**Comment by Fishenzon** [comment]
בוקר טוב.
לפי איך שזה נראה כרגע, הלינק כנראה מת

**Comment by tzagim** [comment]
כרגע זה פועל :)

**Comment by rafi-d** [comment]
נכון, תודה על העדכון. 
רק חבל שהאכות היתה ונשארה זבל...
