### ISSUE TITLE
Reshet13 VOD content isn't working

### ISSUE THREAD

**Issue by dpinhas** [Fishenzon/repo#95]
I'm guessing it is related to the changes they did to their website 20 days ago, maybe it changed again?

**Comment by dpinhas** [comment]
I'm running the latest 2.7.7 btw

**Comment by Fishenzon** [comment]
ערב טוב
האם מדובר על תכנים ששודרו לפני יותר משבועיים?
האם אתה צופה מחו"ל?
אתה יכול לנסות לצפות דרך האתר עצמו ולראות אם אתה מצליח לצפות. אם לא, זאת הסיבה שאתה לא מצליח גם דרך ההרחבה.

**Comment by dpinhas** [comment]
This is about any content even from content that aired today, I’m watching
from Israel without any VPN.

I am able to view it from the web

I’ve tried to remove the add on and reinstall it, that didn’t help so I
guessed it is related to the source.
Can you try reproduce to see what I’m talking about?

**Comment by Fishenzon** [comment]
בוקר טוב.
על איזו מערכת מותקן הקובץ?
תוכל לשלוח קובץ
kodi.log
?
