### ISSUE TITLE
 כאן 11 עם כתוביות

### ISSUE THREAD

**Issue by israelchoen** [Fishenzon/repo#97]
שלום,
האם יש אפשרות להוסיף את ערוץ כאן 11 עם כתוביות?
https://kanlivep2event-i.akamaihd.net/hls/live/765937/765937/master.m3u8

כאן 11 דורש להתקין את
dailymotion,
וגם אחרי התקנה לא עובד. כאן 11 גיבוי עובד.

דרך אגב, הגירסא האחרונה של
IPTV merge
עובדת כעת עם עידן פלוס
https://forum.kodi.tv/showthread.php?tid=340691&pid=2991518#pid2991518

תודה

**Comment by Fishenzon** [comment]
תודה.
הוספתי את הערוץ עם הכתוביות
הוספתי גם את הערוץ מאתר דיילי מושן שמנגן באיכות 1080
ברגע שבאתר משתנית כתובת הניגון לכתובת באתר דיילימושן, קודי מבקש להתקין את ההרחבה שלהם בפעם הראשונה כדי שהלינק יוכל להתנגן. בדרך כלל צריך להפעיל מחדש את קודי כדי שזה יעבוד. בנוסף נפתח מסך ההגדרות של דיילימושן וכדאי לבחור באיכות מקסימלית
UHD
אתה יכול לנסות לנגן את הלינק ישירות ולראות אם זה מצליח

**Comment by israelchoen** [comment]
בדקתי את הלינק והבעיה היא אצלי...
כנראה הסינון של האינטרנט חוסם אצלי את דיילי מושן
במקום זה אני ישתמש בכאן 11 גיבוי
 תודה

**Comment by Fishenzon** [comment]
סבבה
הלינק הראשי של הערוץ מגיע מהאתר עצמו, גם הלינק של לקויי השמיעה מגיע מהאתר.
יש לינק גיבוי שפונה ישירות למה שיש בדרך כלל באתר.
יש לינק ישיר לדיילימושן שלפעמים האתר מפנה אליו.

**Comment by israelchoen** [comment]
שוב שלום,
אם אפשר להוסיף בעידכון הבא את כאן חינוכית (גיבוי) עם הלינק הזה
https://kanlivep2event-i.akamaihd.net/hls/live/747600/747600/master.m3u8
בגלל שהדיילימושן חסום אצלי
תודה על הכל
