### ISSUE TITLE
שום ערוץ לא עובד בעידן פלוס גם לא ב vod

### ISSUE THREAD

**Issue by jaguar5566** [Fishenzon/repo#99]
הפסיקו לעבוד לי כל הערוצים וגם הvod אני לא מצליח לצפות בשום תוכן בעידן פלוס 
גרסה 2.8.3

**Comment by jaguar5566** [comment]
כשאני מנסה להיכנס לערוץ או למשהו בויאודי זה טוען המון זמן ואז זה מראה למעלה כאילו הערוץ עומד להיפתח ואז זה פשוט מפסיק וחוזר לתפריט בלי להיכנס לערוץ , הסרתי את ההתקנה של עידן פלוס והתקנתי מחדש אבל זה לא הסתדר לי

**Comment by rafi-d** [comment]
תוספים אחרים בקודי כן עובדים מול האינטרנט?

**Comment by jaguar5566** [comment]
הורדתי את ההרחבה מfishenzon.github.io ואז התקנתי את וואלה ואת עידן פלוס ושניהם לא עובדים לי עשיתי נקה נתונים ואז מחקתי את הקודים התקנתי מחדש ושוב שניהם לא עובדים
עדכנתי לא מזמן את הסטרימר שיאומי מי בוקס גרסה לגרסה האחרונה שיצאה ובערך באותו הזמן התחילו לי הבעיות , יש לך אולי עצה לתת לי?

**Comment by rafi-d** [comment]
כן,  לא לדווח כאן על בעיות שלא קשורות לתוסף  ;)
נדמה לי שקראתי על בעיות בגרסאות חדשות של שיומי, אז תבדוק בפורומים רלוונטיים לזה.

אישית, אם הסטרימר לא בגרסה האחרונות של הCPU - S905X2 או X3 
הייתי משרדג סטרימר אפילו למשהו סיני פשוט שהיום  ב40$

**Comment by Fishenzon** [comment]
לא קשור להרחבה
